// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/auth/util/extension.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Auth.Util {

  /// <summary>Holder for reflection information generated from proto/clarifai/auth/util/extension.proto</summary>
  public static partial class ExtensionReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/auth/util/extension.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtensionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cihwcm90by9jbGFyaWZhaS9hdXRoL3V0aWwvZXh0ZW5zaW9uLnByb3RvEhJj",
            "bGFyaWZhaS5hdXRoLnV0aWwaJXByb3RvL2NsYXJpZmFpL2F1dGgvc2NvcGUv",
            "c2NvcGUucHJvdG8aJXByb3RvL2NsYXJpZmFpL2F1dGgvdHlwZXMvdHlwZXMu",
            "cHJvdG8aIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvOjkKEGNs",
            "X3ByaXZhdGVfZmllbGQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25z",
            "GMDzBCABKAg6OAoOY2xfcHJpdmF0ZV9ycGMSHi5nb29nbGUucHJvdG9idWYu",
            "TWV0aG9kT3B0aW9ucxjB8wQgASgIOlUKE2NsX2RlcGVuZGluZ19zY29wZXMS",
            "Hi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxjC8wQgAygOMhYuY2xh",
            "cmlmYWkuYXV0aC5zY29wZS5TOlUKDGNsX2F1dGhfdHlwZRIeLmdvb2dsZS5w",
            "cm90b2J1Zi5NZXRob2RPcHRpb25zGMPzBCABKA4yHS5jbGFyaWZhaS5hdXRo",
            "LnR5cGVzLkF1dGhUeXBlOj0KEmNsX3ByaXZhdGVfbWVzc2FnZRIfLmdvb2ds",
            "ZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjE8wQgASgIQiwKG2NvbS5jbGFy",
            "aWZhaS5ncnBjLmF1dGgudXRpbFABWgR1dGlsogIEQ0FJUGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Clarifai.Auth.Scope.ScopeReflection.Descriptor, global::Clarifai.Auth.Types.TypesReflection.Descriptor, global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { ExtensionExtensions.ClPrivateField, ExtensionExtensions.ClPrivateRpc, ExtensionExtensions.ClDependingScopes, ExtensionExtensions.ClAuthType, ExtensionExtensions.ClPrivateMessage }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of proto/clarifai/auth/util/extension.proto</summary>
  public static partial class ExtensionExtensions {
    /// <summary>
    /// indicates if this field should be private. If true, then internal use only. If False,
    /// then publicly avaliable to world.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> ClPrivateField =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(80320, pb::FieldCodec.ForBool(642560, false));
    /// <summary>
    /// indicates if this rpc should be private. If true, then internal use only. If False,
    /// then publicly available to world.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool> ClPrivateRpc =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, bool>(80321, pb::FieldCodec.ForBool(642568, false));
    /// <summary>
    /// For each grpc method we define a list of required low-level auth scopes that are needed
    /// for the key that is issuing the request. These are checked at authorization time for the
    /// request as one of the first things in the life of a request once it reaches out API
    /// servers. There are additional checks for each scope when the resource is used throughout the
    /// backend in order to protect that resource. For example, Inputs_Add protects the writes to the
    /// inputs DB table. Since we know every PostInputs call needs to do that, we add Inputs_Add scope
    /// to the cl_depending_scopes list for the PostInputs method.
    ///
    /// This is only checked valid when used with KeyAuth cl_auth_type.
    ///
    /// This should be the absolute minimum required scopes to make API calls with the method
    /// that this options is used for. If there are some scopes that are needed some of the time
    /// depending on the request, then leave those out as they will be checked at the tighest
    /// possible portion of the codebase to protect that resource and won't effect every API call. For
    /// example, the PostAnnotations call is often used to add concepts as well. If those concepts are
    /// new, then the Concepts_Add scope will be needed. But since you don't always annotate with
    /// concepts, it is not a hard requirements that Concepts_Add is used.
    /// </summary>
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.MethodOptions, global::Clarifai.Auth.Scope.S> ClDependingScopes =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.MethodOptions, global::Clarifai.Auth.Scope.S>(80322, pb::FieldCodec.ForEnum(642578, x => (int) x, x => (global::Clarifai.Auth.Scope.S) x));
    /// <summary>
    /// This is the authorizer type for the endpoint our of multiple backend authorizers.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Clarifai.Auth.Types.AuthType> ClAuthType =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Clarifai.Auth.Types.AuthType>(80323, pb::FieldCodec.ForEnum(642584, x => (int) x, x => (global::Clarifai.Auth.Types.AuthType) x, global::Clarifai.Auth.Types.AuthType.Undef));
    /// <summary>
    /// indicates if this message should be private. If true, then internal use only. If False,
    /// then publicly avaliable to world.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool> ClPrivateMessage =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, bool>(80324, pb::FieldCodec.ForBool(642592, false));
  }

}

#endregion Designer generated code
