// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/utils/extensions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Api.Utils {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/utils/extensions.proto</summary>
  public static partial class ExtensionsReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/utils/extensions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtensionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilwcm90by9jbGFyaWZhaS9hcGkvdXRpbHMvZXh0ZW5zaW9ucy5wcm90bxIS",
            "Y2xhcmlmYWkuYXBpLnV0aWxzGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRv",
            "ci5wcm90bzo5ChBjbF9zaG93X2lmX2VtcHR5Eh0uZ29vZ2xlLnByb3RvYnVm",
            "LkZpZWxkT3B0aW9ucxjQhgMgASgIOjQKC2NsX21vcmV0YWdzEh0uZ29vZ2xl",
            "LnByb3RvYnVmLkZpZWxkT3B0aW9ucxjRhgMgASgJOjkKEGNsX2RlZmF1bHRf",
            "ZmxvYXQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGNqGAyABKAJC",
            "LQobY29tLmNsYXJpZmFpLmdycGMuYXBpLnV0aWxzUAFaBXV0aWxzogIEQ0FJ",
            "UGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { ExtensionsExtensions.ClShowIfEmpty, ExtensionsExtensions.ClMoretags, ExtensionsExtensions.ClDefaultFloat }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of proto/clarifai/api/utils/extensions.proto</summary>
  public static partial class ExtensionsExtensions {
    /// <summary>
    /// If True then we will return this field with it's zero value even if not set.
    /// This means in json responses empty lists will appear instead of not being returned (which is
    /// the default convention for proto3). For int's we will show 0, for floats 0.0, etc.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> ClShowIfEmpty =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50000, pb::FieldCodec.ForBool(400000, false));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> ClMoretags =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50001, pb::FieldCodec.ForString(400010, ""));
    /// <summary>
    /// For float fields where this is set, this value will be used by the server when parsing the
    /// request and the field is not present in the request. If the field is present in the request,
    /// then the value of the field will be used instead. This is ONLY used for json requests as binary
    /// proto requests are expected to always set the field.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float> ClDefaultFloat =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, float>(50010, pb::FieldCodec.ForFloat(400085, 0F));
  }

}

#endregion Designer generated code
