// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/status/status_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Api.Status {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/status/status_code.proto</summary>
  public static partial class StatusCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/status/status_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatusCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Citwcm90by9jbGFyaWZhaS9hcGkvc3RhdHVzL3N0YXR1c19jb2RlLnByb3Rv",
            "EhNjbGFyaWZhaS5hcGkuc3RhdHVzKqBjCgpTdGF0dXNDb2RlEggKBFpFUk8Q",
            "ABIMCgdTVUNDRVNTEJBOEhEKDE1JWEVEX1NUQVRVUxCaThIMCgdGQUlMVVJF",
            "EKROEg4KCVRSWV9BR0FJThCuThIUCg9OT1RfSU1QTEVNRU5URUQQuE4SCgoF",
            "TU9WRUQQwk4SCwoGVEVBUE9UEMxOEhgKE0NPTk5fQUNDT1VOVF9JU1NVRVMQ",
            "+FUSGwoSQ09OTl9UT0tFTl9JTlZBTElEEPlVGgIIARIdChhDT05OX0NSRURF",
            "TlRJQUxTX0lOVkFMSUQQ+lUSHQoYQ09OTl9FWENFRURfSE9VUkxZX0xJTUlU",
            "EPtVEh4KGUNPTk5fRVhDRUVEX01PTlRITFlfTElNSVQQ/FUSEwoOQ09OTl9U",
            "SFJPVFRMRUQQ/VUSGAoTQ09OTl9FWENFRURTX0xJTUlUUxD+VRIdChhDT05O",
            "X0lOU1VGRklDSUVOVF9TQ09QRVMQ/1USFQoQQ09OTl9LRVlfSU5WQUxJRBCA",
            "VhIXChJDT05OX0tFWV9OT1RfRk9VTkQQgVYSHAoXQ09OTl9CQURfUkVRVUVT",
            "VF9GT1JNQVQQ3FYSGAoTQ09OTl9ET0VTX05PVF9FWElTVBDdVhIZChRDT05O",
            "X0lOVkFMSURfUkVRVUVTVBDeVhIcChdDT05OX01FVEhPRF9OT1RfQUxMT1dF",
            "RBDfVhIZChRDT05OX05PX0dEUFJfQ09OU0VOVBDgVhIXChJDT05OX0lOVkFM",
            "SURfUkFOR0UQ4VYSHgoZQ09OTl9BVVRIX01FVEhPRF9ESVNBQkxFRBDAVxIT",
            "Cg1NT0RFTF9UUkFJTkVEEOykARIUCg5NT0RFTF9UUkFJTklORxDtpAESFQoP",
            "TU9ERUxfVU5UUkFJTkVEEO6kARIfChlNT0RFTF9RVUVVRURfRk9SX1RSQUlO",
            "SU5HEO+kARIVCg9NT0RFTF9VUExPQURJTkcQ8KQBEhwKFk1PREVMX1VQTE9B",
            "RElOR19GQUlMRUQQ8aQBEhsKFU1PREVMX1RSQUlOSU5HX0ZBSUxFRBDypAES",
            "FAoOTU9ERUxfQlVJTERJTkcQ86QBEhsKFU1PREVMX0JVSUxESU5HX0ZBSUxF",
            "RBD0pAESIgocTU9ERUxfQlVJTERfVU5FWFBFQ1RFRF9FUlJPUhD1pAESHAoW",
            "TU9ERUxfVFJBSU5JTkdfTk9fREFUQRD2pAESIQobTU9ERUxfVFJBSU5JTkdf",
            "Tk9fUE9TSVRJVkVTEPekARIqCiRNT0RFTF9UUkFJTklOR19PTkVfVlNfTl9T",
            "SU5HTEVfQ0xBU1MQ+KQBEh4KGE1PREVMX1RSQUlOSU5HX1RJTUVEX09VVBD5",
            "pAESIgocTU9ERUxfVFJBSU5JTkdfV0FJVElOR19FUlJPUhD6pAESIgocTU9E",
            "RUxfVFJBSU5JTkdfVU5LTk9XTl9FUlJPUhD7pAESJgocTU9ERUxfVFJBSU5J",
            "TkdfTVNHX1JFREVMSVZFUhD8pAEaAggBEiYKIE1PREVMX1RSQUlOSU5HX0lO",
            "U1VGRklDSUVOVF9EQVRBEP2kARIjCh1NT0RFTF9UUkFJTklOR19JTlZBTElE",
            "X1BBUkFNUxD+pAESNAouTU9ERUxfVFJBSU5JTkdfSU5WQUxJRF9EQVRBX1RP",
            "TEVSQU5DRV9FWENFRURFRBD/pAESGgoUTU9ERUxfTU9ESUZZX1NVQ0NFU1MQ",
            "nqUBEhoKFE1PREVMX01PRElGWV9QRU5ESU5HEJ+lARIZChNNT0RFTF9NT0RJ",
            "RllfRkFJTEVEEKClARIaChRNT0RFTF9ET0VTX05PVF9FWElTVBDQpQESHQoX",
            "TU9ERUxfUEVSTUlTU0lPTl9ERU5JRUQQ0aUBEhwKFk1PREVMX0lOVkFMSURf",
            "QVJHVU1FTlQQ0qUBEhsKFU1PREVMX0lOVkFMSURfUkVRVUVTVBDTpQESFQoP",
            "TU9ERUxfRVZBTFVBVEVEELSmARIWChBNT0RFTF9FVkFMVUFUSU5HELWmARIZ",
            "ChNNT0RFTF9OT1RfRVZBTFVBVEVEELamARIhChtNT0RFTF9RVUVVRURfRk9S",
            "X0VWQUxVQVRJT04Qt6YBEiAKGk1PREVMX0VWQUxVQVRJT05fVElNRURfT1VU",
            "EL6mARIkCh5NT0RFTF9FVkFMVUFUSU9OX1dBSVRJTkdfRVJST1IQv6YBEiQK",
            "Hk1PREVMX0VWQUxVQVRJT05fVU5LTk9XTl9FUlJPUhDApgESHQoXTU9ERUxf",
            "UFJFRElDVElPTl9GQUlMRUQQwaYBEigKHk1PREVMX0VWQUxVQVRJT05fTVNH",
            "X1JFREVMSVZFUhDCpgEaAggBEiIKHE1PREVMX0VWQUxVQVRJT05fTkVFRF9M",
            "QUJFTFMQw6YBEiIKHE1PREVMX0VWQUxVQVRJT05fTkVFRF9JTlBVVFMQxKYB",
            "Eh0KF01PREVMX0VWQUxVQVRJT05fRkFJTEVEEMWmARIdChdNT0RFTF9ERVBM",
            "T1lNRU5UX0ZBSUxFRBDmpgESFQoPTU9ERUxfREVQTE9ZSU5HEOemARIhChtN",
            "T0RFTF9RVUVVRURfRk9SX0RFUExPWU1FTlQQ6KYBEhgKEk1PREVMX05PVF9E",
            "RVBMT1lFRBDppgESHQoXTU9ERUxfQlVTWV9QTEVBU0VfUkVUUlkQ6qYBEhMK",
            "DU1PREVMX0xPQURJTkcQ66YBEiYKIE1PREVMX1JFRkVSRU5DRV9JTlZBTElE",
            "X0FSR1VNRU5UEJinARIqCiRNT0RFTF9FWEFNUExFX0lOUFVUX0lOVkFMSURf",
            "QVJHVU1FTlQQrKcBEhQKDk1PREVMX0VYUE9SVEVEEPynARIVCg9NT0RFTF9F",
            "WFBPUlRJTkcQ/acBEhwKFk1PREVMX0VYUE9SVElOR19GQUlMRUQQ/qcBEhoK",
            "FE1PREVMX0VYUE9SVF9QRU5ESU5HEP+nARIgChpXT1JLRkxPV19OT19NQVRD",
            "SElOR19JTlBVVBDxqwESJAoeV09SS0ZMT1dfUkVRVUlSRV9UUkFJTkVEX01P",
            "REVMEPKrARIYChJXT1JLRkxPV19EVVBMSUNBVEUQ1KwBEiEKG1dPUktGTE9X",
            "X1VOU1VQUE9SVEVEX0ZPUk1BVBDVrAESHQoXV09SS0ZMT1dfRE9FU19OT1Rf",
            "RVhJU1QQ1qwBEiAKGldPUktGTE9XX1BFUk1JU1NJT05fREVOSUVEENesARIf",
            "ChlXT1JLRkxPV19JTlZBTElEX0FSR1VNRU5UENisARIdChdXT1JLRkxPV19J",
            "TlZBTElEX1JFQ0lQRRDZrAESHwoZV09SS0ZMT1dfSU5WQUxJRF9URU1QTEFU",
            "RRDarAESHAoWV09SS0ZMT1dfSU5WQUxJRF9HUkFQSBDbrAESHwoZV09SS0ZM",
            "T1dfSU5URVJOQUxfRkFJTFVSRRDcrAESHgoYV09SS0ZMT1dfSU5WQUxJRF9S",
            "RVFVRVNUENezARIdChdXT1JLRkxPV19NT0RJRllfU1VDQ0VTUxCGrQESHQoX",
            "V09SS0ZMT1dfTU9ESUZZX1BFTkRJTkcQh60BEhwKFldPUktGTE9XX01PRElG",
            "WV9GQUlMRUQQiK0BEh0KF1dPUktGTE9XX1JFSU5ERVhfRkFJTEVEEImtARIc",
            "ChZDT05DRVBUX01PRElGWV9TVUNDRVNTEO60ARIcChZDT05DRVBUX01PRElG",
            "WV9QRU5ESU5HEO+0ARIbChVDT05DRVBUX01PRElGWV9GQUlMRUQQ8LQBEhgK",
            "EkFOTk9UQVRJT05fU1VDQ0VTUxDWvAESGAoSQU5OT1RBVElPTl9QRU5ESU5H",
            "ENe8ARIXChFBTk5PVEFUSU9OX0ZBSUxFRBDYvAESHwoZQU5OT1RBVElPTl9V",
            "TktOT1dOX1NUQVRVUxDavAESIQobQU5OT1RBVElPTl9JTlZBTElEX0FSR1VN",
            "RU5UENu8ARIiChxBTk5PVEFUSU9OX1BFUk1JU1NJT05fREVOSUVEENy8ARIg",
            "ChpBTk5PVEFUSU9OX0FXQUlUSU5HX1JFVklFVxDdvAESKgokQU5OT1RBVElP",
            "Tl9BV0FJVElOR19DT05TRU5TVVNfUkVWSUVXEN+8ARIeChhBTk5PVEFUSU9O",
            "X1JFVklFV19ERU5JRUQQ3rwBEh8KGUFOTk9UQVRJT05fTU9ESUZZX1NVQ0NF",
            "U1MQur0BEh8KGUFOTk9UQVRJT05fTU9ESUZZX1BFTkRJTkcQu70BEh4KGEFO",
            "Tk9UQVRJT05fTU9ESUZZX0ZBSUxFRBC8vQESJgogTUVUQURBVEFfSU5WQUxJ",
            "RF9QQVRDSF9BUkdVTUVOVFMQxMIBEhwKFk1FVEFEQVRBX1BBUlNJTkdfSVNT",
            "VUUQxcIBEiEKG01FVEFEQVRBX01BTklQVUxBVElPTl9JU1NVRRDGwgESHAoW",
            "VFJBSU5FUl9KT0JfU1RBVEVfTk9ORRCowwESHgoYVFJBSU5FUl9KT0JfU1RB",
            "VEVfUVVFVUVEEKnDARIfChlUUkFJTkVSX0pPQl9TVEFURV9SVU5OSU5HEKrD",
            "ARIgChpUUkFJTkVSX0pPQl9TVEFURV9DT01QTEVURRCrwwESHQoXVFJBSU5F",
            "Ul9KT0JfU1RBVEVfRVJST1IQrMMBEhcKEURBVEFfRFVNUF9TVUNDRVNTEL7E",
            "ARIXChFEQVRBX0RVTVBfUEVORElORxC/xAESFgoQREFUQV9EVU1QX0ZBSUxF",
            "RBDAxAESGwoVREFUQV9EVU1QX0lOX1BST0dSRVNTEMHEARIbChFEQVRBX0RV",
            "TVBfTk9fREFUQRDCxAEaAggBEiAKGkRBVEFfRFVNUF9VTkVYUEVDVEVEX0VS",
            "Uk9SEMPEARIeChhEQVRBX0RVTVBfRVhQT1JUX1NVQ0NFU1MQ0sQBEh4KGERB",
            "VEFfRFVNUF9FWFBPUlRfUEVORElORxDTxAESHQoXREFUQV9EVU1QX0VYUE9S",
            "VF9GQUlMRUQQ1MQBEiIKHERBVEFfRFVNUF9FWFBPUlRfSU5fUFJPR1JFU1MQ",
            "1cQBEicKIURBVEFfRFVNUF9FWFBPUlRfVU5FWFBFQ1RFRF9FUlJPUhDWxAES",
            "HQoXQVBQX0RVUExJQ0FUSU9OX1NVQ0NFU1MQ8MQBEhwKFkFQUF9EVVBMSUNB",
            "VElPTl9GQUlMRUQQ8cQBEh0KF0FQUF9EVVBMSUNBVElPTl9QRU5ESU5HEPLE",
            "ARIhChtBUFBfRFVQTElDQVRJT05fSU5fUFJPR1JFU1MQ88QBEiUKH0FQUF9E",
            "VVBMSUNBVElPTl9JTlZBTElEX1JFUVVFU1QQ9MQBEhsKFU1PRFVMRV9ET0VT",
            "X05PVF9FWElTVBDUxQESHgoYTU9EVUxFX1BFUk1JU1NJT05fREVOSUVEENXF",
            "ARIdChdNT0RVTEVfSU5WQUxJRF9BUkdVTUVOVBDWxQESHAoWTU9EVUxFX0lO",
            "VkFMSURfUkVRVUVTVBDXxQESHAoWQlVMS19PUEVSQVRJT05fU1VDQ0VTUxC4",
            "xgESGwoVQlVMS19PUEVSQVRJT05fRkFJTEVEELnGARIcChZCVUxLX09QRVJB",
            "VElPTl9QRU5ESU5HELrGARIgChpCVUxLX09QRVJBVElPTl9JTl9QUk9HUkVT",
            "UxC7xgESJAoeQlVMS19PUEVSQVRJT05fSU5WQUxJRF9SRVFVRVNUELzGARIe",
            "ChhCVUxLX09QRVJBVElPTl9DQU5DRUxMRUQQvcYBEiUKH0JVTEtfT1BFUkFU",
            "SU9OX1VORVhQRUNURURfRVJST1IQvsYBEhsKFVJVTk5FUl9ET0VTX05PVF9F",
            "WElTVBCAyAESHgoYUlVOTkVSX1BFUk1JU1NJT05fREVOSUVEEIHIARIdChdS",
            "VU5ORVJfSU5WQUxJRF9BUkdVTUVOVBCCyAESHAoWUlVOTkVSX0lOVkFMSURf",
            "UkVRVUVTVBCDyAESGAoSUlVOTkVSX05FRURTX1JFVFJZEITIARIZChNSVU5O",
            "RVJfU1RSRUFNX1NUQVJUEIXIARIXChFSVU5ORVJfU1RSRUFNX0VORBCGyAES",
            "GwoVUlVOTkVSX0lURU1fQ0FOQ0VMTEVEEIfIARIeChhSVU5ORVJfUFJPQ0VT",
            "U0lOR19GQUlMRUQQiMgBEh0KF05PREVQT09MX0RPRVNfTk9UX0VYSVNUEOTI",
            "ARIfChlOT0RFUE9PTF9JTlZBTElEX0FSR1VNRU5UEOXIARIeChhOT0RFUE9P",
            "TF9JTlZBTElEX1JFUVVFU1QQ5sgBEiQKHkNPTVBVVEVfQ0xVU1RFUl9ET0VT",
            "X05PVF9FWElTVBDIyQESJgogQ09NUFVURV9DTFVTVEVSX0lOVkFMSURfQVJH",
            "VU1FTlQQyckBEiUKH0NPTVBVVEVfQ0xVU1RFUl9JTlZBTElEX1JFUVVFU1QQ",
            "yskBEh8KGURFUExPWU1FTlRfRE9FU19OT1RfRVhJU1QQrMoBEiEKG0RFUExP",
            "WU1FTlRfSU5WQUxJRF9BUkdVTUVOVBCtygESIAoaREVQTE9ZTUVOVF9JTlZB",
            "TElEX1JFUVVFU1QQrsoBEiIKHElOU1RBTkNFX1RZUEVfRE9FU19OT1RfRVhJ",
            "U1QQkMsBEiQKHklOU1RBTkNFX1RZUEVfSU5WQUxJRF9BUkdVTUVOVBCRywES",
            "IwodSU5TVEFOQ0VfVFlQRV9JTlZBTElEX1JFUVVFU1QQkssBEisKJUNPTVBV",
            "VEVfUExBTkVfTUVUUklDU19JTlZBTElEX1JFUVVFU1QQ9MsBEiIKHFBJUEVM",
            "SU5FX1NURVBfRE9FU19OT1RfRVhJU1QQ2MwBEiQKHlBJUEVMSU5FX1NURVBf",
            "SU5WQUxJRF9BUkdVTUVOVBDZzAESIwodUElQRUxJTkVfU1RFUF9JTlZBTElE",
            "X1JFUVVFU1QQ2swBEh0KF1BJUEVMSU5FX1NURVBfVVBMT0FESU5HENvMARIk",
            "Ch5QSVBFTElORV9TVEVQX1VQTE9BRElOR19GQUlMRUQQ3MwBEhwKFlBJUEVM",
            "SU5FX1NURVBfQlVJTERJTkcQ3cwBEiMKHVBJUEVMSU5FX1NURVBfQlVJTERJ",
            "TkdfRkFJTEVEEN7MARIqCiRQSVBFTElORV9TVEVQX0JVSUxEX1VORVhQRUNU",
            "RURfRVJST1IQ38wBEhkKE1BJUEVMSU5FX1NURVBfUkVBRFkQ4MwBEhMKDUlO",
            "UFVUX1NVQ0NFU1MQsOoBEhMKDUlOUFVUX1BFTkRJTkcQseoBEhIKDElOUFVU",
            "X0ZBSUxFRBCy6gESFwoRSU5QVVRfSU5fUFJPR1JFU1MQs+oBEiAKFklOUFVU",
            "X0RPV05MT0FEX1NVQ0NFU1MQsOoBGgIIARIgChZJTlBVVF9ET1dOTE9BRF9Q",
            "RU5ESU5HELHqARoCCAESHwoVSU5QVVRfRE9XTkxPQURfRkFJTEVEELLqARoC",
            "CAESJAoaSU5QVVRfRE9XTkxPQURfSU5fUFJPR1JFU1MQs+oBGgIIARIgChpJ",
            "TlBVVF9TVEFUVVNfVVBEQVRFX0ZBSUxFRBC06gESGQoTSU5QVVRfREVMRVRF",
            "X0ZBSUxFRBC16gESFQoPSU5QVVRfRFVQTElDQVRFEJTrARIeChhJTlBVVF9V",
            "TlNVUFBPUlRFRF9GT1JNQVQQlesBEhoKFElOUFVUX0RPRVNfTk9UX0VYSVNU",
            "EJbrARIdChdJTlBVVF9QRVJNSVNTSU9OX0RFTklFRBCX6wESHAoWSU5QVVRf",
            "SU5WQUxJRF9BUkdVTUVOVBCY6wESFgoQSU5QVVRfT1ZFUl9MSU1JVBCZ6wES",
            "FwoRSU5QVVRfSU5WQUxJRF9VUkwQmusBEhoKFElOUFVUX01PRElGWV9TVUND",
            "RVNTEPjrARIaChRJTlBVVF9NT0RJRllfUEVORElORxD56wESGQoTSU5QVVRf",
            "TU9ESUZZX0ZBSUxFRBD76wESHwoZSU5QVVRfU1RPUkFHRV9IT1NUX0ZBSUxF",
            "RBCC7AESHQoXQUxMX0lOUFVUX0lOVkFMSURfQllURVMQ3OwBEhsKFUlOUFVU",
            "X0NMVVNURVJfU1VDQ0VTUxDA7QESGwoVSU5QVVRfQ0xVU1RFUl9QRU5ESU5H",
            "EMHtARIaChRJTlBVVF9DTFVTVEVSX0ZBSUxFRBDC7QESHwoZSU5QVVRfQ0xV",
            "U1RFUl9JTl9QUk9HUkVTUxDD7QESGwoVSU5QVVRfUkVJTkRFWF9TVUNDRVNT",
            "EKTuARIbChVJTlBVVF9SRUlOREVYX1BFTkRJTkcQpe4BEhoKFElOUFVUX1JF",
            "SU5ERVhfRkFJTEVEEKbuARIfChlJTlBVVF9SRUlOREVYX0lOX1BST0dSRVNT",
            "EKfuARIiChxJTlBVVF9WSURFT19ET1dOTE9BRF9TVUNDRVNTEJjyARIiChxJ",
            "TlBVVF9WSURFT19ET1dOTE9BRF9QRU5ESU5HEJnyARIhChtJTlBVVF9WSURF",
            "T19ET1dOTE9BRF9GQUlMRUQQmvIBEhsKFUlOUFVUX1ZJREVPX0RVUExJQ0FU",
            "RRD88gESJAoeSU5QVVRfVklERU9fVU5TVVBQT1JURURfRk9STUFUEP3yARIg",
            "ChpJTlBVVF9WSURFT19ET0VTX05PVF9FWElTVBD+8gESIwodSU5QVVRfVklE",
            "RU9fUEVSTUlTU0lPTl9ERU5JRUQQ//IBEiIKHElOUFVUX1ZJREVPX0lOVkFM",
            "SURfQVJHVU1FTlQQgPMBEhwKFklOUFVUX1ZJREVPX09WRVJfTElNSVQQgfMB",
            "Eh0KF0lOUFVUX1ZJREVPX0lOVkFMSURfVVJMEILzARIgChpJTlBVVF9WSURF",
            "T19NT0RJRllfU1VDQ0VTUxDg8wESIAoaSU5QVVRfVklERU9fTU9ESUZZX1BF",
            "TkRJTkcQ4fMBEh8KGUlOUFVUX1ZJREVPX01PRElGWV9GQUlMRUQQ4/MBEiUK",
            "H0lOUFVUX1ZJREVPX1NUT1JBR0VfSE9TVF9GQUlMRUQQ6vMBEiQKHkFMTF9J",
            "TlBVVF9WSURFT1NfSU5WQUxJRF9CWVRFUxDE9AESJAoeSU5QVVRfVklERU9f",
            "UFJPQ0VTU0lOR19TVUNDRVNTEKj1ARIkCh5JTlBVVF9WSURFT19QUk9DRVNT",
            "SU5HX1BFTkRJTkcQsvUBEiMKHUlOUFVUX1ZJREVPX1BST0NFU1NJTkdfRkFJ",
            "TEVEELz1ARInCiFJTlBVVF9WSURFT19TVE9SQUdFX0lOQ09OU0lTVEVOQ1kQ",
            "xvUBEiEKG0lOUFVUX1ZJREVPX1NUT1JBR0VfRkFJTFVSRRDQ9QESKAoiSU5Q",
            "VVRfVklERU9fVVJMX0dFTkVSQVRJT05fRkFJTFVSRRDa9QESHQoXSU5QVVRf",
            "Q09OTkVDVElPTl9GQUlMRUQQvLgCEiYKIFJFUVVFU1RfRElTQUJMRURfRk9S",
            "X01BSU5URU5BTkNFEL24AhIvCiVJTlBVVF9XUklURVNfRElTQUJMRURfRk9S",
            "X01BSU5URU5BTkNFEL64AhoCCAESGwoVSU5QVVRfSU5WQUxJRF9SRVFVRVNU",
            "EL+4AhIdChdQUkVESUNUX0lOVkFMSURfUkVRVUVTVBDBuAISHAoWU0VBUkNI",
            "X0lOVkFMSURfUkVRVUVTVBDCuAISHgoYQ09OQ0VQVFNfSU5WQUxJRF9SRVFV",
            "RVNUEMO4AhIbChVTVEFUU19JTlZBTElEX1JFUVVFU1QQxLgCEhwKFkRBVEFC",
            "QVNFX0RVUExJQ0FURV9LRVkQyrgCEiAKGkRBVEFCQVNFX1NUQVRFTUVOVF9U",
            "SU1FT1VUEMu4AhIkCh5EQVRBQkFTRV9JTlZBTElEX1JPV1NfQUZGRUNURUQQ",
            "zLgCEiAKGkRBVEFCQVNFX0RFQURMT0NLX0RFVEVDVEVEEM24AhIYChJEQVRB",
            "QkFTRV9GQUlMX1RBU0sQzrgCEiYKIERBVEFCQVNFX0ZBSUxfVE9fR0VUX0NP",
            "Tk5FQ1RJT05TEM+4AhIfChlEQVRBQkFTRV9UT09fTUFOWV9DTElFTlRTENC4",
            "AhIiChxEQVRBQkFTRV9DT05TVFJBSU5UX1ZJT0xBVEVEENG4AhIXChFEQVRB",
            "QkFTRV9DQU5DRUxFRBDVuAISHwoZQVNZTkNfV09SS0VSX01VTFRJX0VSUk9S",
            "UxDUuAISHAoWUlBDX1JFUVVFU1RfUVVFVUVfRlVMTBDeuAISHAoWUlBDX1NF",
            "UlZFUl9VTkFWQUlMQUJMRRDfuAISGQoTUlBDX1JFUVVFU1RfVElNRU9VVBDg",
            "uAISIwodUlBDX01BWF9NRVNTQUdFX1NJWkVfRVhDRUVERUQQ4bgCEhIKDFJQ",
            "Q19DQU5DRUxFRBDjuAISGAoSUlBDX1VOS05PV05fTUVUSE9EEOS4AhIeChhS",
            "RVFVRVNUX0NBTkNFTEVEX0JZX1VTRVIQ5bgCEh4KGENMVVNURVJfSU5URVJO",
            "QUxfRkFJTFVSRRCg0AISHwoZRVhURVJOQUxfQ09OTkVDVElPTl9FUlJPUhDi",
            "uAISGgoUUVVFUllfSU5WQUxJRF9TWU5UQVgQ8rgCEhYKEFFVRVVFX0NPTk5f",
            "RVJST1IQqMACEiEKG1FVRVVFX0NMT1NFX1JFUVVFU1RfVElNRU9VVBCqwAIS",
            "FwoRUVVFVUVfQ09OTl9DTE9TRUQQq8ACEh8KGVFVRVVFX1BVQkxJU0hfQUNL",
            "X1RJTUVPVVQQrMACEhkKE1FVRVVFX1BVQkxJU0hfRVJST1IQrcACEiAKGlFV",
            "RVVFX1NVQlNDUklQVElPTl9USU1FT1VUEK7AAhIeChhRVUVVRV9TVUJTQ1JJ",
            "UFRJT05fRVJST1IQr8ACEh4KGFFVRVVFX01BUlNIQUxMSU5HX0ZBSUxFRBCw",
            "wAISIAoaUVVFVUVfVU5NQVJTSEFMTElOR19GQUlMRUQQscACEicKIVFVRVVF",
            "X01BWF9NU0dfUkVERUxJVkVSWV9FWENFRURFRBCywAISFwoRUVVFVUVfQUNL",
            "X0ZBSUxVUkUQs8ACEhMKDVNRU19PVkVSTElNSVQQjMECEiAKGlNRU19JTlZB",
            "TElEX1JFQ0VJUFRfSEFORExFEI3BAhIRCgtTUVNfVU5LTk9XThCOwQISHQoX",
            "U0VBUkNIX0lOVEVSTkFMX0ZBSUxVUkUQ+c8CEh8KGVNFQVJDSF9QUk9KRUNU",
            "SU9OX0ZBSUxVUkUQ+s8CEh8KGVNFQVJDSF9QUkVESUNUSU9OX0ZBSUxVUkUQ",
            "+88CEicKIVNFQVJDSF9CWV9OT1RfRlVMTFlfSU5ERVhFRF9JTlBVVBD8zwIS",
            "IAoaU0FWRURfU0VBUkNIX01PRElGWV9GQUlMRUQQ/c8CEh8KGVNFQVJDSF9D",
            "T1VOVFNfVU5BVkFJTEFCTEUQ/s8CEhcKEUVWQUxVQVRJT05fUVVFVUVEENzQ",
            "AhIcChZFVkFMVUFUSU9OX0lOX1BST0dSRVNTEN3QAhIYChJFVkFMVUFUSU9O",
            "X1NVQ0NFU1MQ3tACEigKIkVWQUxVQVRJT05fRkFJTEVEX1RPX1JFVFJJRVZF",
            "X0RBVEEQ39ACEiEKG0VWQUxVQVRJT05fSU5WQUxJRF9BUkdVTUVOVBDg0AIS",
            "FwoRRVZBTFVBVElPTl9GQUlMRUQQ4dACEhgKEkVWQUxVQVRJT05fUEVORElO",
            "RxDi0AISGgoURVZBTFVBVElPTl9USU1FRF9PVVQQ49ACEiEKG0VWQUxVQVRJ",
            "T05fVU5FWFBFQ1RFRF9FUlJPUhDk0AISFgoQRVZBTFVBVElPTl9NSVhFRBDl",
            "0AISGAoSU1RSSVBFX0VWRU5UX0VSUk9SEOHXAhIQCgpDQUNIRV9NSVNTEMnf",
            "AhImCiBSRURJU19TQ1JJUFRfRVhJVEVEX1dJVEhfRkFJTFVSRRDK3wISFgoQ",
            "UkVESVNfU1RSRUFNX0VSUhDL3wISGAoSUkVESVNfTk9fQ09OU1VNRVJTEMzf",
            "AhIaChRSRURJU19TVFJFQU1fQkFDS09GRhDN3wISGAoSU0lHTlVQX0VWRU5U",
            "X0VSUk9SELHnAhIUCg5TSUdOVVBfRkxBR0dFRBCy5wISGgoURklMRVRZUEVf",
            "VU5TVVBQT1JURUQQs+cCEh8KGUFQUF9DT1VOVF9JTlZBTElEX01FU1NBR0UQ",
            "me8CEicKIUFQUF9DT1VOVF9VUERBVEVfSU5DUkVNRU5UX0ZBSUxFRBCa7wIS",
            "HgoYQVBQX0NPVU5UX1JFQlVJTERfRkFJTEVEEJvvAhIgChpBUFBfQ09VTlRf",
            "SU5URVJOQUxfRkFJTFVSRRCc7wISFwoRTVBfRE9XTkxPQURfRVJST1IQ/e8C",
            "EhoKFE1QX1JFU09MVkVfRE5TX0VSUk9SEP7vAhIpCiNNUF9ET1dOTE9BRF9N",
            "QVhfU0laRV9FWENFRURFRF9FUlJPUhD/7wISGwoVTVBfSU1BR0VfREVDT0RF",
            "X0VSUk9SEIDwAhIZChNNUF9JTlZBTElEX0FSR1VNRU5UEIHwAhIfChlNUF9J",
            "TUFHRV9QUk9DRVNTSU5HX0VSUk9SEILwAhIZChNEQVRBVElFUl9DT05OX0VS",
            "Uk9SEOHwAhIXChFVU0VSX0NPTlNFTlRfRkFDRRDRhgMSFAoOV09SS0VSX01J",
            "U1NJTkcQuI4DEhMKDVdPUktFUl9BQ1RJVkUQuY4DEhUKD1dPUktFUl9JTkFD",
            "VElWRRC6jgMSFwoRQ09MTEVDVE9SX01JU1NJTkcQoJYDEhYKEENPTExFQ1RP",
            "Ul9BQ1RJVkUQoZYDEhgKEkNPTExFQ1RPUl9JTkFDVElWRRCilgMSIQobQ09M",
            "TEVDVE9SX1BPU1RfSU5QVVRfRkFJTEVEEKOWAxIqCiRTU09fSURFTlRJVFlf",
            "UFJPVklERVJfRE9FU19OT1RfRVhJU1QQiZ4DEhYKEFRBU0tfSU5fUFJPR1JF",
            "U1MQ8aUDEg8KCVRBU0tfRE9ORRDypQMSEgoMVEFTS19XT05UX0RPEPOlAxIR",
            "CgtUQVNLX0ZBSUxFRBD1pQMSDwoJVEFTS19JRExFEPalAxITCg1UQVNLX0NP",
            "TkZMSUNUENSmAxIaChRUQVNLX05PVF9JTVBMRU1FTlRFRBDVpgMSEgoMVEFT",
            "S19NSVNTSU5HENamAxIcChZUQVNLX1BFUk1JU1NJT05fREVOSUVEENemAxId",
            "ChdUQVNLX0FTU0lHTk1FTlRfU1VDQ0VTUxC4pwMSHQoXVEFTS19BU1NJR05N",
            "RU5UX1BFTkRJTkcQuacDEiUKH1RBU0tfQVNTSUdOTUVOVF9BV0FJVElOR19S",
            "RVZJRVcQuqcDEi8KKVRBU0tfQVNTSUdOTUVOVF9BV0FJVElOR19DT05TRU5T",
            "VVNfUkVWSUVXELunAxIeChhUQVNLX0FTU0lHTk1FTlRfUkVKRUNURUQQvKcD",
            "EiQKHlRBU0tfQVNTSUdOTUVOVF9SRVZJRVdfU1VDQ0VTUxCcqAMSJAoeVEFT",
            "S19BU1NJR05NRU5UX1JFVklFV19QRU5ESU5HEJ2oAxImCiBUQVNLX0FTU0lH",
            "Tk1FTlRfUkVWSUVXX0RJU01JU1NFRBCeqAMSGQoTTEFCRUxfT1JERVJfUEVO",
            "RElORxDZrQMSHQoXTEFCRUxfT1JERVJfSU5fUFJPR1JFU1MQ2q0DEhkKE0xB",
            "QkVMX09SREVSX1NVQ0NFU1MQ260DEhoKFExBQkVMX09SREVSX0NBTkNFTEVE",
            "ENytAxIUCg5MSUNFTlNFX0FDVElWRRDg1AMSHAoWTElDRU5TRV9ET0VTX05P",
            "VF9FWElTVBDh1AMSGQoTTElDRU5TRV9ORUVEX1VQREFURRDi1AMSFQoPTElD",
            "RU5TRV9FWFBJUkVEEOPUAxIVCg9MSUNFTlNFX1JFVk9LRUQQ5NQDEhUKD0xJ",
            "Q0VOU0VfREVMRVRFRBDl1AMSHQoXTElDRU5TRV9WT0xVTUVfRVhDRUVERUQQ",
            "5tQDEiEKG1BBU1NXT1JEX1ZBTElEQVRJT05fU1VDQ0VTUxDI3AMSIAoaUEFT",
            "U1dPUkRfVkFMSURBVElPTl9GQUlMRUQQydwDEiUKH1BBU1NXT1JEUE9MSUNZ",
            "X0lOVkFMSURfQVJHVU1FTlQQytwDEiIKHEZFQVRVUkVGTEFHX0NPTkZJR19O",
            "T1RfRk9VTkQQsOQDEiIKHEZFQVRVUkVGTEFHX0lOVkFMSURfQVJHVU1FTlQQ",
            "seQDEhkKE0ZFQVRVUkVGTEFHX0JMT0NLRUQQsuQDEhsKFUZFQVRVUkVGTEFH",
            "X05PVF9GT1VORBCz5AMSGQoTTUFJTlRFTkFOQ0VfU1VDQ0VTUxCY7AMSGAoS",
            "TUFJTlRFTkFOQ0VfRkFJTEVEEJnsAxIdChdEQVRBU0VUX1ZFUlNJT05fUEVO",
            "RElORxCF9AMSIQobREFUQVNFVF9WRVJTSU9OX0lOX1BST0dSRVNTEIr0AxIb",
            "ChVEQVRBU0VUX1ZFUlNJT05fUkVBRFkQj/QDEh0KF0RBVEFTRVRfVkVSU0lP",
            "Tl9GQUlMVVJFEJT0AxImCiBEQVRBU0VUX1ZFUlNJT05fVU5FWFBFQ1RFRF9F",
            "UlJPUhCZ9AMSHgoYREFUQVNFVF9WRVJTSU9OX0NPTkZMSUNUEJ70AxIbChVE",
            "QVRBU0VUX0lOUFVUX1NVQ0NFU1MQ5PQDEh0KF0RBVEFTRVRfSU5QVVRfRFVQ",
            "TElDQVRFEOX0AxIkCh5EQVRBU0VUX1ZFUlNJT05fRVhQT1JUX1NVQ0NFU1MQ",
            "yPUDEiQKHkRBVEFTRVRfVkVSU0lPTl9FWFBPUlRfUEVORElORxDJ9QMSIwod",
            "REFUQVNFVF9WRVJTSU9OX0VYUE9SVF9GQUlMRUQQyvUDEigKIkRBVEFTRVRf",
            "VkVSU0lPTl9FWFBPUlRfSU5fUFJPR1JFU1MQy/UDEi0KJ0RBVEFTRVRfVkVS",
            "U0lPTl9FWFBPUlRfVU5FWFBFQ1RFRF9FUlJPUhDM9QMSEAoKSk9CX1FVRVVF",
            "RBCA9AMSEQoLSk9CX1JVTk5JTkcQgfQDEhMKDUpPQl9DT01QTEVURUQQgvQD",
            "EhAKCkpPQl9GQUlMRUQQg/QDEhMKDUpPQl9DQU5DRUxMRUQQhPQDEhoKFEpP",
            "Ql9VTkVYUEVDVEVEX0VSUk9SEIb0AxISCgxKT0JfQ09ORkxJQ1QQh/QDEhwK",
            "FkFVVEhfTUlTU0lOR19JRFBfQVNTT0MQ6PsDEhkKE0xJU1RfT0JKRUNUU19G",
            "QUlMRUQQ0IMEEhwKFkFSQ0hJVkVfRVhUUkFDVF9GQUlMRUQQuIsEEhgKElVQ",
            "TE9BRF9JTl9QUk9HUkVTUxCgkwQSEQoLVVBMT0FEX0RPTkUQoZMEEhMKDVVQ",
            "TE9BRF9GQUlMRUQQopMEEh0KF1VQTE9BRF9VTkVYUEVDVEVEX0VSUk9SEKOT",
            "BBIUCg5VUExPQURfRVhQSVJFRBCkkwQSFQoPVVBMT0FEX0NBTkNFTEVEEKWT",
            "BBIVCg9VUExPQURfQ09ORkxJQ1QQppMEEhoKFEJJTExJTkdfSU5WQUxJRF9J",
            "TkZPEIibBBIcChZCSUxMSU5HX01JU1NJTkdfVE9LRU5TEImbBBIhChtMT0df",
            "RU5UUklFU19JTlZBTElEX1JFUVVFU1QQ8KIEEhsKFUlOVEVSTkFMX1NFUlZF",
            "Ul9JU1NVRRDU/QUSHQoXSU5URVJOQUxfRkVUQ0hJTkdfSVNTVUUQ1f0FEh0K",
            "F0lOVEVSTkFMX0RBVEFCQVNFX0lTU1VFENb9BRIfChlJTlRFUk5BTF9DT05U",
            "RVhUX0NBTkNFTEVEENj9BRIhChtJTlRFUk5BTF9VTkVYUEVDVEVEX1RJTUVP",
            "VVQQ2f0FEhwKFklOVEVSTkFMX1VORVhQRUNURURfVjEQ2v0FEh8KGUlOVEVS",
            "TkFMX1VORVhQRUNURURfUEFOSUMQ2/0FEh8KGUlOVEVSTkFMX1VORVhQRUNU",
            "RURfU1BJUkUQ3P0FEiAKGklOVEVSTkFMX1JFRElTX1VOQVZBSUxBQkxFEN39",
            "BRIhChtJTlRFUk5BTF9SRVNPVVJDRV9FWEhBVVNURUQQ3v0FEiIKHElOVEVS",
            "TkFMX1JFRElTX1VOQ0FURUdPUklaRUQQ3/0FEiAKGklOVEVSTkFMX0FXU19V",
            "TkNBVEVHT1JJWkVEEOD9BRIiChxJTlRFUk5BTF9BWlVSRV9VTkNBVEVHT1JJ",
            "WkVEEOH9BRIlCh9JTlRFUk5BTF9WRUNUT1JEQl9VTkNBVEVHT1JJWkVEEOL9",
            "BRIjCh1JTlRFUk5BTF9PUkFDTEVfVU5DQVRFR09SSVpFRBDj/QUSIgocSU5U",
            "RVJOQUxfVlVMVFJfVU5DQVRFR09SSVpFRBDk/QUSGAoSQ09OTl9VTkNBVEVH",
            "T1JJWkVEELmFBhIZChNNT0RFTF9VTkNBVEVHT1JJWkVEELqFBhIZChNJTlBV",
            "VF9VTkNBVEVHT1JJWkVEELuFBhIeChhBTk5PVEFUSU9OX1VOQ0FURUdPUkla",
            "RUQQvIUGEhsKFUJJTExJTkdfVU5DQVRFR09SSVpFRBC9hQYSHAoWSU5URVJO",
            "QUxfVU5DQVRFR09SSVpFRBDBhQYSEQoLQkFEX1JFUVVFU1QQoMIFEhIKDFNF",
            "UlZFUl9FUlJPUhCEwwUaAhABIggIv8YBEL/GASIICOiBAhDogQIiCAjpgQIQ",
            "6YECIggI6oECEOqBAiIICMyCAhDMggIiCAjNggIQzYICIggIzoICEM6CAiII",
            "CM+CAhDPggIiCAjQggIQ0IICIggI0YICENGCAiIICNKCAhDSggIiCAiwgwIQ",
            "sIMCIggIsYMCELGDAiIICLODAhCzgwIiCAi6gwIQuoMCIggIu7gCELu4AiII",
            "CNK4AhDSuAIiCAjTuAIQ07gCIggI8MECEPDBAiIICPHBAhDxwQIiCAjywQIQ",
            "8sECIggI88ECEPPBAiIICPTBAhD0wQIiCAicxwEQnMcBIggInccBEJ3HASII",
            "CJ7HARCexwEiCAifxwEQn8cBIggIoccBEKHHASIICKLHARCixwFCZwocY29t",
            "LmNsYXJpZmFpLmdycGMuYXBpLnN0YXR1c1ABWj5naXRodWIuY29tL0NsYXJp",
            "ZmFpL2NsYXJpZmFpLWdvLWdycGMvcHJvdG8vY2xhcmlmYWkvYXBpL3N0YXR1",
            "c6ICBENBSVBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Clarifai.Api.Status.StatusCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StatusCode {
    /// <summary>
    /// to be revised and greatly expanded
    /// </summary>
    [pbr::OriginalName("ZERO")] Zero = 0,
    /// <summary>
    /// Generic
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 10000,
    [pbr::OriginalName("MIXED_STATUS")] MixedStatus = 10010,
    [pbr::OriginalName("FAILURE")] Failure = 10020,
    [pbr::OriginalName("TRY_AGAIN")] TryAgain = 10030,
    [pbr::OriginalName("NOT_IMPLEMENTED")] NotImplemented = 10040,
    /// <summary>
    /// Resource moved. Respond with Http status 307 and add new Location header to response
    /// </summary>
    [pbr::OriginalName("MOVED")] Moved = 10050,
    /// <summary>
    ///SUCCESS_WARNING_API_DEPRECATED = 10001;
    ///SUCCESS_WARNING_CLIENT_DEPRECATED = 10002;
    /// </summary>
    [pbr::OriginalName("TEAPOT")] Teapot = 10060,
    /// <summary>
    /// Clarifai Connection Codes: 11xxx
    /// </summary>
    [pbr::OriginalName("CONN_ACCOUNT_ISSUES")] ConnAccountIssues = 11000,
    /// <summary>
    /// invalid auth token used. Deprecated: we should return CONN_KEY_INVALID instead now in all cases.
    /// </summary>
    [pbr::OriginalName("CONN_TOKEN_INVALID")] ConnTokenInvalid = 11001,
    /// <summary>
    /// invalid auth credentials
    /// </summary>
    [pbr::OriginalName("CONN_CREDENTIALS_INVALID")] ConnCredentialsInvalid = 11002,
    /// <summary>
    /// throttle hourly limit exceeded
    /// </summary>
    [pbr::OriginalName("CONN_EXCEED_HOURLY_LIMIT")] ConnExceedHourlyLimit = 11003,
    /// <summary>
    /// throttle monthly limit exceeded
    /// </summary>
    [pbr::OriginalName("CONN_EXCEED_MONTHLY_LIMIT")] ConnExceedMonthlyLimit = 11004,
    /// <summary>
    /// throttler and billing stuff
    /// </summary>
    [pbr::OriginalName("CONN_THROTTLED")] ConnThrottled = 11005,
    /// <summary>
    /// throttler and billing stuff
    /// </summary>
    [pbr::OriginalName("CONN_EXCEEDS_LIMITS")] ConnExceedsLimits = 11006,
    /// <summary>
    /// api key has insufficient permissions
    /// </summary>
    [pbr::OriginalName("CONN_INSUFFICIENT_SCOPES")] ConnInsufficientScopes = 11007,
    /// <summary>
    /// api key is invalid
    /// </summary>
    [pbr::OriginalName("CONN_KEY_INVALID")] ConnKeyInvalid = 11008,
    /// <summary>
    /// api key not found
    /// </summary>
    [pbr::OriginalName("CONN_KEY_NOT_FOUND")] ConnKeyNotFound = 11009,
    /// <summary>
    /// multipart form parsing, broken json, etc
    /// </summary>
    [pbr::OriginalName("CONN_BAD_REQUEST_FORMAT")] ConnBadRequestFormat = 11100,
    /// <summary>
    /// when path is bad
    /// </summary>
    [pbr::OriginalName("CONN_DOES_NOT_EXIST")] ConnDoesNotExist = 11101,
    /// <summary>
    /// something wrong with a header
    /// </summary>
    [pbr::OriginalName("CONN_INVALID_REQUEST")] ConnInvalidRequest = 11102,
    /// <summary>
    /// when a request method is not allowed
    /// </summary>
    [pbr::OriginalName("CONN_METHOD_NOT_ALLOWED")] ConnMethodNotAllowed = 11103,
    /// <summary>
    /// lack GDPR consent
    /// </summary>
    [pbr::OriginalName("CONN_NO_GDPR_CONSENT")] ConnNoGdprConsent = 11104,
    /// <summary>
    /// when invalid range of a resource is requested
    /// </summary>
    [pbr::OriginalName("CONN_INVALID_RANGE")] ConnInvalidRange = 11105,
    /// <summary>
    /// authentication method is disabled
    /// </summary>
    [pbr::OriginalName("CONN_AUTH_METHOD_DISABLED")] ConnAuthMethodDisabled = 11200,
    /// <summary>
    /// Model/Custom Training related 20xxx
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINED")] ModelTrained = 21100,
    /// <summary>
    /// Custom model is currently training.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING")] ModelTraining = 21101,
    /// <summary>
    /// Custom model has not yet been trained.
    /// </summary>
    [pbr::OriginalName("MODEL_UNTRAINED")] ModelUntrained = 21102,
    /// <summary>
    /// Custom model is currently in queue for training, waiting on assets to process first.
    /// </summary>
    [pbr::OriginalName("MODEL_QUEUED_FOR_TRAINING")] ModelQueuedForTraining = 21103,
    [pbr::OriginalName("MODEL_UPLOADING")] ModelUploading = 21104,
    [pbr::OriginalName("MODEL_UPLOADING_FAILED")] ModelUploadingFailed = 21105,
    /// <summary>
    /// generic err msg for any type of model training err.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_FAILED")] ModelTrainingFailed = 21106,
    /// <summary>
    /// For new V3 DockerInternalType models which are built images
    /// </summary>
    [pbr::OriginalName("MODEL_BUILDING")] ModelBuilding = 21107,
    /// <summary>
    /// Failed to build image for model.
    /// </summary>
    [pbr::OriginalName("MODEL_BUILDING_FAILED")] ModelBuildingFailed = 21108,
    /// <summary>
    /// Failed to build image for model.
    /// </summary>
    [pbr::OriginalName("MODEL_BUILD_UNEXPECTED_ERROR")] ModelBuildUnexpectedError = 21109,
    /// <summary>
    /// Custom model training had no data.  FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_NO_DATA")] ModelTrainingNoData = 21110,
    /// <summary>
    /// Custom model training had no positive examples. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_NO_POSITIVES")] ModelTrainingNoPositives = 21111,
    /// <summary>
    /// Custom model training was ONE_VS_N but with a single class. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_ONE_VS_N_SINGLE_CLASS")] ModelTrainingOneVsNSingleClass = 21112,
    /// <summary>
    /// Training took longer than hard coded timeouts. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_TIMED_OUT")] ModelTrainingTimedOut = 21113,
    /// <summary>
    /// Training got error waiting on asset pipeline to finish. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_WAITING_ERROR")] ModelTrainingWaitingError = 21114,
    /// <summary>
    /// Training threw an unknown exception.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_UNKNOWN_ERROR")] ModelTrainingUnknownError = 21115,
    /// <summary>
    /// Training message was redelivered. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_MSG_REDELIVER")] ModelTrainingMsgRedeliver = 21116,
    /// <summary>
    /// Training got error due to insufficient labelled data. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INSUFFICIENT_DATA")] ModelTrainingInsufficientData = 21117,
    /// <summary>
    /// FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INVALID_PARAMS")] ModelTrainingInvalidParams = 21118,
    /// <summary>
    /// Training is stopped because too much data was dropped. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INVALID_DATA_TOLERANCE_EXCEEDED")] ModelTrainingInvalidDataToleranceExceeded = 21119,
    [pbr::OriginalName("MODEL_MODIFY_SUCCESS")] ModelModifySuccess = 21150,
    [pbr::OriginalName("MODEL_MODIFY_PENDING")] ModelModifyPending = 21151,
    [pbr::OriginalName("MODEL_MODIFY_FAILED")] ModelModifyFailed = 21152,
    [pbr::OriginalName("MODEL_DOES_NOT_EXIST")] ModelDoesNotExist = 21200,
    [pbr::OriginalName("MODEL_PERMISSION_DENIED")] ModelPermissionDenied = 21201,
    [pbr::OriginalName("MODEL_INVALID_ARGUMENT")] ModelInvalidArgument = 21202,
    [pbr::OriginalName("MODEL_INVALID_REQUEST")] ModelInvalidRequest = 21203,
    [pbr::OriginalName("MODEL_EVALUATED")] ModelEvaluated = 21300,
    [pbr::OriginalName("MODEL_EVALUATING")] ModelEvaluating = 21301,
    [pbr::OriginalName("MODEL_NOT_EVALUATED")] ModelNotEvaluated = 21302,
    [pbr::OriginalName("MODEL_QUEUED_FOR_EVALUATION")] ModelQueuedForEvaluation = 21303,
    /// <summary>
    /// Evaluation took longer than hard coded timeouts. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_TIMED_OUT")] ModelEvaluationTimedOut = 21310,
    /// <summary>
    /// Evaluation got error waiting on asset pipeline to finish.FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_WAITING_ERROR")] ModelEvaluationWaitingError = 21311,
    /// <summary>
    /// EVALUATION THREW AN UNKNOWN EXCEPTION.
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_UNKNOWN_ERROR")] ModelEvaluationUnknownError = 21312,
    [pbr::OriginalName("MODEL_PREDICTION_FAILED")] ModelPredictionFailed = 21313,
    /// <summary>
    /// Eval message was redelivered. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_MSG_REDELIVER")] ModelEvaluationMsgRedeliver = 21314,
    /// <summary>
    /// Don't have enough concepts labelled to perform evaluation. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_NEED_LABELS")] ModelEvaluationNeedLabels = 21315,
    /// <summary>
    /// Don't have enough inputs per concept to perform evaluation. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_NEED_INPUTS")] ModelEvaluationNeedInputs = 21316,
    /// <summary>
    /// Generic err code for eval failure.
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_FAILED")] ModelEvaluationFailed = 21317,
    /// <summary>
    /// Used when inference coordinator failed to deploy spire and throws an error
    /// </summary>
    [pbr::OriginalName("MODEL_DEPLOYMENT_FAILED")] ModelDeploymentFailed = 21350,
    /// <summary>
    /// Used when calling the inference coordinator to deploy a spire
    /// </summary>
    [pbr::OriginalName("MODEL_DEPLOYING")] ModelDeploying = 21351,
    /// <summary>
    /// Used when training is completed
    /// </summary>
    [pbr::OriginalName("MODEL_QUEUED_FOR_DEPLOYMENT")] ModelQueuedForDeployment = 21352,
    /// <summary>
    /// Used when model spire deployment is manually taken down or due to inactivity
    /// </summary>
    [pbr::OriginalName("MODEL_NOT_DEPLOYED")] ModelNotDeployed = 21353,
    [pbr::OriginalName("MODEL_BUSY_PLEASE_RETRY")] ModelBusyPleaseRetry = 21354,
    /// <summary>
    /// Used when the model pod is running, but not yet ready to serve requests.
    /// </summary>
    [pbr::OriginalName("MODEL_LOADING")] ModelLoading = 21355,
    /// <summary>
    /// Used when a model reference field is not set properly
    /// </summary>
    [pbr::OriginalName("MODEL_REFERENCE_INVALID_ARGUMENT")] ModelReferenceInvalidArgument = 21400,
    /// <summary>
    /// Used when a model example input field is not set properly
    /// </summary>
    [pbr::OriginalName("MODEL_EXAMPLE_INPUT_INVALID_ARGUMENT")] ModelExampleInputInvalidArgument = 21420,
    /// <summary>
    /// Model Export status codes
    /// </summary>
    [pbr::OriginalName("MODEL_EXPORTED")] ModelExported = 21500,
    [pbr::OriginalName("MODEL_EXPORTING")] ModelExporting = 21501,
    [pbr::OriginalName("MODEL_EXPORTING_FAILED")] ModelExportingFailed = 21502,
    [pbr::OriginalName("MODEL_EXPORT_PENDING")] ModelExportPending = 21503,
    /// <summary>
    /// specified model input not in workflow
    /// </summary>
    [pbr::OriginalName("WORKFLOW_NO_MATCHING_INPUT")] WorkflowNoMatchingInput = 22001,
    /// <summary>
    /// specified model must be trained
    /// </summary>
    [pbr::OriginalName("WORKFLOW_REQUIRE_TRAINED_MODEL")] WorkflowRequireTrainedModel = 22002,
    [pbr::OriginalName("WORKFLOW_DUPLICATE")] WorkflowDuplicate = 22100,
    [pbr::OriginalName("WORKFLOW_UNSUPPORTED_FORMAT")] WorkflowUnsupportedFormat = 22101,
    [pbr::OriginalName("WORKFLOW_DOES_NOT_EXIST")] WorkflowDoesNotExist = 22102,
    [pbr::OriginalName("WORKFLOW_PERMISSION_DENIED")] WorkflowPermissionDenied = 22103,
    /// <summary>
    /// error in the request somewhere
    /// </summary>
    [pbr::OriginalName("WORKFLOW_INVALID_ARGUMENT")] WorkflowInvalidArgument = 22104,
    [pbr::OriginalName("WORKFLOW_INVALID_RECIPE")] WorkflowInvalidRecipe = 22105,
    [pbr::OriginalName("WORKFLOW_INVALID_TEMPLATE")] WorkflowInvalidTemplate = 22106,
    [pbr::OriginalName("WORKFLOW_INVALID_GRAPH")] WorkflowInvalidGraph = 22107,
    [pbr::OriginalName("WORKFLOW_INTERNAL_FAILURE")] WorkflowInternalFailure = 22108,
    /// <summary>
    /// error in the request somewhere
    /// </summary>
    [pbr::OriginalName("WORKFLOW_INVALID_REQUEST")] WorkflowInvalidRequest = 22999,
    [pbr::OriginalName("WORKFLOW_MODIFY_SUCCESS")] WorkflowModifySuccess = 22150,
    [pbr::OriginalName("WORKFLOW_MODIFY_PENDING")] WorkflowModifyPending = 22151,
    [pbr::OriginalName("WORKFLOW_MODIFY_FAILED")] WorkflowModifyFailed = 22152,
    [pbr::OriginalName("WORKFLOW_REINDEX_FAILED")] WorkflowReindexFailed = 22153,
    /// <summary>
    /// Concept related 23xxx
    /// </summary>
    [pbr::OriginalName("CONCEPT_MODIFY_SUCCESS")] ConceptModifySuccess = 23150,
    [pbr::OriginalName("CONCEPT_MODIFY_PENDING")] ConceptModifyPending = 23151,
    [pbr::OriginalName("CONCEPT_MODIFY_FAILED")] ConceptModifyFailed = 23152,
    /// <summary>
    /// Annotation related 24xxx
    /// </summary>
    [pbr::OriginalName("ANNOTATION_SUCCESS")] AnnotationSuccess = 24150,
    [pbr::OriginalName("ANNOTATION_PENDING")] AnnotationPending = 24151,
    [pbr::OriginalName("ANNOTATION_FAILED")] AnnotationFailed = 24152,
    [pbr::OriginalName("ANNOTATION_UNKNOWN_STATUS")] AnnotationUnknownStatus = 24154,
    [pbr::OriginalName("ANNOTATION_INVALID_ARGUMENT")] AnnotationInvalidArgument = 24155,
    [pbr::OriginalName("ANNOTATION_PERMISSION_DENIED")] AnnotationPermissionDenied = 24156,
    /// <summary>
    /// Annotation is awaiting review from task REVIEWERS.
    /// </summary>
    [pbr::OriginalName("ANNOTATION_AWAITING_REVIEW")] AnnotationAwaitingReview = 24157,
    /// <summary>
    /// Annotation is awaiting consensus review from task LABELERS.
    /// </summary>
    [pbr::OriginalName("ANNOTATION_AWAITING_CONSENSUS_REVIEW")] AnnotationAwaitingConsensusReview = 24159,
    [pbr::OriginalName("ANNOTATION_REVIEW_DENIED")] AnnotationReviewDenied = 24158,
    [pbr::OriginalName("ANNOTATION_MODIFY_SUCCESS")] AnnotationModifySuccess = 24250,
    [pbr::OriginalName("ANNOTATION_MODIFY_PENDING")] AnnotationModifyPending = 24251,
    [pbr::OriginalName("ANNOTATION_MODIFY_FAILED")] AnnotationModifyFailed = 24252,
    /// <summary>
    /// Metadata related 249xx
    /// </summary>
    [pbr::OriginalName("METADATA_INVALID_PATCH_ARGUMENTS")] MetadataInvalidPatchArguments = 24900,
    [pbr::OriginalName("METADATA_PARSING_ISSUE")] MetadataParsingIssue = 24901,
    [pbr::OriginalName("METADATA_MANIPULATION_ISSUE")] MetadataManipulationIssue = 24902,
    /// <summary>
    /// Training service related 25xxx
    /// </summary>
    [pbr::OriginalName("TRAINER_JOB_STATE_NONE")] TrainerJobStateNone = 25000,
    [pbr::OriginalName("TRAINER_JOB_STATE_QUEUED")] TrainerJobStateQueued = 25001,
    [pbr::OriginalName("TRAINER_JOB_STATE_RUNNING")] TrainerJobStateRunning = 25002,
    [pbr::OriginalName("TRAINER_JOB_STATE_COMPLETE")] TrainerJobStateComplete = 25003,
    [pbr::OriginalName("TRAINER_JOB_STATE_ERROR")] TrainerJobStateError = 25004,
    /// <summary>
    /// Data Dump related 251xx
    /// </summary>
    [pbr::OriginalName("DATA_DUMP_SUCCESS")] DataDumpSuccess = 25150,
    [pbr::OriginalName("DATA_DUMP_PENDING")] DataDumpPending = 25151,
    [pbr::OriginalName("DATA_DUMP_FAILED")] DataDumpFailed = 25152,
    [pbr::OriginalName("DATA_DUMP_IN_PROGRESS")] DataDumpInProgress = 25153,
    /// <summary>
    /// DEPRECATED: Not used anymore. Now for an empty data dump, DATA_DUMP_SUCCESS is returned. To detect an empty data dump, check if the inptus count is 0.
    /// </summary>
    [pbr::OriginalName("DATA_DUMP_NO_DATA")] DataDumpNoData = 25154,
    [pbr::OriginalName("DATA_DUMP_UNEXPECTED_ERROR")] DataDumpUnexpectedError = 25155,
    [pbr::OriginalName("DATA_DUMP_EXPORT_SUCCESS")] DataDumpExportSuccess = 25170,
    [pbr::OriginalName("DATA_DUMP_EXPORT_PENDING")] DataDumpExportPending = 25171,
    [pbr::OriginalName("DATA_DUMP_EXPORT_FAILED")] DataDumpExportFailed = 25172,
    [pbr::OriginalName("DATA_DUMP_EXPORT_IN_PROGRESS")] DataDumpExportInProgress = 25173,
    [pbr::OriginalName("DATA_DUMP_EXPORT_UNEXPECTED_ERROR")] DataDumpExportUnexpectedError = 25174,
    /// <summary>
    /// Duplicate related 252xx
    /// </summary>
    [pbr::OriginalName("APP_DUPLICATION_SUCCESS")] AppDuplicationSuccess = 25200,
    [pbr::OriginalName("APP_DUPLICATION_FAILED")] AppDuplicationFailed = 25201,
    [pbr::OriginalName("APP_DUPLICATION_PENDING")] AppDuplicationPending = 25202,
    [pbr::OriginalName("APP_DUPLICATION_IN_PROGRESS")] AppDuplicationInProgress = 25203,
    [pbr::OriginalName("APP_DUPLICATION_INVALID_REQUEST")] AppDuplicationInvalidRequest = 25204,
    /// <summary>
    /// Module related codes 253xx
    /// </summary>
    [pbr::OriginalName("MODULE_DOES_NOT_EXIST")] ModuleDoesNotExist = 25300,
    [pbr::OriginalName("MODULE_PERMISSION_DENIED")] ModulePermissionDenied = 25301,
    [pbr::OriginalName("MODULE_INVALID_ARGUMENT")] ModuleInvalidArgument = 25302,
    [pbr::OriginalName("MODULE_INVALID_REQUEST")] ModuleInvalidRequest = 25303,
    /// <summary>
    /// Bulk Operation related codes 254xx
    /// </summary>
    [pbr::OriginalName("BULK_OPERATION_SUCCESS")] BulkOperationSuccess = 25400,
    [pbr::OriginalName("BULK_OPERATION_FAILED")] BulkOperationFailed = 25401,
    [pbr::OriginalName("BULK_OPERATION_PENDING")] BulkOperationPending = 25402,
    [pbr::OriginalName("BULK_OPERATION_IN_PROGRESS")] BulkOperationInProgress = 25403,
    [pbr::OriginalName("BULK_OPERATION_INVALID_REQUEST")] BulkOperationInvalidRequest = 25404,
    [pbr::OriginalName("BULK_OPERATION_CANCELLED")] BulkOperationCancelled = 25405,
    [pbr::OriginalName("BULK_OPERATION_UNEXPECTED_ERROR")] BulkOperationUnexpectedError = 25406,
    /// <summary>
    /// Runner related codes 256xx
    /// </summary>
    [pbr::OriginalName("RUNNER_DOES_NOT_EXIST")] RunnerDoesNotExist = 25600,
    [pbr::OriginalName("RUNNER_PERMISSION_DENIED")] RunnerPermissionDenied = 25601,
    [pbr::OriginalName("RUNNER_INVALID_ARGUMENT")] RunnerInvalidArgument = 25602,
    [pbr::OriginalName("RUNNER_INVALID_REQUEST")] RunnerInvalidRequest = 25603,
    [pbr::OriginalName("RUNNER_NEEDS_RETRY")] RunnerNeedsRetry = 25604,
    [pbr::OriginalName("RUNNER_STREAM_START")] RunnerStreamStart = 25605,
    [pbr::OriginalName("RUNNER_STREAM_END")] RunnerStreamEnd = 25606,
    [pbr::OriginalName("RUNNER_ITEM_CANCELLED")] RunnerItemCancelled = 25607,
    [pbr::OriginalName("RUNNER_PROCESSING_FAILED")] RunnerProcessingFailed = 25608,
    /// <summary>
    /// Nodepool related codes 257xx
    /// </summary>
    [pbr::OriginalName("NODEPOOL_DOES_NOT_EXIST")] NodepoolDoesNotExist = 25700,
    [pbr::OriginalName("NODEPOOL_INVALID_ARGUMENT")] NodepoolInvalidArgument = 25701,
    [pbr::OriginalName("NODEPOOL_INVALID_REQUEST")] NodepoolInvalidRequest = 25702,
    /// <summary>
    /// ComputeCluster related codes 258xx
    /// </summary>
    [pbr::OriginalName("COMPUTE_CLUSTER_DOES_NOT_EXIST")] ComputeClusterDoesNotExist = 25800,
    [pbr::OriginalName("COMPUTE_CLUSTER_INVALID_ARGUMENT")] ComputeClusterInvalidArgument = 25801,
    [pbr::OriginalName("COMPUTE_CLUSTER_INVALID_REQUEST")] ComputeClusterInvalidRequest = 25802,
    /// <summary>
    /// Deployment related codes 259xx
    /// </summary>
    [pbr::OriginalName("DEPLOYMENT_DOES_NOT_EXIST")] DeploymentDoesNotExist = 25900,
    [pbr::OriginalName("DEPLOYMENT_INVALID_ARGUMENT")] DeploymentInvalidArgument = 25901,
    [pbr::OriginalName("DEPLOYMENT_INVALID_REQUEST")] DeploymentInvalidRequest = 25902,
    /// <summary>
    /// InstanceType related codes 260xx
    /// </summary>
    [pbr::OriginalName("INSTANCE_TYPE_DOES_NOT_EXIST")] InstanceTypeDoesNotExist = 26000,
    [pbr::OriginalName("INSTANCE_TYPE_INVALID_ARGUMENT")] InstanceTypeInvalidArgument = 26001,
    [pbr::OriginalName("INSTANCE_TYPE_INVALID_REQUEST")] InstanceTypeInvalidRequest = 26002,
    /// <summary>
    /// Compute plane related codes 261xx
    /// </summary>
    [pbr::OriginalName("COMPUTE_PLANE_METRICS_INVALID_REQUEST")] ComputePlaneMetricsInvalidRequest = 26100,
    /// <summary>
    /// PipelineStep related codes 262xx
    /// </summary>
    [pbr::OriginalName("PIPELINE_STEP_DOES_NOT_EXIST")] PipelineStepDoesNotExist = 26200,
    [pbr::OriginalName("PIPELINE_STEP_INVALID_ARGUMENT")] PipelineStepInvalidArgument = 26201,
    [pbr::OriginalName("PIPELINE_STEP_INVALID_REQUEST")] PipelineStepInvalidRequest = 26202,
    [pbr::OriginalName("PIPELINE_STEP_UPLOADING")] PipelineStepUploading = 26203,
    [pbr::OriginalName("PIPELINE_STEP_UPLOADING_FAILED")] PipelineStepUploadingFailed = 26204,
    [pbr::OriginalName("PIPELINE_STEP_BUILDING")] PipelineStepBuilding = 26205,
    [pbr::OriginalName("PIPELINE_STEP_BUILDING_FAILED")] PipelineStepBuildingFailed = 26206,
    [pbr::OriginalName("PIPELINE_STEP_BUILD_UNEXPECTED_ERROR")] PipelineStepBuildUnexpectedError = 26207,
    [pbr::OriginalName("PIPELINE_STEP_READY")] PipelineStepReady = 26208,
    /// <summary>
    /// Input:Image related 30xxx
    /// </summary>
    [pbr::OriginalName("INPUT_SUCCESS")] InputSuccess = 30000,
    /// <summary>
    /// when things are async, this is the default status.
    /// </summary>
    [pbr::OriginalName("INPUT_PENDING")] InputPending = 30001,
    /// <summary>
    /// any type of error downloading and processing
    /// </summary>
    [pbr::OriginalName("INPUT_FAILED")] InputFailed = 30002,
    [pbr::OriginalName("INPUT_IN_PROGRESS")] InputInProgress = 30003,
    /// <summary>
    /// use INPUT_SUCCESS, INPUT_PENDING, INPUT_FAILED, INPUT_IN_PROGRESS instead
    /// DOWNLOAD is no longer correct, but keep old statuses for backward compatibility
    /// </summary>
    [pbr::OriginalName("INPUT_DOWNLOAD_SUCCESS", PreferredAlias = false)] InputDownloadSuccess = 30000,
    [pbr::OriginalName("INPUT_DOWNLOAD_PENDING", PreferredAlias = false)] InputDownloadPending = 30001,
    [pbr::OriginalName("INPUT_DOWNLOAD_FAILED", PreferredAlias = false)] InputDownloadFailed = 30002,
    [pbr::OriginalName("INPUT_DOWNLOAD_IN_PROGRESS", PreferredAlias = false)] InputDownloadInProgress = 30003,
    [pbr::OriginalName("INPUT_STATUS_UPDATE_FAILED")] InputStatusUpdateFailed = 30004,
    [pbr::OriginalName("INPUT_DELETE_FAILED")] InputDeleteFailed = 30005,
    [pbr::OriginalName("INPUT_DUPLICATE")] InputDuplicate = 30100,
    [pbr::OriginalName("INPUT_UNSUPPORTED_FORMAT")] InputUnsupportedFormat = 30101,
    [pbr::OriginalName("INPUT_DOES_NOT_EXIST")] InputDoesNotExist = 30102,
    [pbr::OriginalName("INPUT_PERMISSION_DENIED")] InputPermissionDenied = 30103,
    [pbr::OriginalName("INPUT_INVALID_ARGUMENT")] InputInvalidArgument = 30104,
    [pbr::OriginalName("INPUT_OVER_LIMIT")] InputOverLimit = 30105,
    [pbr::OriginalName("INPUT_INVALID_URL")] InputInvalidUrl = 30106,
    [pbr::OriginalName("INPUT_MODIFY_SUCCESS")] InputModifySuccess = 30200,
    [pbr::OriginalName("INPUT_MODIFY_PENDING")] InputModifyPending = 30201,
    [pbr::OriginalName("INPUT_MODIFY_FAILED")] InputModifyFailed = 30203,
    [pbr::OriginalName("INPUT_STORAGE_HOST_FAILED")] InputStorageHostFailed = 30210,
    [pbr::OriginalName("ALL_INPUT_INVALID_BYTES")] AllInputInvalidBytes = 30300,
    [pbr::OriginalName("INPUT_CLUSTER_SUCCESS")] InputClusterSuccess = 30400,
    [pbr::OriginalName("INPUT_CLUSTER_PENDING")] InputClusterPending = 30401,
    [pbr::OriginalName("INPUT_CLUSTER_FAILED")] InputClusterFailed = 30402,
    [pbr::OriginalName("INPUT_CLUSTER_IN_PROGRESS")] InputClusterInProgress = 30403,
    [pbr::OriginalName("INPUT_REINDEX_SUCCESS")] InputReindexSuccess = 30500,
    [pbr::OriginalName("INPUT_REINDEX_PENDING")] InputReindexPending = 30501,
    [pbr::OriginalName("INPUT_REINDEX_FAILED")] InputReindexFailed = 30502,
    [pbr::OriginalName("INPUT_REINDEX_IN_PROGRESS")] InputReindexInProgress = 30503,
    /// <summary>
    /// Input:Video related 31xxx -- Deprecated
    /// </summary>
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_SUCCESS")] InputVideoDownloadSuccess = 31000,
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_PENDING")] InputVideoDownloadPending = 31001,
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_FAILED")] InputVideoDownloadFailed = 31002,
    [pbr::OriginalName("INPUT_VIDEO_DUPLICATE")] InputVideoDuplicate = 31100,
    [pbr::OriginalName("INPUT_VIDEO_UNSUPPORTED_FORMAT")] InputVideoUnsupportedFormat = 31101,
    [pbr::OriginalName("INPUT_VIDEO_DOES_NOT_EXIST")] InputVideoDoesNotExist = 31102,
    [pbr::OriginalName("INPUT_VIDEO_PERMISSION_DENIED")] InputVideoPermissionDenied = 31103,
    [pbr::OriginalName("INPUT_VIDEO_INVALID_ARGUMENT")] InputVideoInvalidArgument = 31104,
    [pbr::OriginalName("INPUT_VIDEO_OVER_LIMIT")] InputVideoOverLimit = 31105,
    [pbr::OriginalName("INPUT_VIDEO_INVALID_URL")] InputVideoInvalidUrl = 31106,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_SUCCESS")] InputVideoModifySuccess = 31200,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_PENDING")] InputVideoModifyPending = 31201,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_FAILED")] InputVideoModifyFailed = 31203,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_HOST_FAILED")] InputVideoStorageHostFailed = 31210,
    [pbr::OriginalName("ALL_INPUT_VIDEOS_INVALID_BYTES")] AllInputVideosInvalidBytes = 31300,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_SUCCESS")] InputVideoProcessingSuccess = 31400,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_PENDING")] InputVideoProcessingPending = 31410,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_FAILED")] InputVideoProcessingFailed = 31420,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_INCONSISTENCY")] InputVideoStorageInconsistency = 31430,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_FAILURE")] InputVideoStorageFailure = 31440,
    [pbr::OriginalName("INPUT_VIDEO_URL_GENERATION_FAILURE")] InputVideoUrlGenerationFailure = 31450,
    [pbr::OriginalName("INPUT_CONNECTION_FAILED")] InputConnectionFailed = 39996,
    [pbr::OriginalName("REQUEST_DISABLED_FOR_MAINTENANCE")] RequestDisabledForMaintenance = 39997,
    /// <summary>
    /// deprecate this one. Use REQUEST_DISABLED_FOR_MAINTENANCE
    /// </summary>
    [pbr::OriginalName("INPUT_WRITES_DISABLED_FOR_MAINTENANCE")] InputWritesDisabledForMaintenance = 39998,
    [pbr::OriginalName("INPUT_INVALID_REQUEST")] InputInvalidRequest = 39999,
    /// <summary>
    /// API formatting issues 4000x
    /// </summary>
    [pbr::OriginalName("PREDICT_INVALID_REQUEST")] PredictInvalidRequest = 40001,
    [pbr::OriginalName("SEARCH_INVALID_REQUEST")] SearchInvalidRequest = 40002,
    [pbr::OriginalName("CONCEPTS_INVALID_REQUEST")] ConceptsInvalidRequest = 40003,
    [pbr::OriginalName("STATS_INVALID_REQUEST")] StatsInvalidRequest = 40004,
    /// <summary>
    /// Other related 400xx
    /// </summary>
    [pbr::OriginalName("DATABASE_DUPLICATE_KEY")] DatabaseDuplicateKey = 40010,
    [pbr::OriginalName("DATABASE_STATEMENT_TIMEOUT")] DatabaseStatementTimeout = 40011,
    [pbr::OriginalName("DATABASE_INVALID_ROWS_AFFECTED")] DatabaseInvalidRowsAffected = 40012,
    [pbr::OriginalName("DATABASE_DEADLOCK_DETECTED")] DatabaseDeadlockDetected = 40013,
    [pbr::OriginalName("DATABASE_FAIL_TASK")] DatabaseFailTask = 40014,
    [pbr::OriginalName("DATABASE_FAIL_TO_GET_CONNECTIONS")] DatabaseFailToGetConnections = 40015,
    [pbr::OriginalName("DATABASE_TOO_MANY_CLIENTS")] DatabaseTooManyClients = 40016,
    [pbr::OriginalName("DATABASE_CONSTRAINT_VIOLATED")] DatabaseConstraintViolated = 40017,
    [pbr::OriginalName("DATABASE_CANCELED")] DatabaseCanceled = 40021,
    [pbr::OriginalName("ASYNC_WORKER_MULTI_ERRORS")] AsyncWorkerMultiErrors = 40020,
    [pbr::OriginalName("RPC_REQUEST_QUEUE_FULL")] RpcRequestQueueFull = 40030,
    [pbr::OriginalName("RPC_SERVER_UNAVAILABLE")] RpcServerUnavailable = 40031,
    [pbr::OriginalName("RPC_REQUEST_TIMEOUT")] RpcRequestTimeout = 40032,
    [pbr::OriginalName("RPC_MAX_MESSAGE_SIZE_EXCEEDED")] RpcMaxMessageSizeExceeded = 40033,
    [pbr::OriginalName("RPC_CANCELED")] RpcCanceled = 40035,
    [pbr::OriginalName("RPC_UNKNOWN_METHOD")] RpcUnknownMethod = 40036,
    [pbr::OriginalName("REQUEST_CANCELED_BY_USER")] RequestCanceledByUser = 40037,
    [pbr::OriginalName("CLUSTER_INTERNAL_FAILURE")] ClusterInternalFailure = 43040,
    /// <summary>
    /// could not connect to external services
    /// </summary>
    [pbr::OriginalName("EXTERNAL_CONNECTION_ERROR")] ExternalConnectionError = 40034,
    [pbr::OriginalName("QUERY_INVALID_SYNTAX")] QueryInvalidSyntax = 40050,
    /// <summary>
    /// Queue related errors 41xxx
    /// </summary>
    [pbr::OriginalName("QUEUE_CONN_ERROR")] QueueConnError = 41000,
    [pbr::OriginalName("QUEUE_CLOSE_REQUEST_TIMEOUT")] QueueCloseRequestTimeout = 41002,
    [pbr::OriginalName("QUEUE_CONN_CLOSED")] QueueConnClosed = 41003,
    [pbr::OriginalName("QUEUE_PUBLISH_ACK_TIMEOUT")] QueuePublishAckTimeout = 41004,
    [pbr::OriginalName("QUEUE_PUBLISH_ERROR")] QueuePublishError = 41005,
    [pbr::OriginalName("QUEUE_SUBSCRIPTION_TIMEOUT")] QueueSubscriptionTimeout = 41006,
    [pbr::OriginalName("QUEUE_SUBSCRIPTION_ERROR")] QueueSubscriptionError = 41007,
    [pbr::OriginalName("QUEUE_MARSHALLING_FAILED")] QueueMarshallingFailed = 41008,
    [pbr::OriginalName("QUEUE_UNMARSHALLING_FAILED")] QueueUnmarshallingFailed = 41009,
    [pbr::OriginalName("QUEUE_MAX_MSG_REDELIVERY_EXCEEDED")] QueueMaxMsgRedeliveryExceeded = 41010,
    [pbr::OriginalName("QUEUE_ACK_FAILURE")] QueueAckFailure = 41011,
    /// <summary>
    /// SQS related errors 411xx
    /// </summary>
    [pbr::OriginalName("SQS_OVERLIMIT")] SqsOverlimit = 41100,
    [pbr::OriginalName("SQS_INVALID_RECEIPT_HANDLE")] SqsInvalidReceiptHandle = 41101,
    [pbr::OriginalName("SQS_UNKNOWN")] SqsUnknown = 41102,
    /// <summary>
    ///Search related errors 43xxxx
    /// </summary>
    [pbr::OriginalName("SEARCH_INTERNAL_FAILURE")] SearchInternalFailure = 43001,
    [pbr::OriginalName("SEARCH_PROJECTION_FAILURE")] SearchProjectionFailure = 43002,
    [pbr::OriginalName("SEARCH_PREDICTION_FAILURE")] SearchPredictionFailure = 43003,
    [pbr::OriginalName("SEARCH_BY_NOT_FULLY_INDEXED_INPUT")] SearchByNotFullyIndexedInput = 43004,
    [pbr::OriginalName("SAVED_SEARCH_MODIFY_FAILED")] SavedSearchModifyFailed = 43005,
    [pbr::OriginalName("SEARCH_COUNTS_UNAVAILABLE")] SearchCountsUnavailable = 43006,
    /// <summary>
    /// Workflow evaluation err code
    /// </summary>
    [pbr::OriginalName("EVALUATION_QUEUED")] EvaluationQueued = 43100,
    [pbr::OriginalName("EVALUATION_IN_PROGRESS")] EvaluationInProgress = 43101,
    [pbr::OriginalName("EVALUATION_SUCCESS")] EvaluationSuccess = 43102,
    [pbr::OriginalName("EVALUATION_FAILED_TO_RETRIEVE_DATA")] EvaluationFailedToRetrieveData = 43103,
    [pbr::OriginalName("EVALUATION_INVALID_ARGUMENT")] EvaluationInvalidArgument = 43104,
    [pbr::OriginalName("EVALUATION_FAILED")] EvaluationFailed = 43105,
    [pbr::OriginalName("EVALUATION_PENDING")] EvaluationPending = 43106,
    [pbr::OriginalName("EVALUATION_TIMED_OUT")] EvaluationTimedOut = 43107,
    [pbr::OriginalName("EVALUATION_UNEXPECTED_ERROR")] EvaluationUnexpectedError = 43108,
    [pbr::OriginalName("EVALUATION_MIXED")] EvaluationMixed = 43109,
    /// <summary>
    /// Stripe 44xxx
    /// </summary>
    [pbr::OriginalName("STRIPE_EVENT_ERROR")] StripeEventError = 44001,
    /// <summary>
    /// Redis/Cache 45xxx
    /// </summary>
    [pbr::OriginalName("CACHE_MISS")] CacheMiss = 45001,
    [pbr::OriginalName("REDIS_SCRIPT_EXITED_WITH_FAILURE")] RedisScriptExitedWithFailure = 45002,
    [pbr::OriginalName("REDIS_STREAM_ERR")] RedisStreamErr = 45003,
    [pbr::OriginalName("REDIS_NO_CONSUMERS")] RedisNoConsumers = 45004,
    [pbr::OriginalName("REDIS_STREAM_BACKOFF")] RedisStreamBackoff = 45005,
    /// <summary>
    /// Sift Science 46xxx
    /// </summary>
    [pbr::OriginalName("SIGNUP_EVENT_ERROR")] SignupEventError = 46001,
    [pbr::OriginalName("SIGNUP_FLAGGED")] SignupFlagged = 46002,
    [pbr::OriginalName("FILETYPE_UNSUPPORTED")] FiletypeUnsupported = 46003,
    /// <summary>
    /// Application counts related errors 470xx
    /// </summary>
    [pbr::OriginalName("APP_COUNT_INVALID_MESSAGE")] AppCountInvalidMessage = 47001,
    [pbr::OriginalName("APP_COUNT_UPDATE_INCREMENT_FAILED")] AppCountUpdateIncrementFailed = 47002,
    [pbr::OriginalName("APP_COUNT_REBUILD_FAILED")] AppCountRebuildFailed = 47003,
    [pbr::OriginalName("APP_COUNT_INTERNAL_FAILURE")] AppCountInternalFailure = 47004,
    /// <summary>
    /// Media processor related errors 471xx -- DEPRECATED
    /// </summary>
    [pbr::OriginalName("MP_DOWNLOAD_ERROR")] MpDownloadError = 47101,
    [pbr::OriginalName("MP_RESOLVE_DNS_ERROR")] MpResolveDnsError = 47102,
    [pbr::OriginalName("MP_DOWNLOAD_MAX_SIZE_EXCEEDED_ERROR")] MpDownloadMaxSizeExceededError = 47103,
    [pbr::OriginalName("MP_IMAGE_DECODE_ERROR")] MpImageDecodeError = 47104,
    [pbr::OriginalName("MP_INVALID_ARGUMENT")] MpInvalidArgument = 47105,
    [pbr::OriginalName("MP_IMAGE_PROCESSING_ERROR")] MpImageProcessingError = 47106,
    /// <summary>
    /// DataTier related error 472xx
    /// </summary>
    [pbr::OriginalName("DATATIER_CONN_ERROR")] DatatierConnError = 47201,
    /// <summary>
    /// User legal consent stauts related 50xxx
    /// </summary>
    [pbr::OriginalName("USER_CONSENT_FACE")] UserConsentFace = 50001,
    /// <summary>
    /// Workers 51xxx
    /// </summary>
    [pbr::OriginalName("WORKER_MISSING")] WorkerMissing = 51000,
    [pbr::OriginalName("WORKER_ACTIVE")] WorkerActive = 51001,
    [pbr::OriginalName("WORKER_INACTIVE")] WorkerInactive = 51002,
    /// <summary>
    /// Collectors 52xxx
    /// </summary>
    [pbr::OriginalName("COLLECTOR_MISSING")] CollectorMissing = 52000,
    [pbr::OriginalName("COLLECTOR_ACTIVE")] CollectorActive = 52001,
    [pbr::OriginalName("COLLECTOR_INACTIVE")] CollectorInactive = 52002,
    [pbr::OriginalName("COLLECTOR_POST_INPUT_FAILED")] CollectorPostInputFailed = 52003,
    /// <summary>
    /// SSO 53xxx
    /// </summary>
    [pbr::OriginalName("SSO_IDENTITY_PROVIDER_DOES_NOT_EXIST")] SsoIdentityProviderDoesNotExist = 53001,
    /// <summary>
    /// Tasks 54xxx
    /// The task was created.
    /// </summary>
    [pbr::OriginalName("TASK_IN_PROGRESS")] TaskInProgress = 54001,
    /// <summary>
    /// The task is completed.
    /// </summary>
    [pbr::OriginalName("TASK_DONE")] TaskDone = 54002,
    /// <summary>
    /// The task is marked as abandoned.
    /// </summary>
    [pbr::OriginalName("TASK_WONT_DO")] TaskWontDo = 54003,
    /// <summary>
    /// An error occurred during add-task-annotations or add-auto-annotations pipeline.
    /// </summary>
    [pbr::OriginalName("TASK_FAILED")] TaskFailed = 54005,
    /// <summary>
    /// When an Auto Annotation task job has finished processing its last batch and is waiting for more dataset assets.
    /// </summary>
    [pbr::OriginalName("TASK_IDLE")] TaskIdle = 54006,
    /// <summary>
    /// The task operation is in conflict with the current state of the server.
    /// </summary>
    [pbr::OriginalName("TASK_CONFLICT")] TaskConflict = 54100,
    /// <summary>
    /// Certain task-related scenarios are not implemented.
    /// </summary>
    [pbr::OriginalName("TASK_NOT_IMPLEMENTED")] TaskNotImplemented = 54101,
    /// <summary>
    /// Task was not found.
    /// </summary>
    [pbr::OriginalName("TASK_MISSING")] TaskMissing = 54102,
    /// <summary>
    /// Not allowed to perform a task-related action.
    /// </summary>
    [pbr::OriginalName("TASK_PERMISSION_DENIED")] TaskPermissionDenied = 54103,
    /// <summary>
    /// Task Assignments 542xx
    /// </summary>
    [pbr::OriginalName("TASK_ASSIGNMENT_SUCCESS")] TaskAssignmentSuccess = 54200,
    [pbr::OriginalName("TASK_ASSIGNMENT_PENDING")] TaskAssignmentPending = 54201,
    [pbr::OriginalName("TASK_ASSIGNMENT_AWAITING_REVIEW")] TaskAssignmentAwaitingReview = 54202,
    [pbr::OriginalName("TASK_ASSIGNMENT_AWAITING_CONSENSUS_REVIEW")] TaskAssignmentAwaitingConsensusReview = 54203,
    [pbr::OriginalName("TASK_ASSIGNMENT_REJECTED")] TaskAssignmentRejected = 54204,
    /// <summary>
    /// Task Assignment Reviews 543xx
    /// </summary>
    [pbr::OriginalName("TASK_ASSIGNMENT_REVIEW_SUCCESS")] TaskAssignmentReviewSuccess = 54300,
    [pbr::OriginalName("TASK_ASSIGNMENT_REVIEW_PENDING")] TaskAssignmentReviewPending = 54301,
    [pbr::OriginalName("TASK_ASSIGNMENT_REVIEW_DISMISSED")] TaskAssignmentReviewDismissed = 54302,
    /// <summary>
    /// Label Order Related Status Code 55xxx
    /// </summary>
    [pbr::OriginalName("LABEL_ORDER_PENDING")] LabelOrderPending = 55001,
    [pbr::OriginalName("LABEL_ORDER_IN_PROGRESS")] LabelOrderInProgress = 55002,
    [pbr::OriginalName("LABEL_ORDER_SUCCESS")] LabelOrderSuccess = 55003,
    [pbr::OriginalName("LABEL_ORDER_CANCELED")] LabelOrderCanceled = 55004,
    /// <summary>
    /// License Related Status Code 600xx
    /// </summary>
    [pbr::OriginalName("LICENSE_ACTIVE")] LicenseActive = 60000,
    [pbr::OriginalName("LICENSE_DOES_NOT_EXIST")] LicenseDoesNotExist = 60001,
    [pbr::OriginalName("LICENSE_NEED_UPDATE")] LicenseNeedUpdate = 60002,
    [pbr::OriginalName("LICENSE_EXPIRED")] LicenseExpired = 60003,
    [pbr::OriginalName("LICENSE_REVOKED")] LicenseRevoked = 60004,
    /// <summary>
    /// hidden state not reflected to users
    /// </summary>
    [pbr::OriginalName("LICENSE_DELETED")] LicenseDeleted = 60005,
    [pbr::OriginalName("LICENSE_VOLUME_EXCEEDED")] LicenseVolumeExceeded = 60006,
    /// <summary>
    /// Password Related Status Code
    /// </summary>
    [pbr::OriginalName("PASSWORD_VALIDATION_SUCCESS")] PasswordValidationSuccess = 61000,
    [pbr::OriginalName("PASSWORD_VALIDATION_FAILED")] PasswordValidationFailed = 61001,
    [pbr::OriginalName("PASSWORDPOLICY_INVALID_ARGUMENT")] PasswordpolicyInvalidArgument = 61002,
    /// <summary>
    /// Feature flags status code
    /// </summary>
    [pbr::OriginalName("FEATUREFLAG_CONFIG_NOT_FOUND")] FeatureflagConfigNotFound = 62000,
    [pbr::OriginalName("FEATUREFLAG_INVALID_ARGUMENT")] FeatureflagInvalidArgument = 62001,
    [pbr::OriginalName("FEATUREFLAG_BLOCKED")] FeatureflagBlocked = 62002,
    [pbr::OriginalName("FEATUREFLAG_NOT_FOUND")] FeatureflagNotFound = 62003,
    /// <summary>
    /// Maintenance status code
    /// </summary>
    [pbr::OriginalName("MAINTENANCE_SUCCESS")] MaintenanceSuccess = 63000,
    [pbr::OriginalName("MAINTENANCE_FAILED")] MaintenanceFailed = 63001,
    /// <summary>
    /// Datasets 64xxx
    /// The dataset version is pending to be processed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_PENDING")] DatasetVersionPending = 64005,
    /// <summary>
    /// The dataset version is currently being processed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_IN_PROGRESS")] DatasetVersionInProgress = 64010,
    /// <summary>
    /// The dataset version is ready to be used.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_READY")] DatasetVersionReady = 64015,
    /// <summary>
    /// An error occurred during the dataset version processing.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_FAILURE")] DatasetVersionFailure = 64020,
    /// <summary>
    /// An unexpected error occurred during the dataset version processing.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_UNEXPECTED_ERROR")] DatasetVersionUnexpectedError = 64025,
    /// <summary>
    /// An alteration to dataset version would create a conflict
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_CONFLICT")] DatasetVersionConflict = 64030,
    /// <summary>
    /// The dataset input was successfully added.
    /// </summary>
    [pbr::OriginalName("DATASET_INPUT_SUCCESS")] DatasetInputSuccess = 64100,
    /// <summary>
    /// The dataset input is a duplicate.
    /// Deprecated: Unused.
    /// </summary>
    [pbr::OriginalName("DATASET_INPUT_DUPLICATE")] DatasetInputDuplicate = 64101,
    /// <summary>
    /// The dataset version export is completed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_SUCCESS")] DatasetVersionExportSuccess = 64200,
    /// <summary>
    /// The dataset version is pending to be exported.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_PENDING")] DatasetVersionExportPending = 64201,
    /// <summary>
    /// An error occurred during the dataset version export.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_FAILED")] DatasetVersionExportFailed = 64202,
    /// <summary>
    /// The dataset version is currently being exported.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_IN_PROGRESS")] DatasetVersionExportInProgress = 64203,
    /// <summary>
    /// An unexpected error occurred during the dataset version export.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_UNEXPECTED_ERROR")] DatasetVersionExportUnexpectedError = 64204,
    /// <summary>
    /// Generic Job status codes
    /// </summary>
    [pbr::OriginalName("JOB_QUEUED")] JobQueued = 64000,
    [pbr::OriginalName("JOB_RUNNING")] JobRunning = 64001,
    [pbr::OriginalName("JOB_COMPLETED")] JobCompleted = 64002,
    [pbr::OriginalName("JOB_FAILED")] JobFailed = 64003,
    [pbr::OriginalName("JOB_CANCELLED")] JobCancelled = 64004,
    [pbr::OriginalName("JOB_UNEXPECTED_ERROR")] JobUnexpectedError = 64006,
    [pbr::OriginalName("JOB_CONFLICT")] JobConflict = 64007,
    /// <summary>
    ///auth issues
    /// </summary>
    [pbr::OriginalName("AUTH_MISSING_IDP_ASSOC")] AuthMissingIdpAssoc = 65000,
    [pbr::OriginalName("LIST_OBJECTS_FAILED")] ListObjectsFailed = 66000,
    [pbr::OriginalName("ARCHIVE_EXTRACT_FAILED")] ArchiveExtractFailed = 67000,
    /// <summary>
    /// Multipart uploading status codes
    /// </summary>
    [pbr::OriginalName("UPLOAD_IN_PROGRESS")] UploadInProgress = 68000,
    [pbr::OriginalName("UPLOAD_DONE")] UploadDone = 68001,
    [pbr::OriginalName("UPLOAD_FAILED")] UploadFailed = 68002,
    [pbr::OriginalName("UPLOAD_UNEXPECTED_ERROR")] UploadUnexpectedError = 68003,
    [pbr::OriginalName("UPLOAD_EXPIRED")] UploadExpired = 68004,
    [pbr::OriginalName("UPLOAD_CANCELED")] UploadCanceled = 68005,
    [pbr::OriginalName("UPLOAD_CONFLICT")] UploadConflict = 68006,
    /// <summary>
    /// Billing related issues: 69xxx
    /// </summary>
    [pbr::OriginalName("BILLING_INVALID_INFO")] BillingInvalidInfo = 69000,
    [pbr::OriginalName("BILLING_MISSING_TOKENS")] BillingMissingTokens = 69001,
    /// <summary>
    /// Logs related issues: 70000;
    /// </summary>
    [pbr::OriginalName("LOG_ENTRIES_INVALID_REQUEST")] LogEntriesInvalidRequest = 70000,
    /// <summary>
    /// Internal issues: 98xxx
    /// </summary>
    [pbr::OriginalName("INTERNAL_SERVER_ISSUE")] InternalServerIssue = 98004,
    [pbr::OriginalName("INTERNAL_FETCHING_ISSUE")] InternalFetchingIssue = 98005,
    [pbr::OriginalName("INTERNAL_DATABASE_ISSUE")] InternalDatabaseIssue = 98006,
    [pbr::OriginalName("INTERNAL_CONTEXT_CANCELED")] InternalContextCanceled = 98008,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_TIMEOUT")] InternalUnexpectedTimeout = 98009,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_V1")] InternalUnexpectedV1 = 98010,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_PANIC")] InternalUnexpectedPanic = 98011,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_SPIRE")] InternalUnexpectedSpire = 98012,
    [pbr::OriginalName("INTERNAL_REDIS_UNAVAILABLE")] InternalRedisUnavailable = 98013,
    [pbr::OriginalName("INTERNAL_RESOURCE_EXHAUSTED")] InternalResourceExhausted = 98014,
    [pbr::OriginalName("INTERNAL_REDIS_UNCATEGORIZED")] InternalRedisUncategorized = 98015,
    [pbr::OriginalName("INTERNAL_AWS_UNCATEGORIZED")] InternalAwsUncategorized = 98016,
    [pbr::OriginalName("INTERNAL_AZURE_UNCATEGORIZED")] InternalAzureUncategorized = 98017,
    [pbr::OriginalName("INTERNAL_VECTORDB_UNCATEGORIZED")] InternalVectordbUncategorized = 98018,
    [pbr::OriginalName("INTERNAL_ORACLE_UNCATEGORIZED")] InternalOracleUncategorized = 98019,
    [pbr::OriginalName("INTERNAL_VULTR_UNCATEGORIZED")] InternalVultrUncategorized = 98020,
    /// <summary>
    /// Uncategorized: 99xxx: move off as soon as known
    /// </summary>
    [pbr::OriginalName("CONN_UNCATEGORIZED")] ConnUncategorized = 99001,
    [pbr::OriginalName("MODEL_UNCATEGORIZED")] ModelUncategorized = 99002,
    [pbr::OriginalName("INPUT_UNCATEGORIZED")] InputUncategorized = 99003,
    [pbr::OriginalName("ANNOTATION_UNCATEGORIZED")] AnnotationUncategorized = 99004,
    [pbr::OriginalName("BILLING_UNCATEGORIZED")] BillingUncategorized = 99005,
    [pbr::OriginalName("INTERNAL_UNCATEGORIZED")] InternalUncategorized = 99009,
    /// <summary>
    /// Deprecated: migrate off to one of the internal issues
    /// </summary>
    [pbr::OriginalName("BAD_REQUEST")] BadRequest = 90400,
    /// <summary>
    /// Deprecated: migrate off to one of the internal issues
    /// </summary>
    [pbr::OriginalName("SERVER_ERROR")] ServerError = 90500,
  }

  #endregion

}

#endregion Designer generated code
