// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/status/status_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Api.Status {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/status/status_code.proto</summary>
  public static partial class StatusCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/status/status_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatusCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Citwcm90by9jbGFyaWZhaS9hcGkvc3RhdHVzL3N0YXR1c19jb2RlLnByb3Rv",
            "EhNjbGFyaWZhaS5hcGkuc3RhdHVzKo5VCgpTdGF0dXNDb2RlEggKBFpFUk8Q",
            "ABIMCgdTVUNDRVNTEJBOEhEKDE1JWEVEX1NUQVRVUxCaThIMCgdGQUlMVVJF",
            "EKROEg4KCVRSWV9BR0FJThCuThIUCg9OT1RfSU1QTEVNRU5URUQQuE4SCgoF",
            "TU9WRUQQwk4SCwoGVEVBUE9UEMxOEhgKE0NPTk5fQUNDT1VOVF9JU1NVRVMQ",
            "+FUSGwoSQ09OTl9UT0tFTl9JTlZBTElEEPlVGgIIARIdChhDT05OX0NSRURF",
            "TlRJQUxTX0lOVkFMSUQQ+lUSHQoYQ09OTl9FWENFRURfSE9VUkxZX0xJTUlU",
            "EPtVEh4KGUNPTk5fRVhDRUVEX01PTlRITFlfTElNSVQQ/FUSEwoOQ09OTl9U",
            "SFJPVFRMRUQQ/VUSGAoTQ09OTl9FWENFRURTX0xJTUlUUxD+VRIdChhDT05O",
            "X0lOU1VGRklDSUVOVF9TQ09QRVMQ/1USFQoQQ09OTl9LRVlfSU5WQUxJRBCA",
            "VhIXChJDT05OX0tFWV9OT1RfRk9VTkQQgVYSHAoXQ09OTl9CQURfUkVRVUVT",
            "VF9GT1JNQVQQ3FYSGAoTQ09OTl9ET0VTX05PVF9FWElTVBDdVhIZChRDT05O",
            "X0lOVkFMSURfUkVRVUVTVBDeVhIcChdDT05OX01FVEhPRF9OT1RfQUxMT1dF",
            "RBDfVhIZChRDT05OX05PX0dEUFJfQ09OU0VOVBDgVhIeChlDT05OX0FVVEhf",
            "TUVUSE9EX0RJU0FCTEVEEMBXEhMKDU1PREVMX1RSQUlORUQQ7KQBEhQKDk1P",
            "REVMX1RSQUlOSU5HEO2kARIVCg9NT0RFTF9VTlRSQUlORUQQ7qQBEh8KGU1P",
            "REVMX1FVRVVFRF9GT1JfVFJBSU5JTkcQ76QBEhUKD01PREVMX1VQTE9BRElO",
            "RxDwpAESHAoWTU9ERUxfVVBMT0FESU5HX0ZBSUxFRBDxpAESGwoVTU9ERUxf",
            "VFJBSU5JTkdfRkFJTEVEEPKkARIcChZNT0RFTF9UUkFJTklOR19OT19EQVRB",
            "EPakARIhChtNT0RFTF9UUkFJTklOR19OT19QT1NJVElWRVMQ96QBEioKJE1P",
            "REVMX1RSQUlOSU5HX09ORV9WU19OX1NJTkdMRV9DTEFTUxD4pAESHgoYTU9E",
            "RUxfVFJBSU5JTkdfVElNRURfT1VUEPmkARIiChxNT0RFTF9UUkFJTklOR19X",
            "QUlUSU5HX0VSUk9SEPqkARIiChxNT0RFTF9UUkFJTklOR19VTktOT1dOX0VS",
            "Uk9SEPukARImChxNT0RFTF9UUkFJTklOR19NU0dfUkVERUxJVkVSEPykARoC",
            "CAESJgogTU9ERUxfVFJBSU5JTkdfSU5TVUZGSUNJRU5UX0RBVEEQ/aQBEiMK",
            "HU1PREVMX1RSQUlOSU5HX0lOVkFMSURfUEFSQU1TEP6kARI0Ci5NT0RFTF9U",
            "UkFJTklOR19JTlZBTElEX0RBVEFfVE9MRVJBTkNFX0VYQ0VFREVEEP+kARIa",
            "ChRNT0RFTF9NT0RJRllfU1VDQ0VTUxCepQESGgoUTU9ERUxfTU9ESUZZX1BF",
            "TkRJTkcQn6UBEhkKE01PREVMX01PRElGWV9GQUlMRUQQoKUBEhoKFE1PREVM",
            "X0RPRVNfTk9UX0VYSVNUENClARIdChdNT0RFTF9QRVJNSVNTSU9OX0RFTklF",
            "RBDRpQESHAoWTU9ERUxfSU5WQUxJRF9BUkdVTUVOVBDSpQESGwoVTU9ERUxf",
            "SU5WQUxJRF9SRVFVRVNUENOlARIVCg9NT0RFTF9FVkFMVUFURUQQtKYBEhYK",
            "EE1PREVMX0VWQUxVQVRJTkcQtaYBEhkKE01PREVMX05PVF9FVkFMVUFURUQQ",
            "tqYBEiEKG01PREVMX1FVRVVFRF9GT1JfRVZBTFVBVElPThC3pgESIAoaTU9E",
            "RUxfRVZBTFVBVElPTl9USU1FRF9PVVQQvqYBEiQKHk1PREVMX0VWQUxVQVRJ",
            "T05fV0FJVElOR19FUlJPUhC/pgESJAoeTU9ERUxfRVZBTFVBVElPTl9VTktO",
            "T1dOX0VSUk9SEMCmARIdChdNT0RFTF9QUkVESUNUSU9OX0ZBSUxFRBDBpgES",
            "KAoeTU9ERUxfRVZBTFVBVElPTl9NU0dfUkVERUxJVkVSEMKmARoCCAESIgoc",
            "TU9ERUxfRVZBTFVBVElPTl9ORUVEX0xBQkVMUxDDpgESIgocTU9ERUxfRVZB",
            "TFVBVElPTl9ORUVEX0lOUFVUUxDEpgESHQoXTU9ERUxfRVZBTFVBVElPTl9G",
            "QUlMRUQQxaYBEh0KF01PREVMX0RFUExPWU1FTlRfRkFJTEVEEOamARIVCg9N",
            "T0RFTF9ERVBMT1lJTkcQ56YBEiEKG01PREVMX1FVRVVFRF9GT1JfREVQTE9Z",
            "TUVOVBDopgESGAoSTU9ERUxfTk9UX0RFUExPWUVEEOmmARImCiBNT0RFTF9S",
            "RUZFUkVOQ0VfSU5WQUxJRF9BUkdVTUVOVBCYpwESKgokTU9ERUxfRVhBTVBM",
            "RV9JTlBVVF9JTlZBTElEX0FSR1VNRU5UEKynARIgChpXT1JLRkxPV19OT19N",
            "QVRDSElOR19JTlBVVBDxqwESJAoeV09SS0ZMT1dfUkVRVUlSRV9UUkFJTkVE",
            "X01PREVMEPKrARIYChJXT1JLRkxPV19EVVBMSUNBVEUQ1KwBEiEKG1dPUktG",
            "TE9XX1VOU1VQUE9SVEVEX0ZPUk1BVBDVrAESHQoXV09SS0ZMT1dfRE9FU19O",
            "T1RfRVhJU1QQ1qwBEiAKGldPUktGTE9XX1BFUk1JU1NJT05fREVOSUVEENes",
            "ARIfChlXT1JLRkxPV19JTlZBTElEX0FSR1VNRU5UENisARIdChdXT1JLRkxP",
            "V19JTlZBTElEX1JFQ0lQRRDZrAESHwoZV09SS0ZMT1dfSU5WQUxJRF9URU1Q",
            "TEFURRDarAESHAoWV09SS0ZMT1dfSU5WQUxJRF9HUkFQSBDbrAESHwoZV09S",
            "S0ZMT1dfSU5URVJOQUxfRkFJTFVSRRDcrAESHgoYV09SS0ZMT1dfSU5WQUxJ",
            "RF9SRVFVRVNUENezARIdChdXT1JLRkxPV19NT0RJRllfU1VDQ0VTUxCGrQES",
            "HQoXV09SS0ZMT1dfTU9ESUZZX1BFTkRJTkcQh60BEhwKFldPUktGTE9XX01P",
            "RElGWV9GQUlMRUQQiK0BEh0KF1dPUktGTE9XX1JFSU5ERVhfRkFJTEVEEImt",
            "ARIcChZDT05DRVBUX01PRElGWV9TVUNDRVNTEO60ARIcChZDT05DRVBUX01P",
            "RElGWV9QRU5ESU5HEO+0ARIbChVDT05DRVBUX01PRElGWV9GQUlMRUQQ8LQB",
            "EhgKEkFOTk9UQVRJT05fU1VDQ0VTUxDWvAESGAoSQU5OT1RBVElPTl9QRU5E",
            "SU5HENe8ARIXChFBTk5PVEFUSU9OX0ZBSUxFRBDYvAESHwoZQU5OT1RBVElP",
            "Tl9VTktOT1dOX1NUQVRVUxDavAESIQobQU5OT1RBVElPTl9JTlZBTElEX0FS",
            "R1VNRU5UENu8ARIiChxBTk5PVEFUSU9OX1BFUk1JU1NJT05fREVOSUVEENy8",
            "ARIgChpBTk5PVEFUSU9OX0FXQUlUSU5HX1JFVklFVxDdvAESKgokQU5OT1RB",
            "VElPTl9BV0FJVElOR19DT05TRU5TVVNfUkVWSUVXEN+8ARIeChhBTk5PVEFU",
            "SU9OX1JFVklFV19ERU5JRUQQ3rwBEh8KGUFOTk9UQVRJT05fTU9ESUZZX1NV",
            "Q0NFU1MQur0BEh8KGUFOTk9UQVRJT05fTU9ESUZZX1BFTkRJTkcQu70BEh4K",
            "GEFOTk9UQVRJT05fTU9ESUZZX0ZBSUxFRBC8vQESJgogTUVUQURBVEFfSU5W",
            "QUxJRF9QQVRDSF9BUkdVTUVOVFMQxMIBEhwKFk1FVEFEQVRBX1BBUlNJTkdf",
            "SVNTVUUQxcIBEiEKG01FVEFEQVRBX01BTklQVUxBVElPTl9JU1NVRRDGwgES",
            "HAoWVFJBSU5FUl9KT0JfU1RBVEVfTk9ORRCowwESHgoYVFJBSU5FUl9KT0Jf",
            "U1RBVEVfUVVFVUVEEKnDARIfChlUUkFJTkVSX0pPQl9TVEFURV9SVU5OSU5H",
            "EKrDARIgChpUUkFJTkVSX0pPQl9TVEFURV9DT01QTEVURRCrwwESHQoXVFJB",
            "SU5FUl9KT0JfU1RBVEVfRVJST1IQrMMBEhcKEURBVEFfRFVNUF9TVUNDRVNT",
            "EL7EARIXChFEQVRBX0RVTVBfUEVORElORxC/xAESFgoQREFUQV9EVU1QX0ZB",
            "SUxFRBDAxAESGwoVREFUQV9EVU1QX0lOX1BST0dSRVNTEMHEARIbChFEQVRB",
            "X0RVTVBfTk9fREFUQRDCxAEaAggBEiAKGkRBVEFfRFVNUF9VTkVYUEVDVEVE",
            "X0VSUk9SEMPEARIeChhEQVRBX0RVTVBfRVhQT1JUX1NVQ0NFU1MQ0sQBEh4K",
            "GERBVEFfRFVNUF9FWFBPUlRfUEVORElORxDTxAESHQoXREFUQV9EVU1QX0VY",
            "UE9SVF9GQUlMRUQQ1MQBEiIKHERBVEFfRFVNUF9FWFBPUlRfSU5fUFJPR1JF",
            "U1MQ1cQBEicKIURBVEFfRFVNUF9FWFBPUlRfVU5FWFBFQ1RFRF9FUlJPUhDW",
            "xAESHQoXQVBQX0RVUExJQ0FUSU9OX1NVQ0NFU1MQ8MQBEhwKFkFQUF9EVVBM",
            "SUNBVElPTl9GQUlMRUQQ8cQBEh0KF0FQUF9EVVBMSUNBVElPTl9QRU5ESU5H",
            "EPLEARIhChtBUFBfRFVQTElDQVRJT05fSU5fUFJPR1JFU1MQ88QBEiUKH0FQ",
            "UF9EVVBMSUNBVElPTl9JTlZBTElEX1JFUVVFU1QQ9MQBEhsKFU1PRFVMRV9E",
            "T0VTX05PVF9FWElTVBDUxQESHgoYTU9EVUxFX1BFUk1JU1NJT05fREVOSUVE",
            "ENXFARIdChdNT0RVTEVfSU5WQUxJRF9BUkdVTUVOVBDWxQESHAoWTU9EVUxF",
            "X0lOVkFMSURfUkVRVUVTVBDXxQESHAoWQlVMS19PUEVSQVRJT05fU1VDQ0VT",
            "UxC4xgESGwoVQlVMS19PUEVSQVRJT05fRkFJTEVEELnGARIcChZCVUxLX09Q",
            "RVJBVElPTl9QRU5ESU5HELrGARIgChpCVUxLX09QRVJBVElPTl9JTl9QUk9H",
            "UkVTUxC7xgESJAoeQlVMS19PUEVSQVRJT05fSU5WQUxJRF9SRVFVRVNUELzG",
            "ARIeChhCVUxLX09QRVJBVElPTl9DQU5DRUxMRUQQvcYBEiUKH0JVTEtfT1BF",
            "UkFUSU9OX1VORVhQRUNURURfRVJST1IQvsYBEhsKFVJVTk5FUl9ET0VTX05P",
            "VF9FWElTVBCAyAESHgoYUlVOTkVSX1BFUk1JU1NJT05fREVOSUVEEIHIARId",
            "ChdSVU5ORVJfSU5WQUxJRF9BUkdVTUVOVBCCyAESHAoWUlVOTkVSX0lOVkFM",
            "SURfUkVRVUVTVBCDyAESGAoSUlVOTkVSX05FRURTX1JFVFJZEITIARIcChZJ",
            "TlBVVF9ET1dOTE9BRF9TVUNDRVNTELDqARIcChZJTlBVVF9ET1dOTE9BRF9Q",
            "RU5ESU5HELHqARIbChVJTlBVVF9ET1dOTE9BRF9GQUlMRUQQsuoBEiAKGklO",
            "UFVUX0RPV05MT0FEX0lOX1BST0dSRVNTELPqARIgChpJTlBVVF9TVEFUVVNf",
            "VVBEQVRFX0ZBSUxFRBC06gESGQoTSU5QVVRfREVMRVRFX0ZBSUxFRBC16gES",
            "FQoPSU5QVVRfRFVQTElDQVRFEJTrARIeChhJTlBVVF9VTlNVUFBPUlRFRF9G",
            "T1JNQVQQlesBEhoKFElOUFVUX0RPRVNfTk9UX0VYSVNUEJbrARIdChdJTlBV",
            "VF9QRVJNSVNTSU9OX0RFTklFRBCX6wESHAoWSU5QVVRfSU5WQUxJRF9BUkdV",
            "TUVOVBCY6wESFgoQSU5QVVRfT1ZFUl9MSU1JVBCZ6wESFwoRSU5QVVRfSU5W",
            "QUxJRF9VUkwQmusBEhoKFElOUFVUX01PRElGWV9TVUNDRVNTEPjrARIaChRJ",
            "TlBVVF9NT0RJRllfUEVORElORxD56wESGQoTSU5QVVRfTU9ESUZZX0ZBSUxF",
            "RBD76wESHwoZSU5QVVRfU1RPUkFHRV9IT1NUX0ZBSUxFRBCC7AESHQoXQUxM",
            "X0lOUFVUX0lOVkFMSURfQllURVMQ3OwBEhsKFUlOUFVUX0NMVVNURVJfU1VD",
            "Q0VTUxDA7QESGwoVSU5QVVRfQ0xVU1RFUl9QRU5ESU5HEMHtARIaChRJTlBV",
            "VF9DTFVTVEVSX0ZBSUxFRBDC7QESHwoZSU5QVVRfQ0xVU1RFUl9JTl9QUk9H",
            "UkVTUxDD7QESGwoVSU5QVVRfUkVJTkRFWF9TVUNDRVNTEKTuARIbChVJTlBV",
            "VF9SRUlOREVYX1BFTkRJTkcQpe4BEhoKFElOUFVUX1JFSU5ERVhfRkFJTEVE",
            "EKbuARIfChlJTlBVVF9SRUlOREVYX0lOX1BST0dSRVNTEKfuARIiChxJTlBV",
            "VF9WSURFT19ET1dOTE9BRF9TVUNDRVNTEJjyARIiChxJTlBVVF9WSURFT19E",
            "T1dOTE9BRF9QRU5ESU5HEJnyARIhChtJTlBVVF9WSURFT19ET1dOTE9BRF9G",
            "QUlMRUQQmvIBEhsKFUlOUFVUX1ZJREVPX0RVUExJQ0FURRD88gESJAoeSU5Q",
            "VVRfVklERU9fVU5TVVBQT1JURURfRk9STUFUEP3yARIgChpJTlBVVF9WSURF",
            "T19ET0VTX05PVF9FWElTVBD+8gESIwodSU5QVVRfVklERU9fUEVSTUlTU0lP",
            "Tl9ERU5JRUQQ//IBEiIKHElOUFVUX1ZJREVPX0lOVkFMSURfQVJHVU1FTlQQ",
            "gPMBEhwKFklOUFVUX1ZJREVPX09WRVJfTElNSVQQgfMBEh0KF0lOUFVUX1ZJ",
            "REVPX0lOVkFMSURfVVJMEILzARIgChpJTlBVVF9WSURFT19NT0RJRllfU1VD",
            "Q0VTUxDg8wESIAoaSU5QVVRfVklERU9fTU9ESUZZX1BFTkRJTkcQ4fMBEh8K",
            "GUlOUFVUX1ZJREVPX01PRElGWV9GQUlMRUQQ4/MBEiUKH0lOUFVUX1ZJREVP",
            "X1NUT1JBR0VfSE9TVF9GQUlMRUQQ6vMBEiQKHkFMTF9JTlBVVF9WSURFT1Nf",
            "SU5WQUxJRF9CWVRFUxDE9AESJAoeSU5QVVRfVklERU9fUFJPQ0VTU0lOR19T",
            "VUNDRVNTEKj1ARIkCh5JTlBVVF9WSURFT19QUk9DRVNTSU5HX1BFTkRJTkcQ",
            "svUBEiMKHUlOUFVUX1ZJREVPX1BST0NFU1NJTkdfRkFJTEVEELz1ARInCiFJ",
            "TlBVVF9WSURFT19TVE9SQUdFX0lOQ09OU0lTVEVOQ1kQxvUBEiEKG0lOUFVU",
            "X1ZJREVPX1NUT1JBR0VfRkFJTFVSRRDQ9QESKAoiSU5QVVRfVklERU9fVVJM",
            "X0dFTkVSQVRJT05fRkFJTFVSRRDa9QESHQoXSU5QVVRfQ09OTkVDVElPTl9G",
            "QUlMRUQQvLgCEiYKIFJFUVVFU1RfRElTQUJMRURfRk9SX01BSU5URU5BTkNF",
            "EL24AhIvCiVJTlBVVF9XUklURVNfRElTQUJMRURfRk9SX01BSU5URU5BTkNF",
            "EL64AhoCCAESGwoVSU5QVVRfSU5WQUxJRF9SRVFVRVNUEL+4AhIdChdQUkVE",
            "SUNUX0lOVkFMSURfUkVRVUVTVBDBuAISHAoWU0VBUkNIX0lOVkFMSURfUkVR",
            "VUVTVBDCuAISHgoYQ09OQ0VQVFNfSU5WQUxJRF9SRVFVRVNUEMO4AhIbChVT",
            "VEFUU19JTlZBTElEX1JFUVVFU1QQxLgCEhwKFkRBVEFCQVNFX0RVUExJQ0FU",
            "RV9LRVkQyrgCEiAKGkRBVEFCQVNFX1NUQVRFTUVOVF9USU1FT1VUEMu4AhIk",
            "Ch5EQVRBQkFTRV9JTlZBTElEX1JPV1NfQUZGRUNURUQQzLgCEiAKGkRBVEFC",
            "QVNFX0RFQURMT0NLX0RFVEVDVEVEEM24AhIYChJEQVRBQkFTRV9GQUlMX1RB",
            "U0sQzrgCEiYKIERBVEFCQVNFX0ZBSUxfVE9fR0VUX0NPTk5FQ1RJT05TEM+4",
            "AhIfChlEQVRBQkFTRV9UT09fTUFOWV9DTElFTlRTENC4AhIiChxEQVRBQkFT",
            "RV9DT05TVFJBSU5UX1ZJT0xBVEVEENG4AhIXChFEQVRBQkFTRV9DQU5DRUxF",
            "RBDVuAISHwoZQVNZTkNfV09SS0VSX01VTFRJX0VSUk9SUxDUuAISHAoWUlBD",
            "X1JFUVVFU1RfUVVFVUVfRlVMTBDeuAISHAoWUlBDX1NFUlZFUl9VTkFWQUlM",
            "QUJMRRDfuAISGQoTUlBDX1JFUVVFU1RfVElNRU9VVBDguAISIwodUlBDX01B",
            "WF9NRVNTQUdFX1NJWkVfRVhDRUVERUQQ4bgCEhIKDFJQQ19DQU5DRUxFRBDj",
            "uAISGAoSUlBDX1VOS05PV05fTUVUSE9EEOS4AhIeChhSRVFVRVNUX0NBTkNF",
            "TEVEX0JZX1VTRVIQ5bgCEh4KGENMVVNURVJfSU5URVJOQUxfRkFJTFVSRRCg",
            "0AISHwoZRVhURVJOQUxfQ09OTkVDVElPTl9FUlJPUhDiuAISGgoUUVVFUllf",
            "SU5WQUxJRF9TWU5UQVgQ8rgCEhYKEFFVRVVFX0NPTk5fRVJST1IQqMACEiEK",
            "G1FVRVVFX0NMT1NFX1JFUVVFU1RfVElNRU9VVBCqwAISFwoRUVVFVUVfQ09O",
            "Tl9DTE9TRUQQq8ACEh8KGVFVRVVFX1BVQkxJU0hfQUNLX1RJTUVPVVQQrMAC",
            "EhkKE1FVRVVFX1BVQkxJU0hfRVJST1IQrcACEiAKGlFVRVVFX1NVQlNDUklQ",
            "VElPTl9USU1FT1VUEK7AAhIeChhRVUVVRV9TVUJTQ1JJUFRJT05fRVJST1IQ",
            "r8ACEh4KGFFVRVVFX01BUlNIQUxMSU5HX0ZBSUxFRBCwwAISIAoaUVVFVUVf",
            "VU5NQVJTSEFMTElOR19GQUlMRUQQscACEicKIVFVRVVFX01BWF9NU0dfUkVE",
            "RUxJVkVSWV9FWENFRURFRBCywAISFwoRUVVFVUVfQUNLX0ZBSUxVUkUQs8AC",
            "EhMKDVNRU19PVkVSTElNSVQQjMECEiAKGlNRU19JTlZBTElEX1JFQ0VJUFRf",
            "SEFORExFEI3BAhIRCgtTUVNfVU5LTk9XThCOwQISHQoXU0VBUkNIX0lOVEVS",
            "TkFMX0ZBSUxVUkUQ+c8CEh8KGVNFQVJDSF9QUk9KRUNUSU9OX0ZBSUxVUkUQ",
            "+s8CEh8KGVNFQVJDSF9QUkVESUNUSU9OX0ZBSUxVUkUQ+88CEicKIVNFQVJD",
            "SF9CWV9OT1RfRlVMTFlfSU5ERVhFRF9JTlBVVBD8zwISIAoaU0FWRURfU0VB",
            "UkNIX01PRElGWV9GQUlMRUQQ/c8CEh8KGVNFQVJDSF9DT1VOVFNfVU5BVkFJ",
            "TEFCTEUQ/s8CEhcKEUVWQUxVQVRJT05fUVVFVUVEENzQAhIcChZFVkFMVUFU",
            "SU9OX0lOX1BST0dSRVNTEN3QAhIYChJFVkFMVUFUSU9OX1NVQ0NFU1MQ3tAC",
            "EigKIkVWQUxVQVRJT05fRkFJTEVEX1RPX1JFVFJJRVZFX0RBVEEQ39ACEiEK",
            "G0VWQUxVQVRJT05fSU5WQUxJRF9BUkdVTUVOVBDg0AISFwoRRVZBTFVBVElP",
            "Tl9GQUlMRUQQ4dACEhgKEkVWQUxVQVRJT05fUEVORElORxDi0AISGgoURVZB",
            "TFVBVElPTl9USU1FRF9PVVQQ49ACEiEKG0VWQUxVQVRJT05fVU5FWFBFQ1RF",
            "RF9FUlJPUhDk0AISFgoQRVZBTFVBVElPTl9NSVhFRBDl0AISGAoSU1RSSVBF",
            "X0VWRU5UX0VSUk9SEOHXAhIQCgpDQUNIRV9NSVNTEMnfAhImCiBSRURJU19T",
            "Q1JJUFRfRVhJVEVEX1dJVEhfRkFJTFVSRRDK3wISFgoQUkVESVNfU1RSRUFN",
            "X0VSUhDL3wISGAoSUkVESVNfTk9fQ09OU1VNRVJTEMzfAhIaChRSRURJU19T",
            "VFJFQU1fQkFDS09GRhDN3wISGAoSU0lHTlVQX0VWRU5UX0VSUk9SELHnAhIU",
            "Cg5TSUdOVVBfRkxBR0dFRBCy5wISGgoURklMRVRZUEVfVU5TVVBQT1JURUQQ",
            "s+cCEh8KGUFQUF9DT1VOVF9JTlZBTElEX01FU1NBR0UQme8CEicKIUFQUF9D",
            "T1VOVF9VUERBVEVfSU5DUkVNRU5UX0ZBSUxFRBCa7wISHgoYQVBQX0NPVU5U",
            "X1JFQlVJTERfRkFJTEVEEJvvAhIgChpBUFBfQ09VTlRfSU5URVJOQUxfRkFJ",
            "TFVSRRCc7wISFwoRTVBfRE9XTkxPQURfRVJST1IQ/e8CEhoKFE1QX1JFU09M",
            "VkVfRE5TX0VSUk9SEP7vAhIpCiNNUF9ET1dOTE9BRF9NQVhfU0laRV9FWENF",
            "RURFRF9FUlJPUhD/7wISGwoVTVBfSU1BR0VfREVDT0RFX0VSUk9SEIDwAhIZ",
            "ChNNUF9JTlZBTElEX0FSR1VNRU5UEIHwAhIfChlNUF9JTUFHRV9QUk9DRVNT",
            "SU5HX0VSUk9SEILwAhIZChNEQVRBVElFUl9DT05OX0VSUk9SEOHwAhIXChFV",
            "U0VSX0NPTlNFTlRfRkFDRRDRhgMSFAoOV09SS0VSX01JU1NJTkcQuI4DEhMK",
            "DVdPUktFUl9BQ1RJVkUQuY4DEhUKD1dPUktFUl9JTkFDVElWRRC6jgMSFwoR",
            "Q09MTEVDVE9SX01JU1NJTkcQoJYDEhYKEENPTExFQ1RPUl9BQ1RJVkUQoZYD",
            "EhgKEkNPTExFQ1RPUl9JTkFDVElWRRCilgMSIQobQ09MTEVDVE9SX1BPU1Rf",
            "SU5QVVRfRkFJTEVEEKOWAxIqCiRTU09fSURFTlRJVFlfUFJPVklERVJfRE9F",
            "U19OT1RfRVhJU1QQiZ4DEhYKEFRBU0tfSU5fUFJPR1JFU1MQ8aUDEg8KCVRB",
            "U0tfRE9ORRDypQMSEgoMVEFTS19XT05UX0RPEPOlAxIRCgtUQVNLX0ZBSUxF",
            "RBD1pQMSDwoJVEFTS19JRExFEPalAxITCg1UQVNLX0NPTkZMSUNUENSmAxIa",
            "ChRUQVNLX05PVF9JTVBMRU1FTlRFRBDVpgMSEgoMVEFTS19NSVNTSU5HENam",
            "AxIZChNMQUJFTF9PUkRFUl9QRU5ESU5HENmtAxIdChdMQUJFTF9PUkRFUl9J",
            "Tl9QUk9HUkVTUxDarQMSGQoTTEFCRUxfT1JERVJfU1VDQ0VTUxDbrQMSGgoU",
            "TEFCRUxfT1JERVJfQ0FOQ0VMRUQQ3K0DEhQKDkxJQ0VOU0VfQUNUSVZFEODU",
            "AxIcChZMSUNFTlNFX0RPRVNfTk9UX0VYSVNUEOHUAxIZChNMSUNFTlNFX05F",
            "RURfVVBEQVRFEOLUAxIVCg9MSUNFTlNFX0VYUElSRUQQ49QDEhUKD0xJQ0VO",
            "U0VfUkVWT0tFRBDk1AMSFQoPTElDRU5TRV9ERUxFVEVEEOXUAxIdChdMSUNF",
            "TlNFX1ZPTFVNRV9FWENFRURFRBDm1AMSIQobUEFTU1dPUkRfVkFMSURBVElP",
            "Tl9TVUNDRVNTEMjcAxIgChpQQVNTV09SRF9WQUxJREFUSU9OX0ZBSUxFRBDJ",
            "3AMSJQofUEFTU1dPUkRQT0xJQ1lfSU5WQUxJRF9BUkdVTUVOVBDK3AMSIgoc",
            "RkVBVFVSRUZMQUdfQ09ORklHX05PVF9GT1VORBCw5AMSIgocRkVBVFVSRUZM",
            "QUdfSU5WQUxJRF9BUkdVTUVOVBCx5AMSGQoTRkVBVFVSRUZMQUdfQkxPQ0tF",
            "RBCy5AMSGQoTTUFJTlRFTkFOQ0VfU1VDQ0VTUxCY7AMSGAoSTUFJTlRFTkFO",
            "Q0VfRkFJTEVEEJnsAxIdChdEQVRBU0VUX1ZFUlNJT05fUEVORElORxCF9AMS",
            "IQobREFUQVNFVF9WRVJTSU9OX0lOX1BST0dSRVNTEIr0AxIbChVEQVRBU0VU",
            "X1ZFUlNJT05fUkVBRFkQj/QDEh0KF0RBVEFTRVRfVkVSU0lPTl9GQUlMVVJF",
            "EJT0AxImCiBEQVRBU0VUX1ZFUlNJT05fVU5FWFBFQ1RFRF9FUlJPUhCZ9AMS",
            "HgoYREFUQVNFVF9WRVJTSU9OX0NPTkZMSUNUEJ70AxIbChVEQVRBU0VUX0lO",
            "UFVUX1NVQ0NFU1MQ5PQDEh0KF0RBVEFTRVRfSU5QVVRfRFVQTElDQVRFEOX0",
            "AxIkCh5EQVRBU0VUX1ZFUlNJT05fRVhQT1JUX1NVQ0NFU1MQyPUDEiQKHkRB",
            "VEFTRVRfVkVSU0lPTl9FWFBPUlRfUEVORElORxDJ9QMSIwodREFUQVNFVF9W",
            "RVJTSU9OX0VYUE9SVF9GQUlMRUQQyvUDEigKIkRBVEFTRVRfVkVSU0lPTl9F",
            "WFBPUlRfSU5fUFJPR1JFU1MQy/UDEi0KJ0RBVEFTRVRfVkVSU0lPTl9FWFBP",
            "UlRfVU5FWFBFQ1RFRF9FUlJPUhDM9QMSEAoKSk9CX1FVRVVFRBCA9AMSEQoL",
            "Sk9CX1JVTk5JTkcQgfQDEhMKDUpPQl9DT01QTEVURUQQgvQDEhAKCkpPQl9G",
            "QUlMRUQQg/QDEhMKDUpPQl9DQU5DRUxMRUQQhPQDEhoKFEpPQl9VTkVYUEVD",
            "VEVEX0VSUk9SEIb0AxISCgxKT0JfQ09ORkxJQ1QQh/QDEhwKFkFVVEhfTUlT",
            "U0lOR19JRFBfQVNTT0MQ6PsDEhkKE0xJU1RfT0JKRUNUU19GQUlMRUQQ0IME",
            "EhwKFkFSQ0hJVkVfRVhUUkFDVF9GQUlMRUQQuIsEEhgKElVQTE9BRF9JTl9Q",
            "Uk9HUkVTUxCgkwQSEQoLVVBMT0FEX0RPTkUQoZMEEhMKDVVQTE9BRF9GQUlM",
            "RUQQopMEEh0KF1VQTE9BRF9VTkVYUEVDVEVEX0VSUk9SEKOTBBIUCg5VUExP",
            "QURfRVhQSVJFRBCkkwQSFQoPVVBMT0FEX0NBTkNFTEVEEKWTBBIVCg9VUExP",
            "QURfQ09ORkxJQ1QQppMEEhoKFEJJTExJTkdfSU5WQUxJRF9JTkZPEIibBBIb",
            "ChVJTlRFUk5BTF9TRVJWRVJfSVNTVUUQ1P0FEh0KF0lOVEVSTkFMX0ZFVENI",
            "SU5HX0lTU1VFENX9BRIdChdJTlRFUk5BTF9EQVRBQkFTRV9JU1NVRRDW/QUS",
            "HwoZSU5URVJOQUxfQ09OVEVYVF9DQU5DRUxFRBDY/QUSIQobSU5URVJOQUxf",
            "VU5FWFBFQ1RFRF9USU1FT1VUENn9BRIcChZJTlRFUk5BTF9VTkVYUEVDVEVE",
            "X1YxENr9BRIfChlJTlRFUk5BTF9VTkVYUEVDVEVEX1BBTklDENv9BRIfChlJ",
            "TlRFUk5BTF9VTkVYUEVDVEVEX1NQSVJFENz9BRIgChpJTlRFUk5BTF9SRURJ",
            "U19VTkFWQUlMQUJMRRDd/QUSIQobSU5URVJOQUxfUkVTT1VSQ0VfRVhIQVVT",
            "VEVEEN79BRIiChxJTlRFUk5BTF9SRURJU19VTkNBVEVHT1JJWkVEEN/9BRIg",
            "ChpJTlRFUk5BTF9BV1NfVU5DQVRFR09SSVpFRBDg/QUSIgocSU5URVJOQUxf",
            "QVpVUkVfVU5DQVRFR09SSVpFRBDh/QUSGAoSQ09OTl9VTkNBVEVHT1JJWkVE",
            "ELmFBhIZChNNT0RFTF9VTkNBVEVHT1JJWkVEELqFBhIZChNJTlBVVF9VTkNB",
            "VEVHT1JJWkVEELuFBhIeChhBTk5PVEFUSU9OX1VOQ0FURUdPUklaRUQQvIUG",
            "EhsKFUJJTExJTkdfVU5DQVRFR09SSVpFRBC9hQYSHAoWSU5URVJOQUxfVU5D",
            "QVRFR09SSVpFRBDBhQYSEQoLQkFEX1JFUVVFU1QQoMIFEhIKDFNFUlZFUl9F",
            "UlJPUhCEwwUiCAi/xgEQv8YBIggI6IECEOiBAiIICOmBAhDpgQIiCAjqgQIQ",
            "6oECIggIzIICEMyCAiIICM2CAhDNggIiCAjOggIQzoICIggIz4ICEM+CAiII",
            "CNCCAhDQggIiCAjRggIQ0YICIggI0oICENKCAiIICLCDAhCwgwIiCAixgwIQ",
            "sYMCIggIs4MCELODAiIICLqDAhC6gwIiCAi7uAIQu7gCIggI0rgCENK4AiII",
            "CNO4AhDTuAIiCAjwwQIQ8MECIggI8cECEPHBAiIICPLBAhDywQIiCAjzwQIQ",
            "88ECIggI9MECEPTBAiIICJzHARCcxwEiCAidxwEQnccBIggInscBEJ7HASII",
            "CJ/HARCfxwEiCAihxwEQoccBIggIoscBEKLHAUJnChxjb20uY2xhcmlmYWku",
            "Z3JwYy5hcGkuc3RhdHVzUAFaPmdpdGh1Yi5jb20vQ2xhcmlmYWkvY2xhcmlm",
            "YWktZ28tZ3JwYy9wcm90by9jbGFyaWZhaS9hcGkvc3RhdHVzogIEQ0FJUGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Clarifai.Api.Status.StatusCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StatusCode {
    /// <summary>
    /// to be revised and greatly expanded
    /// </summary>
    [pbr::OriginalName("ZERO")] Zero = 0,
    /// <summary>
    /// Generic
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 10000,
    [pbr::OriginalName("MIXED_STATUS")] MixedStatus = 10010,
    [pbr::OriginalName("FAILURE")] Failure = 10020,
    [pbr::OriginalName("TRY_AGAIN")] TryAgain = 10030,
    [pbr::OriginalName("NOT_IMPLEMENTED")] NotImplemented = 10040,
    /// <summary>
    /// Resource moved. Respond with Http status 307 and add new Location header to response
    /// </summary>
    [pbr::OriginalName("MOVED")] Moved = 10050,
    /// <summary>
    ///SUCCESS_WARNING_API_DEPRECATED = 10001;
    ///SUCCESS_WARNING_CLIENT_DEPRECATED = 10002;
    /// </summary>
    [pbr::OriginalName("TEAPOT")] Teapot = 10060,
    /// <summary>
    /// Clarifai Connection Codes: 11xxx
    /// </summary>
    [pbr::OriginalName("CONN_ACCOUNT_ISSUES")] ConnAccountIssues = 11000,
    /// <summary>
    /// invalid auth token used. Deprecated: we should return CONN_KEY_INVALID instead now in all cases.
    /// </summary>
    [pbr::OriginalName("CONN_TOKEN_INVALID")] ConnTokenInvalid = 11001,
    /// <summary>
    /// invalid auth credentials
    /// </summary>
    [pbr::OriginalName("CONN_CREDENTIALS_INVALID")] ConnCredentialsInvalid = 11002,
    /// <summary>
    /// throttle hourly limit exceeded
    /// </summary>
    [pbr::OriginalName("CONN_EXCEED_HOURLY_LIMIT")] ConnExceedHourlyLimit = 11003,
    /// <summary>
    /// throttle monthly limit exceeded
    /// </summary>
    [pbr::OriginalName("CONN_EXCEED_MONTHLY_LIMIT")] ConnExceedMonthlyLimit = 11004,
    /// <summary>
    /// throttler and billing stuff
    /// </summary>
    [pbr::OriginalName("CONN_THROTTLED")] ConnThrottled = 11005,
    /// <summary>
    /// throttler and billing stuff
    /// </summary>
    [pbr::OriginalName("CONN_EXCEEDS_LIMITS")] ConnExceedsLimits = 11006,
    /// <summary>
    /// api key has insufficient permissions
    /// </summary>
    [pbr::OriginalName("CONN_INSUFFICIENT_SCOPES")] ConnInsufficientScopes = 11007,
    /// <summary>
    /// api key is invalid
    /// </summary>
    [pbr::OriginalName("CONN_KEY_INVALID")] ConnKeyInvalid = 11008,
    /// <summary>
    /// api key not found
    /// </summary>
    [pbr::OriginalName("CONN_KEY_NOT_FOUND")] ConnKeyNotFound = 11009,
    /// <summary>
    /// multipart form parsing, broken json, etc
    /// </summary>
    [pbr::OriginalName("CONN_BAD_REQUEST_FORMAT")] ConnBadRequestFormat = 11100,
    /// <summary>
    /// when path is bad
    /// </summary>
    [pbr::OriginalName("CONN_DOES_NOT_EXIST")] ConnDoesNotExist = 11101,
    /// <summary>
    /// something wrong with a header
    /// </summary>
    [pbr::OriginalName("CONN_INVALID_REQUEST")] ConnInvalidRequest = 11102,
    /// <summary>
    /// when a request method is not allowed
    /// </summary>
    [pbr::OriginalName("CONN_METHOD_NOT_ALLOWED")] ConnMethodNotAllowed = 11103,
    /// <summary>
    /// lack GDPR consent
    /// </summary>
    [pbr::OriginalName("CONN_NO_GDPR_CONSENT")] ConnNoGdprConsent = 11104,
    /// <summary>
    /// authentication method is disabled
    /// </summary>
    [pbr::OriginalName("CONN_AUTH_METHOD_DISABLED")] ConnAuthMethodDisabled = 11200,
    /// <summary>
    /// Model/Custom Training related 20xxx
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINED")] ModelTrained = 21100,
    /// <summary>
    /// Custom model is currently training.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING")] ModelTraining = 21101,
    /// <summary>
    /// Custom model has not yet been trained.
    /// </summary>
    [pbr::OriginalName("MODEL_UNTRAINED")] ModelUntrained = 21102,
    /// <summary>
    /// Custom model is currently in queue for training, waiting on assets to process first.
    /// </summary>
    [pbr::OriginalName("MODEL_QUEUED_FOR_TRAINING")] ModelQueuedForTraining = 21103,
    [pbr::OriginalName("MODEL_UPLOADING")] ModelUploading = 21104,
    [pbr::OriginalName("MODEL_UPLOADING_FAILED")] ModelUploadingFailed = 21105,
    /// <summary>
    /// generic err msg for any type of model training err.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_FAILED")] ModelTrainingFailed = 21106,
    /// <summary>
    /// Custom model training had no data.  FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_NO_DATA")] ModelTrainingNoData = 21110,
    /// <summary>
    /// Custom model training had no positive examples. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_NO_POSITIVES")] ModelTrainingNoPositives = 21111,
    /// <summary>
    /// Custom model training was ONE_VS_N but with a single class. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_ONE_VS_N_SINGLE_CLASS")] ModelTrainingOneVsNSingleClass = 21112,
    /// <summary>
    /// Training took longer than hard coded timeouts. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_TIMED_OUT")] ModelTrainingTimedOut = 21113,
    /// <summary>
    /// Training got error waiting on asset pipeline to finish. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_WAITING_ERROR")] ModelTrainingWaitingError = 21114,
    /// <summary>
    /// Training threw an unknown exception.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_UNKNOWN_ERROR")] ModelTrainingUnknownError = 21115,
    /// <summary>
    /// Training message was redelivered. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_MSG_REDELIVER")] ModelTrainingMsgRedeliver = 21116,
    /// <summary>
    /// Training got error due to insufficient labelled data. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INSUFFICIENT_DATA")] ModelTrainingInsufficientData = 21117,
    /// <summary>
    /// FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INVALID_PARAMS")] ModelTrainingInvalidParams = 21118,
    /// <summary>
    /// Training is stopped because too much data was dropped. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INVALID_DATA_TOLERANCE_EXCEEDED")] ModelTrainingInvalidDataToleranceExceeded = 21119,
    [pbr::OriginalName("MODEL_MODIFY_SUCCESS")] ModelModifySuccess = 21150,
    [pbr::OriginalName("MODEL_MODIFY_PENDING")] ModelModifyPending = 21151,
    [pbr::OriginalName("MODEL_MODIFY_FAILED")] ModelModifyFailed = 21152,
    [pbr::OriginalName("MODEL_DOES_NOT_EXIST")] ModelDoesNotExist = 21200,
    [pbr::OriginalName("MODEL_PERMISSION_DENIED")] ModelPermissionDenied = 21201,
    [pbr::OriginalName("MODEL_INVALID_ARGUMENT")] ModelInvalidArgument = 21202,
    [pbr::OriginalName("MODEL_INVALID_REQUEST")] ModelInvalidRequest = 21203,
    [pbr::OriginalName("MODEL_EVALUATED")] ModelEvaluated = 21300,
    [pbr::OriginalName("MODEL_EVALUATING")] ModelEvaluating = 21301,
    [pbr::OriginalName("MODEL_NOT_EVALUATED")] ModelNotEvaluated = 21302,
    [pbr::OriginalName("MODEL_QUEUED_FOR_EVALUATION")] ModelQueuedForEvaluation = 21303,
    /// <summary>
    /// Evaluation took longer than hard coded timeouts. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_TIMED_OUT")] ModelEvaluationTimedOut = 21310,
    /// <summary>
    /// Evaluation got error waiting on asset pipeline to finish.FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_WAITING_ERROR")] ModelEvaluationWaitingError = 21311,
    /// <summary>
    /// EVALUATION THREW AN UNKNOWN EXCEPTION.
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_UNKNOWN_ERROR")] ModelEvaluationUnknownError = 21312,
    [pbr::OriginalName("MODEL_PREDICTION_FAILED")] ModelPredictionFailed = 21313,
    /// <summary>
    /// Eval message was redelivered. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_MSG_REDELIVER")] ModelEvaluationMsgRedeliver = 21314,
    /// <summary>
    /// Don't have enough concepts labelled to perform evaluation. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_NEED_LABELS")] ModelEvaluationNeedLabels = 21315,
    /// <summary>
    /// Don't have enough inputs per concept to perform evaluation. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_NEED_INPUTS")] ModelEvaluationNeedInputs = 21316,
    /// <summary>
    /// Generic err code for eval failure.
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_FAILED")] ModelEvaluationFailed = 21317,
    /// <summary>
    /// Used when inference coordinator failed to deploy spire and throws an error
    /// </summary>
    [pbr::OriginalName("MODEL_DEPLOYMENT_FAILED")] ModelDeploymentFailed = 21350,
    /// <summary>
    /// Used when calling the inference coordinator to deploy a spire
    /// </summary>
    [pbr::OriginalName("MODEL_DEPLOYING")] ModelDeploying = 21351,
    /// <summary>
    /// Used when training is completed
    /// </summary>
    [pbr::OriginalName("MODEL_QUEUED_FOR_DEPLOYMENT")] ModelQueuedForDeployment = 21352,
    /// <summary>
    /// Used when model spire deployment is manually taken down or due to inactivity
    /// </summary>
    [pbr::OriginalName("MODEL_NOT_DEPLOYED")] ModelNotDeployed = 21353,
    /// <summary>
    /// Used when a model reference field is not set properly
    /// </summary>
    [pbr::OriginalName("MODEL_REFERENCE_INVALID_ARGUMENT")] ModelReferenceInvalidArgument = 21400,
    /// <summary>
    /// Used when a model example input field is not set properly
    /// </summary>
    [pbr::OriginalName("MODEL_EXAMPLE_INPUT_INVALID_ARGUMENT")] ModelExampleInputInvalidArgument = 21420,
    /// <summary>
    /// specified model input not in workflow
    /// </summary>
    [pbr::OriginalName("WORKFLOW_NO_MATCHING_INPUT")] WorkflowNoMatchingInput = 22001,
    /// <summary>
    /// specified model must be trained
    /// </summary>
    [pbr::OriginalName("WORKFLOW_REQUIRE_TRAINED_MODEL")] WorkflowRequireTrainedModel = 22002,
    [pbr::OriginalName("WORKFLOW_DUPLICATE")] WorkflowDuplicate = 22100,
    [pbr::OriginalName("WORKFLOW_UNSUPPORTED_FORMAT")] WorkflowUnsupportedFormat = 22101,
    [pbr::OriginalName("WORKFLOW_DOES_NOT_EXIST")] WorkflowDoesNotExist = 22102,
    [pbr::OriginalName("WORKFLOW_PERMISSION_DENIED")] WorkflowPermissionDenied = 22103,
    /// <summary>
    /// error in the request somewhere
    /// </summary>
    [pbr::OriginalName("WORKFLOW_INVALID_ARGUMENT")] WorkflowInvalidArgument = 22104,
    [pbr::OriginalName("WORKFLOW_INVALID_RECIPE")] WorkflowInvalidRecipe = 22105,
    [pbr::OriginalName("WORKFLOW_INVALID_TEMPLATE")] WorkflowInvalidTemplate = 22106,
    [pbr::OriginalName("WORKFLOW_INVALID_GRAPH")] WorkflowInvalidGraph = 22107,
    [pbr::OriginalName("WORKFLOW_INTERNAL_FAILURE")] WorkflowInternalFailure = 22108,
    /// <summary>
    /// error in the request somewhere
    /// </summary>
    [pbr::OriginalName("WORKFLOW_INVALID_REQUEST")] WorkflowInvalidRequest = 22999,
    [pbr::OriginalName("WORKFLOW_MODIFY_SUCCESS")] WorkflowModifySuccess = 22150,
    [pbr::OriginalName("WORKFLOW_MODIFY_PENDING")] WorkflowModifyPending = 22151,
    [pbr::OriginalName("WORKFLOW_MODIFY_FAILED")] WorkflowModifyFailed = 22152,
    [pbr::OriginalName("WORKFLOW_REINDEX_FAILED")] WorkflowReindexFailed = 22153,
    /// <summary>
    /// Concept related 23xxx
    /// </summary>
    [pbr::OriginalName("CONCEPT_MODIFY_SUCCESS")] ConceptModifySuccess = 23150,
    [pbr::OriginalName("CONCEPT_MODIFY_PENDING")] ConceptModifyPending = 23151,
    [pbr::OriginalName("CONCEPT_MODIFY_FAILED")] ConceptModifyFailed = 23152,
    /// <summary>
    /// Annotation related 24xxx
    /// </summary>
    [pbr::OriginalName("ANNOTATION_SUCCESS")] AnnotationSuccess = 24150,
    [pbr::OriginalName("ANNOTATION_PENDING")] AnnotationPending = 24151,
    [pbr::OriginalName("ANNOTATION_FAILED")] AnnotationFailed = 24152,
    [pbr::OriginalName("ANNOTATION_UNKNOWN_STATUS")] AnnotationUnknownStatus = 24154,
    [pbr::OriginalName("ANNOTATION_INVALID_ARGUMENT")] AnnotationInvalidArgument = 24155,
    [pbr::OriginalName("ANNOTATION_PERMISSION_DENIED")] AnnotationPermissionDenied = 24156,
    [pbr::OriginalName("ANNOTATION_AWAITING_REVIEW")] AnnotationAwaitingReview = 24157,
    [pbr::OriginalName("ANNOTATION_AWAITING_CONSENSUS_REVIEW")] AnnotationAwaitingConsensusReview = 24159,
    [pbr::OriginalName("ANNOTATION_REVIEW_DENIED")] AnnotationReviewDenied = 24158,
    [pbr::OriginalName("ANNOTATION_MODIFY_SUCCESS")] AnnotationModifySuccess = 24250,
    [pbr::OriginalName("ANNOTATION_MODIFY_PENDING")] AnnotationModifyPending = 24251,
    [pbr::OriginalName("ANNOTATION_MODIFY_FAILED")] AnnotationModifyFailed = 24252,
    /// <summary>
    /// Metadata related 249xx
    /// </summary>
    [pbr::OriginalName("METADATA_INVALID_PATCH_ARGUMENTS")] MetadataInvalidPatchArguments = 24900,
    [pbr::OriginalName("METADATA_PARSING_ISSUE")] MetadataParsingIssue = 24901,
    [pbr::OriginalName("METADATA_MANIPULATION_ISSUE")] MetadataManipulationIssue = 24902,
    /// <summary>
    /// Training service related 25xxx
    /// </summary>
    [pbr::OriginalName("TRAINER_JOB_STATE_NONE")] TrainerJobStateNone = 25000,
    [pbr::OriginalName("TRAINER_JOB_STATE_QUEUED")] TrainerJobStateQueued = 25001,
    [pbr::OriginalName("TRAINER_JOB_STATE_RUNNING")] TrainerJobStateRunning = 25002,
    [pbr::OriginalName("TRAINER_JOB_STATE_COMPLETE")] TrainerJobStateComplete = 25003,
    [pbr::OriginalName("TRAINER_JOB_STATE_ERROR")] TrainerJobStateError = 25004,
    /// <summary>
    /// Data Dump related 251xx
    /// </summary>
    [pbr::OriginalName("DATA_DUMP_SUCCESS")] DataDumpSuccess = 25150,
    [pbr::OriginalName("DATA_DUMP_PENDING")] DataDumpPending = 25151,
    [pbr::OriginalName("DATA_DUMP_FAILED")] DataDumpFailed = 25152,
    [pbr::OriginalName("DATA_DUMP_IN_PROGRESS")] DataDumpInProgress = 25153,
    /// <summary>
    /// DEPRECATED: Not used anymore. Now for an empty data dump, DATA_DUMP_SUCCESS is returned. To detect an empty data dump, check if the inptus count is 0.
    /// </summary>
    [pbr::OriginalName("DATA_DUMP_NO_DATA")] DataDumpNoData = 25154,
    [pbr::OriginalName("DATA_DUMP_UNEXPECTED_ERROR")] DataDumpUnexpectedError = 25155,
    [pbr::OriginalName("DATA_DUMP_EXPORT_SUCCESS")] DataDumpExportSuccess = 25170,
    [pbr::OriginalName("DATA_DUMP_EXPORT_PENDING")] DataDumpExportPending = 25171,
    [pbr::OriginalName("DATA_DUMP_EXPORT_FAILED")] DataDumpExportFailed = 25172,
    [pbr::OriginalName("DATA_DUMP_EXPORT_IN_PROGRESS")] DataDumpExportInProgress = 25173,
    [pbr::OriginalName("DATA_DUMP_EXPORT_UNEXPECTED_ERROR")] DataDumpExportUnexpectedError = 25174,
    /// <summary>
    /// Duplicate related 252xx
    /// </summary>
    [pbr::OriginalName("APP_DUPLICATION_SUCCESS")] AppDuplicationSuccess = 25200,
    [pbr::OriginalName("APP_DUPLICATION_FAILED")] AppDuplicationFailed = 25201,
    [pbr::OriginalName("APP_DUPLICATION_PENDING")] AppDuplicationPending = 25202,
    [pbr::OriginalName("APP_DUPLICATION_IN_PROGRESS")] AppDuplicationInProgress = 25203,
    [pbr::OriginalName("APP_DUPLICATION_INVALID_REQUEST")] AppDuplicationInvalidRequest = 25204,
    /// <summary>
    /// Module related codes 253xx
    /// </summary>
    [pbr::OriginalName("MODULE_DOES_NOT_EXIST")] ModuleDoesNotExist = 25300,
    [pbr::OriginalName("MODULE_PERMISSION_DENIED")] ModulePermissionDenied = 25301,
    [pbr::OriginalName("MODULE_INVALID_ARGUMENT")] ModuleInvalidArgument = 25302,
    [pbr::OriginalName("MODULE_INVALID_REQUEST")] ModuleInvalidRequest = 25303,
    /// <summary>
    /// Bulk Operation related codes 254xx
    /// </summary>
    [pbr::OriginalName("BULK_OPERATION_SUCCESS")] BulkOperationSuccess = 25400,
    [pbr::OriginalName("BULK_OPERATION_FAILED")] BulkOperationFailed = 25401,
    [pbr::OriginalName("BULK_OPERATION_PENDING")] BulkOperationPending = 25402,
    [pbr::OriginalName("BULK_OPERATION_IN_PROGRESS")] BulkOperationInProgress = 25403,
    [pbr::OriginalName("BULK_OPERATION_INVALID_REQUEST")] BulkOperationInvalidRequest = 25404,
    [pbr::OriginalName("BULK_OPERATION_CANCELLED")] BulkOperationCancelled = 25405,
    [pbr::OriginalName("BULK_OPERATION_UNEXPECTED_ERROR")] BulkOperationUnexpectedError = 25406,
    /// <summary>
    /// Runner related codes 256xx
    /// </summary>
    [pbr::OriginalName("RUNNER_DOES_NOT_EXIST")] RunnerDoesNotExist = 25600,
    [pbr::OriginalName("RUNNER_PERMISSION_DENIED")] RunnerPermissionDenied = 25601,
    [pbr::OriginalName("RUNNER_INVALID_ARGUMENT")] RunnerInvalidArgument = 25602,
    [pbr::OriginalName("RUNNER_INVALID_REQUEST")] RunnerInvalidRequest = 25603,
    [pbr::OriginalName("RUNNER_NEEDS_RETRY")] RunnerNeedsRetry = 25604,
    /// <summary>
    /// Input:Image related 30xxx
    /// </summary>
    [pbr::OriginalName("INPUT_DOWNLOAD_SUCCESS")] InputDownloadSuccess = 30000,
    /// <summary>
    /// when things are async, this is the default status.
    /// </summary>
    [pbr::OriginalName("INPUT_DOWNLOAD_PENDING")] InputDownloadPending = 30001,
    /// <summary>
    /// any type of error downloading and processing
    /// </summary>
    [pbr::OriginalName("INPUT_DOWNLOAD_FAILED")] InputDownloadFailed = 30002,
    [pbr::OriginalName("INPUT_DOWNLOAD_IN_PROGRESS")] InputDownloadInProgress = 30003,
    [pbr::OriginalName("INPUT_STATUS_UPDATE_FAILED")] InputStatusUpdateFailed = 30004,
    [pbr::OriginalName("INPUT_DELETE_FAILED")] InputDeleteFailed = 30005,
    [pbr::OriginalName("INPUT_DUPLICATE")] InputDuplicate = 30100,
    [pbr::OriginalName("INPUT_UNSUPPORTED_FORMAT")] InputUnsupportedFormat = 30101,
    [pbr::OriginalName("INPUT_DOES_NOT_EXIST")] InputDoesNotExist = 30102,
    [pbr::OriginalName("INPUT_PERMISSION_DENIED")] InputPermissionDenied = 30103,
    [pbr::OriginalName("INPUT_INVALID_ARGUMENT")] InputInvalidArgument = 30104,
    [pbr::OriginalName("INPUT_OVER_LIMIT")] InputOverLimit = 30105,
    [pbr::OriginalName("INPUT_INVALID_URL")] InputInvalidUrl = 30106,
    [pbr::OriginalName("INPUT_MODIFY_SUCCESS")] InputModifySuccess = 30200,
    [pbr::OriginalName("INPUT_MODIFY_PENDING")] InputModifyPending = 30201,
    [pbr::OriginalName("INPUT_MODIFY_FAILED")] InputModifyFailed = 30203,
    [pbr::OriginalName("INPUT_STORAGE_HOST_FAILED")] InputStorageHostFailed = 30210,
    [pbr::OriginalName("ALL_INPUT_INVALID_BYTES")] AllInputInvalidBytes = 30300,
    [pbr::OriginalName("INPUT_CLUSTER_SUCCESS")] InputClusterSuccess = 30400,
    [pbr::OriginalName("INPUT_CLUSTER_PENDING")] InputClusterPending = 30401,
    [pbr::OriginalName("INPUT_CLUSTER_FAILED")] InputClusterFailed = 30402,
    [pbr::OriginalName("INPUT_CLUSTER_IN_PROGRESS")] InputClusterInProgress = 30403,
    [pbr::OriginalName("INPUT_REINDEX_SUCCESS")] InputReindexSuccess = 30500,
    [pbr::OriginalName("INPUT_REINDEX_PENDING")] InputReindexPending = 30501,
    [pbr::OriginalName("INPUT_REINDEX_FAILED")] InputReindexFailed = 30502,
    [pbr::OriginalName("INPUT_REINDEX_IN_PROGRESS")] InputReindexInProgress = 30503,
    /// <summary>
    /// Input:Video related 31xxx -- Deprecated
    /// </summary>
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_SUCCESS")] InputVideoDownloadSuccess = 31000,
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_PENDING")] InputVideoDownloadPending = 31001,
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_FAILED")] InputVideoDownloadFailed = 31002,
    [pbr::OriginalName("INPUT_VIDEO_DUPLICATE")] InputVideoDuplicate = 31100,
    [pbr::OriginalName("INPUT_VIDEO_UNSUPPORTED_FORMAT")] InputVideoUnsupportedFormat = 31101,
    [pbr::OriginalName("INPUT_VIDEO_DOES_NOT_EXIST")] InputVideoDoesNotExist = 31102,
    [pbr::OriginalName("INPUT_VIDEO_PERMISSION_DENIED")] InputVideoPermissionDenied = 31103,
    [pbr::OriginalName("INPUT_VIDEO_INVALID_ARGUMENT")] InputVideoInvalidArgument = 31104,
    [pbr::OriginalName("INPUT_VIDEO_OVER_LIMIT")] InputVideoOverLimit = 31105,
    [pbr::OriginalName("INPUT_VIDEO_INVALID_URL")] InputVideoInvalidUrl = 31106,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_SUCCESS")] InputVideoModifySuccess = 31200,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_PENDING")] InputVideoModifyPending = 31201,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_FAILED")] InputVideoModifyFailed = 31203,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_HOST_FAILED")] InputVideoStorageHostFailed = 31210,
    [pbr::OriginalName("ALL_INPUT_VIDEOS_INVALID_BYTES")] AllInputVideosInvalidBytes = 31300,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_SUCCESS")] InputVideoProcessingSuccess = 31400,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_PENDING")] InputVideoProcessingPending = 31410,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_FAILED")] InputVideoProcessingFailed = 31420,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_INCONSISTENCY")] InputVideoStorageInconsistency = 31430,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_FAILURE")] InputVideoStorageFailure = 31440,
    [pbr::OriginalName("INPUT_VIDEO_URL_GENERATION_FAILURE")] InputVideoUrlGenerationFailure = 31450,
    [pbr::OriginalName("INPUT_CONNECTION_FAILED")] InputConnectionFailed = 39996,
    [pbr::OriginalName("REQUEST_DISABLED_FOR_MAINTENANCE")] RequestDisabledForMaintenance = 39997,
    /// <summary>
    /// deprecate this one. Use REQUEST_DISABLED_FOR_MAINTENANCE
    /// </summary>
    [pbr::OriginalName("INPUT_WRITES_DISABLED_FOR_MAINTENANCE")] InputWritesDisabledForMaintenance = 39998,
    [pbr::OriginalName("INPUT_INVALID_REQUEST")] InputInvalidRequest = 39999,
    /// <summary>
    /// API formatting issues 4000x
    /// </summary>
    [pbr::OriginalName("PREDICT_INVALID_REQUEST")] PredictInvalidRequest = 40001,
    [pbr::OriginalName("SEARCH_INVALID_REQUEST")] SearchInvalidRequest = 40002,
    [pbr::OriginalName("CONCEPTS_INVALID_REQUEST")] ConceptsInvalidRequest = 40003,
    [pbr::OriginalName("STATS_INVALID_REQUEST")] StatsInvalidRequest = 40004,
    /// <summary>
    /// Other related 400xx
    /// </summary>
    [pbr::OriginalName("DATABASE_DUPLICATE_KEY")] DatabaseDuplicateKey = 40010,
    [pbr::OriginalName("DATABASE_STATEMENT_TIMEOUT")] DatabaseStatementTimeout = 40011,
    [pbr::OriginalName("DATABASE_INVALID_ROWS_AFFECTED")] DatabaseInvalidRowsAffected = 40012,
    [pbr::OriginalName("DATABASE_DEADLOCK_DETECTED")] DatabaseDeadlockDetected = 40013,
    [pbr::OriginalName("DATABASE_FAIL_TASK")] DatabaseFailTask = 40014,
    [pbr::OriginalName("DATABASE_FAIL_TO_GET_CONNECTIONS")] DatabaseFailToGetConnections = 40015,
    [pbr::OriginalName("DATABASE_TOO_MANY_CLIENTS")] DatabaseTooManyClients = 40016,
    [pbr::OriginalName("DATABASE_CONSTRAINT_VIOLATED")] DatabaseConstraintViolated = 40017,
    [pbr::OriginalName("DATABASE_CANCELED")] DatabaseCanceled = 40021,
    [pbr::OriginalName("ASYNC_WORKER_MULTI_ERRORS")] AsyncWorkerMultiErrors = 40020,
    [pbr::OriginalName("RPC_REQUEST_QUEUE_FULL")] RpcRequestQueueFull = 40030,
    [pbr::OriginalName("RPC_SERVER_UNAVAILABLE")] RpcServerUnavailable = 40031,
    [pbr::OriginalName("RPC_REQUEST_TIMEOUT")] RpcRequestTimeout = 40032,
    [pbr::OriginalName("RPC_MAX_MESSAGE_SIZE_EXCEEDED")] RpcMaxMessageSizeExceeded = 40033,
    [pbr::OriginalName("RPC_CANCELED")] RpcCanceled = 40035,
    [pbr::OriginalName("RPC_UNKNOWN_METHOD")] RpcUnknownMethod = 40036,
    [pbr::OriginalName("REQUEST_CANCELED_BY_USER")] RequestCanceledByUser = 40037,
    [pbr::OriginalName("CLUSTER_INTERNAL_FAILURE")] ClusterInternalFailure = 43040,
    /// <summary>
    /// could not connect to external services
    /// </summary>
    [pbr::OriginalName("EXTERNAL_CONNECTION_ERROR")] ExternalConnectionError = 40034,
    [pbr::OriginalName("QUERY_INVALID_SYNTAX")] QueryInvalidSyntax = 40050,
    /// <summary>
    /// Queue related errors 41xxx
    /// </summary>
    [pbr::OriginalName("QUEUE_CONN_ERROR")] QueueConnError = 41000,
    [pbr::OriginalName("QUEUE_CLOSE_REQUEST_TIMEOUT")] QueueCloseRequestTimeout = 41002,
    [pbr::OriginalName("QUEUE_CONN_CLOSED")] QueueConnClosed = 41003,
    [pbr::OriginalName("QUEUE_PUBLISH_ACK_TIMEOUT")] QueuePublishAckTimeout = 41004,
    [pbr::OriginalName("QUEUE_PUBLISH_ERROR")] QueuePublishError = 41005,
    [pbr::OriginalName("QUEUE_SUBSCRIPTION_TIMEOUT")] QueueSubscriptionTimeout = 41006,
    [pbr::OriginalName("QUEUE_SUBSCRIPTION_ERROR")] QueueSubscriptionError = 41007,
    [pbr::OriginalName("QUEUE_MARSHALLING_FAILED")] QueueMarshallingFailed = 41008,
    [pbr::OriginalName("QUEUE_UNMARSHALLING_FAILED")] QueueUnmarshallingFailed = 41009,
    [pbr::OriginalName("QUEUE_MAX_MSG_REDELIVERY_EXCEEDED")] QueueMaxMsgRedeliveryExceeded = 41010,
    [pbr::OriginalName("QUEUE_ACK_FAILURE")] QueueAckFailure = 41011,
    /// <summary>
    /// SQS related errors 411xx
    /// </summary>
    [pbr::OriginalName("SQS_OVERLIMIT")] SqsOverlimit = 41100,
    [pbr::OriginalName("SQS_INVALID_RECEIPT_HANDLE")] SqsInvalidReceiptHandle = 41101,
    [pbr::OriginalName("SQS_UNKNOWN")] SqsUnknown = 41102,
    /// <summary>
    ///Search related errors 43xxxx
    /// </summary>
    [pbr::OriginalName("SEARCH_INTERNAL_FAILURE")] SearchInternalFailure = 43001,
    [pbr::OriginalName("SEARCH_PROJECTION_FAILURE")] SearchProjectionFailure = 43002,
    [pbr::OriginalName("SEARCH_PREDICTION_FAILURE")] SearchPredictionFailure = 43003,
    [pbr::OriginalName("SEARCH_BY_NOT_FULLY_INDEXED_INPUT")] SearchByNotFullyIndexedInput = 43004,
    [pbr::OriginalName("SAVED_SEARCH_MODIFY_FAILED")] SavedSearchModifyFailed = 43005,
    [pbr::OriginalName("SEARCH_COUNTS_UNAVAILABLE")] SearchCountsUnavailable = 43006,
    /// <summary>
    /// Workflow evaluation err code
    /// </summary>
    [pbr::OriginalName("EVALUATION_QUEUED")] EvaluationQueued = 43100,
    [pbr::OriginalName("EVALUATION_IN_PROGRESS")] EvaluationInProgress = 43101,
    [pbr::OriginalName("EVALUATION_SUCCESS")] EvaluationSuccess = 43102,
    [pbr::OriginalName("EVALUATION_FAILED_TO_RETRIEVE_DATA")] EvaluationFailedToRetrieveData = 43103,
    [pbr::OriginalName("EVALUATION_INVALID_ARGUMENT")] EvaluationInvalidArgument = 43104,
    [pbr::OriginalName("EVALUATION_FAILED")] EvaluationFailed = 43105,
    [pbr::OriginalName("EVALUATION_PENDING")] EvaluationPending = 43106,
    [pbr::OriginalName("EVALUATION_TIMED_OUT")] EvaluationTimedOut = 43107,
    [pbr::OriginalName("EVALUATION_UNEXPECTED_ERROR")] EvaluationUnexpectedError = 43108,
    [pbr::OriginalName("EVALUATION_MIXED")] EvaluationMixed = 43109,
    /// <summary>
    /// Stripe 44xxx
    /// </summary>
    [pbr::OriginalName("STRIPE_EVENT_ERROR")] StripeEventError = 44001,
    /// <summary>
    /// Redis/Cache 45xxx
    /// </summary>
    [pbr::OriginalName("CACHE_MISS")] CacheMiss = 45001,
    [pbr::OriginalName("REDIS_SCRIPT_EXITED_WITH_FAILURE")] RedisScriptExitedWithFailure = 45002,
    [pbr::OriginalName("REDIS_STREAM_ERR")] RedisStreamErr = 45003,
    [pbr::OriginalName("REDIS_NO_CONSUMERS")] RedisNoConsumers = 45004,
    [pbr::OriginalName("REDIS_STREAM_BACKOFF")] RedisStreamBackoff = 45005,
    /// <summary>
    /// Sift Science 46xxx
    /// </summary>
    [pbr::OriginalName("SIGNUP_EVENT_ERROR")] SignupEventError = 46001,
    [pbr::OriginalName("SIGNUP_FLAGGED")] SignupFlagged = 46002,
    [pbr::OriginalName("FILETYPE_UNSUPPORTED")] FiletypeUnsupported = 46003,
    /// <summary>
    /// Application counts related errors 470xx
    /// </summary>
    [pbr::OriginalName("APP_COUNT_INVALID_MESSAGE")] AppCountInvalidMessage = 47001,
    [pbr::OriginalName("APP_COUNT_UPDATE_INCREMENT_FAILED")] AppCountUpdateIncrementFailed = 47002,
    [pbr::OriginalName("APP_COUNT_REBUILD_FAILED")] AppCountRebuildFailed = 47003,
    [pbr::OriginalName("APP_COUNT_INTERNAL_FAILURE")] AppCountInternalFailure = 47004,
    /// <summary>
    /// Media processor related errors 471xx -- DEPRECATED
    /// </summary>
    [pbr::OriginalName("MP_DOWNLOAD_ERROR")] MpDownloadError = 47101,
    [pbr::OriginalName("MP_RESOLVE_DNS_ERROR")] MpResolveDnsError = 47102,
    [pbr::OriginalName("MP_DOWNLOAD_MAX_SIZE_EXCEEDED_ERROR")] MpDownloadMaxSizeExceededError = 47103,
    [pbr::OriginalName("MP_IMAGE_DECODE_ERROR")] MpImageDecodeError = 47104,
    [pbr::OriginalName("MP_INVALID_ARGUMENT")] MpInvalidArgument = 47105,
    [pbr::OriginalName("MP_IMAGE_PROCESSING_ERROR")] MpImageProcessingError = 47106,
    /// <summary>
    /// DataTier related error 472xx
    /// </summary>
    [pbr::OriginalName("DATATIER_CONN_ERROR")] DatatierConnError = 47201,
    /// <summary>
    /// User legal consent stauts related 50xxx
    /// </summary>
    [pbr::OriginalName("USER_CONSENT_FACE")] UserConsentFace = 50001,
    /// <summary>
    /// Workers 51xxx
    /// </summary>
    [pbr::OriginalName("WORKER_MISSING")] WorkerMissing = 51000,
    [pbr::OriginalName("WORKER_ACTIVE")] WorkerActive = 51001,
    [pbr::OriginalName("WORKER_INACTIVE")] WorkerInactive = 51002,
    /// <summary>
    /// Collectors 52xxx
    /// </summary>
    [pbr::OriginalName("COLLECTOR_MISSING")] CollectorMissing = 52000,
    [pbr::OriginalName("COLLECTOR_ACTIVE")] CollectorActive = 52001,
    [pbr::OriginalName("COLLECTOR_INACTIVE")] CollectorInactive = 52002,
    [pbr::OriginalName("COLLECTOR_POST_INPUT_FAILED")] CollectorPostInputFailed = 52003,
    /// <summary>
    /// SSO 53xxx
    /// </summary>
    [pbr::OriginalName("SSO_IDENTITY_PROVIDER_DOES_NOT_EXIST")] SsoIdentityProviderDoesNotExist = 53001,
    /// <summary>
    /// Tasks 54xxx
    /// The task was created.
    /// </summary>
    [pbr::OriginalName("TASK_IN_PROGRESS")] TaskInProgress = 54001,
    /// <summary>
    /// The task is completed.
    /// </summary>
    [pbr::OriginalName("TASK_DONE")] TaskDone = 54002,
    /// <summary>
    /// The task is marked as abandoned.
    /// </summary>
    [pbr::OriginalName("TASK_WONT_DO")] TaskWontDo = 54003,
    /// <summary>
    /// An error occurred during add-task-annotations or add-auto-annotations pipeline.
    /// </summary>
    [pbr::OriginalName("TASK_FAILED")] TaskFailed = 54005,
    /// <summary>
    /// When an Auto Annotation task job has finished processing its last batch and is waiting for more dataset assets.
    /// </summary>
    [pbr::OriginalName("TASK_IDLE")] TaskIdle = 54006,
    /// <summary>
    /// The task operation is in conflict with the current state of the server.
    /// </summary>
    [pbr::OriginalName("TASK_CONFLICT")] TaskConflict = 54100,
    /// <summary>
    /// Certain task-related scenarios are not implemented.
    /// </summary>
    [pbr::OriginalName("TASK_NOT_IMPLEMENTED")] TaskNotImplemented = 54101,
    /// <summary>
    /// Task was not found.
    /// </summary>
    [pbr::OriginalName("TASK_MISSING")] TaskMissing = 54102,
    /// <summary>
    /// Label Order Related Status Code 55xxx
    /// </summary>
    [pbr::OriginalName("LABEL_ORDER_PENDING")] LabelOrderPending = 55001,
    [pbr::OriginalName("LABEL_ORDER_IN_PROGRESS")] LabelOrderInProgress = 55002,
    [pbr::OriginalName("LABEL_ORDER_SUCCESS")] LabelOrderSuccess = 55003,
    [pbr::OriginalName("LABEL_ORDER_CANCELED")] LabelOrderCanceled = 55004,
    /// <summary>
    /// License Related Status Code 600xx
    /// </summary>
    [pbr::OriginalName("LICENSE_ACTIVE")] LicenseActive = 60000,
    [pbr::OriginalName("LICENSE_DOES_NOT_EXIST")] LicenseDoesNotExist = 60001,
    [pbr::OriginalName("LICENSE_NEED_UPDATE")] LicenseNeedUpdate = 60002,
    [pbr::OriginalName("LICENSE_EXPIRED")] LicenseExpired = 60003,
    [pbr::OriginalName("LICENSE_REVOKED")] LicenseRevoked = 60004,
    /// <summary>
    /// hidden state not reflected to users
    /// </summary>
    [pbr::OriginalName("LICENSE_DELETED")] LicenseDeleted = 60005,
    [pbr::OriginalName("LICENSE_VOLUME_EXCEEDED")] LicenseVolumeExceeded = 60006,
    /// <summary>
    /// Password Related Status Code
    /// </summary>
    [pbr::OriginalName("PASSWORD_VALIDATION_SUCCESS")] PasswordValidationSuccess = 61000,
    [pbr::OriginalName("PASSWORD_VALIDATION_FAILED")] PasswordValidationFailed = 61001,
    [pbr::OriginalName("PASSWORDPOLICY_INVALID_ARGUMENT")] PasswordpolicyInvalidArgument = 61002,
    /// <summary>
    /// Feature flags status code
    /// </summary>
    [pbr::OriginalName("FEATUREFLAG_CONFIG_NOT_FOUND")] FeatureflagConfigNotFound = 62000,
    [pbr::OriginalName("FEATUREFLAG_INVALID_ARGUMENT")] FeatureflagInvalidArgument = 62001,
    [pbr::OriginalName("FEATUREFLAG_BLOCKED")] FeatureflagBlocked = 62002,
    /// <summary>
    /// Maintenance status code
    /// </summary>
    [pbr::OriginalName("MAINTENANCE_SUCCESS")] MaintenanceSuccess = 63000,
    [pbr::OriginalName("MAINTENANCE_FAILED")] MaintenanceFailed = 63001,
    /// <summary>
    /// Datasets 64xxx
    /// The dataset version is pending to be processed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_PENDING")] DatasetVersionPending = 64005,
    /// <summary>
    /// The dataset version is currently being processed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_IN_PROGRESS")] DatasetVersionInProgress = 64010,
    /// <summary>
    /// The dataset version is ready to be used.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_READY")] DatasetVersionReady = 64015,
    /// <summary>
    /// An error occurred during the dataset version processing.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_FAILURE")] DatasetVersionFailure = 64020,
    /// <summary>
    /// An unexpected error occurred during the dataset version processing.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_UNEXPECTED_ERROR")] DatasetVersionUnexpectedError = 64025,
    /// <summary>
    /// An alteration to dataset version would create a conflict
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_CONFLICT")] DatasetVersionConflict = 64030,
    /// <summary>
    /// The dataset input was successfully added.
    /// </summary>
    [pbr::OriginalName("DATASET_INPUT_SUCCESS")] DatasetInputSuccess = 64100,
    /// <summary>
    /// The dataset input is a duplicate.
    /// Deprecated: Unused.
    /// </summary>
    [pbr::OriginalName("DATASET_INPUT_DUPLICATE")] DatasetInputDuplicate = 64101,
    /// <summary>
    /// The dataset version export is completed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_SUCCESS")] DatasetVersionExportSuccess = 64200,
    /// <summary>
    /// The dataset version is pending to be exported.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_PENDING")] DatasetVersionExportPending = 64201,
    /// <summary>
    /// An error occurred during the dataset version export.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_FAILED")] DatasetVersionExportFailed = 64202,
    /// <summary>
    /// The dataset version is currently being exported.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_IN_PROGRESS")] DatasetVersionExportInProgress = 64203,
    /// <summary>
    /// An unexpected error occurred during the dataset version export.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_UNEXPECTED_ERROR")] DatasetVersionExportUnexpectedError = 64204,
    /// <summary>
    /// Generic Job status codes
    /// </summary>
    [pbr::OriginalName("JOB_QUEUED")] JobQueued = 64000,
    [pbr::OriginalName("JOB_RUNNING")] JobRunning = 64001,
    [pbr::OriginalName("JOB_COMPLETED")] JobCompleted = 64002,
    [pbr::OriginalName("JOB_FAILED")] JobFailed = 64003,
    [pbr::OriginalName("JOB_CANCELLED")] JobCancelled = 64004,
    [pbr::OriginalName("JOB_UNEXPECTED_ERROR")] JobUnexpectedError = 64006,
    [pbr::OriginalName("JOB_CONFLICT")] JobConflict = 64007,
    /// <summary>
    ///auth issues
    /// </summary>
    [pbr::OriginalName("AUTH_MISSING_IDP_ASSOC")] AuthMissingIdpAssoc = 65000,
    [pbr::OriginalName("LIST_OBJECTS_FAILED")] ListObjectsFailed = 66000,
    [pbr::OriginalName("ARCHIVE_EXTRACT_FAILED")] ArchiveExtractFailed = 67000,
    /// <summary>
    /// Multipart uploading status codes
    /// </summary>
    [pbr::OriginalName("UPLOAD_IN_PROGRESS")] UploadInProgress = 68000,
    [pbr::OriginalName("UPLOAD_DONE")] UploadDone = 68001,
    [pbr::OriginalName("UPLOAD_FAILED")] UploadFailed = 68002,
    [pbr::OriginalName("UPLOAD_UNEXPECTED_ERROR")] UploadUnexpectedError = 68003,
    [pbr::OriginalName("UPLOAD_EXPIRED")] UploadExpired = 68004,
    [pbr::OriginalName("UPLOAD_CANCELED")] UploadCanceled = 68005,
    [pbr::OriginalName("UPLOAD_CONFLICT")] UploadConflict = 68006,
    /// <summary>
    /// Billing related issues: 69xxx
    /// </summary>
    [pbr::OriginalName("BILLING_INVALID_INFO")] BillingInvalidInfo = 69000,
    /// <summary>
    /// Internal issues: 98xxx
    /// </summary>
    [pbr::OriginalName("INTERNAL_SERVER_ISSUE")] InternalServerIssue = 98004,
    [pbr::OriginalName("INTERNAL_FETCHING_ISSUE")] InternalFetchingIssue = 98005,
    [pbr::OriginalName("INTERNAL_DATABASE_ISSUE")] InternalDatabaseIssue = 98006,
    [pbr::OriginalName("INTERNAL_CONTEXT_CANCELED")] InternalContextCanceled = 98008,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_TIMEOUT")] InternalUnexpectedTimeout = 98009,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_V1")] InternalUnexpectedV1 = 98010,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_PANIC")] InternalUnexpectedPanic = 98011,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_SPIRE")] InternalUnexpectedSpire = 98012,
    [pbr::OriginalName("INTERNAL_REDIS_UNAVAILABLE")] InternalRedisUnavailable = 98013,
    [pbr::OriginalName("INTERNAL_RESOURCE_EXHAUSTED")] InternalResourceExhausted = 98014,
    [pbr::OriginalName("INTERNAL_REDIS_UNCATEGORIZED")] InternalRedisUncategorized = 98015,
    [pbr::OriginalName("INTERNAL_AWS_UNCATEGORIZED")] InternalAwsUncategorized = 98016,
    [pbr::OriginalName("INTERNAL_AZURE_UNCATEGORIZED")] InternalAzureUncategorized = 98017,
    /// <summary>
    /// Uncategorized: 99xxx: move off as soon as known
    /// </summary>
    [pbr::OriginalName("CONN_UNCATEGORIZED")] ConnUncategorized = 99001,
    [pbr::OriginalName("MODEL_UNCATEGORIZED")] ModelUncategorized = 99002,
    [pbr::OriginalName("INPUT_UNCATEGORIZED")] InputUncategorized = 99003,
    [pbr::OriginalName("ANNOTATION_UNCATEGORIZED")] AnnotationUncategorized = 99004,
    [pbr::OriginalName("BILLING_UNCATEGORIZED")] BillingUncategorized = 99005,
    [pbr::OriginalName("INTERNAL_UNCATEGORIZED")] InternalUncategorized = 99009,
    /// <summary>
    /// Deprecated: migrate off to one of the internal issues
    /// </summary>
    [pbr::OriginalName("BAD_REQUEST")] BadRequest = 90400,
    /// <summary>
    /// Deprecated: migrate off to one of the internal issues
    /// </summary>
    [pbr::OriginalName("SERVER_ERROR")] ServerError = 90500,
  }

  #endregion

}

#endregion Designer generated code
