// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/status/status_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Api.Status {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/status/status_code.proto</summary>
  public static partial class StatusCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/status/status_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatusCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Citwcm90by9jbGFyaWZhaS9hcGkvc3RhdHVzL3N0YXR1c19jb2RlLnByb3Rv",
            "EhNjbGFyaWZhaS5hcGkuc3RhdHVzKslmCgpTdGF0dXNDb2RlEggKBFpFUk8Q",
            "ABIMCgdTVUNDRVNTEJBOEhEKDE1JWEVEX1NUQVRVUxCaThIMCgdGQUlMVVJF",
            "EKROEg4KCVRSWV9BR0FJThCuThIUCg9OT1RfSU1QTEVNRU5URUQQuE4SCgoF",
            "TU9WRUQQwk4SCwoGVEVBUE9UEMxOEg0KCEFDQ0VQVEVEENZOEhgKE0NPTk5f",
            "QUNDT1VOVF9JU1NVRVMQ+FUSGwoSQ09OTl9UT0tFTl9JTlZBTElEEPlVGgII",
            "ARIdChhDT05OX0NSRURFTlRJQUxTX0lOVkFMSUQQ+lUSHQoYQ09OTl9FWENF",
            "RURfSE9VUkxZX0xJTUlUEPtVEh4KGUNPTk5fRVhDRUVEX01PTlRITFlfTElN",
            "SVQQ/FUSEwoOQ09OTl9USFJPVFRMRUQQ/VUSGAoTQ09OTl9FWENFRURTX0xJ",
            "TUlUUxD+VRIdChhDT05OX0lOU1VGRklDSUVOVF9TQ09QRVMQ/1USFQoQQ09O",
            "Tl9LRVlfSU5WQUxJRBCAVhIXChJDT05OX0tFWV9OT1RfRk9VTkQQgVYSHAoX",
            "Q09OTl9CQURfUkVRVUVTVF9GT1JNQVQQ3FYSGAoTQ09OTl9ET0VTX05PVF9F",
            "WElTVBDdVhIZChRDT05OX0lOVkFMSURfUkVRVUVTVBDeVhIcChdDT05OX01F",
            "VEhPRF9OT1RfQUxMT1dFRBDfVhIZChRDT05OX05PX0dEUFJfQ09OU0VOVBDg",
            "VhIXChJDT05OX0lOVkFMSURfUkFOR0UQ4VYSHgoZQ09OTl9BVVRIX01FVEhP",
            "RF9ESVNBQkxFRBDAVxITCg1NT0RFTF9UUkFJTkVEEOykARIUCg5NT0RFTF9U",
            "UkFJTklORxDtpAESFQoPTU9ERUxfVU5UUkFJTkVEEO6kARIfChlNT0RFTF9R",
            "VUVVRURfRk9SX1RSQUlOSU5HEO+kARIVCg9NT0RFTF9VUExPQURJTkcQ8KQB",
            "EhwKFk1PREVMX1VQTE9BRElOR19GQUlMRUQQ8aQBEhsKFU1PREVMX1RSQUlO",
            "SU5HX0ZBSUxFRBDypAESFAoOTU9ERUxfQlVJTERJTkcQ86QBEhsKFU1PREVM",
            "X0JVSUxESU5HX0ZBSUxFRBD0pAESIgocTU9ERUxfQlVJTERfVU5FWFBFQ1RF",
            "RF9FUlJPUhD1pAESHAoWTU9ERUxfVFJBSU5JTkdfTk9fREFUQRD2pAESIQob",
            "TU9ERUxfVFJBSU5JTkdfTk9fUE9TSVRJVkVTEPekARIqCiRNT0RFTF9UUkFJ",
            "TklOR19PTkVfVlNfTl9TSU5HTEVfQ0xBU1MQ+KQBEh4KGE1PREVMX1RSQUlO",
            "SU5HX1RJTUVEX09VVBD5pAESIgocTU9ERUxfVFJBSU5JTkdfV0FJVElOR19F",
            "UlJPUhD6pAESIgocTU9ERUxfVFJBSU5JTkdfVU5LTk9XTl9FUlJPUhD7pAES",
            "JgocTU9ERUxfVFJBSU5JTkdfTVNHX1JFREVMSVZFUhD8pAEaAggBEiYKIE1P",
            "REVMX1RSQUlOSU5HX0lOU1VGRklDSUVOVF9EQVRBEP2kARIjCh1NT0RFTF9U",
            "UkFJTklOR19JTlZBTElEX1BBUkFNUxD+pAESNAouTU9ERUxfVFJBSU5JTkdf",
            "SU5WQUxJRF9EQVRBX1RPTEVSQU5DRV9FWENFRURFRBD/pAESGgoUTU9ERUxf",
            "TU9ESUZZX1NVQ0NFU1MQnqUBEhoKFE1PREVMX01PRElGWV9QRU5ESU5HEJ+l",
            "ARIZChNNT0RFTF9NT0RJRllfRkFJTEVEEKClARIaChRNT0RFTF9ET0VTX05P",
            "VF9FWElTVBDQpQESHQoXTU9ERUxfUEVSTUlTU0lPTl9ERU5JRUQQ0aUBEhwK",
            "Fk1PREVMX0lOVkFMSURfQVJHVU1FTlQQ0qUBEhsKFU1PREVMX0lOVkFMSURf",
            "UkVRVUVTVBDTpQESFQoPTU9ERUxfRVZBTFVBVEVEELSmARIWChBNT0RFTF9F",
            "VkFMVUFUSU5HELWmARIZChNNT0RFTF9OT1RfRVZBTFVBVEVEELamARIhChtN",
            "T0RFTF9RVUVVRURfRk9SX0VWQUxVQVRJT04Qt6YBEiAKGk1PREVMX0VWQUxV",
            "QVRJT05fVElNRURfT1VUEL6mARIkCh5NT0RFTF9FVkFMVUFUSU9OX1dBSVRJ",
            "TkdfRVJST1IQv6YBEiQKHk1PREVMX0VWQUxVQVRJT05fVU5LTk9XTl9FUlJP",
            "UhDApgESHQoXTU9ERUxfUFJFRElDVElPTl9GQUlMRUQQwaYBEigKHk1PREVM",
            "X0VWQUxVQVRJT05fTVNHX1JFREVMSVZFUhDCpgEaAggBEiIKHE1PREVMX0VW",
            "QUxVQVRJT05fTkVFRF9MQUJFTFMQw6YBEiIKHE1PREVMX0VWQUxVQVRJT05f",
            "TkVFRF9JTlBVVFMQxKYBEh0KF01PREVMX0VWQUxVQVRJT05fRkFJTEVEEMWm",
            "ARIdChdNT0RFTF9ERVBMT1lNRU5UX0ZBSUxFRBDmpgESFQoPTU9ERUxfREVQ",
            "TE9ZSU5HEOemARIhChtNT0RFTF9RVUVVRURfRk9SX0RFUExPWU1FTlQQ6KYB",
            "EhgKEk1PREVMX05PVF9ERVBMT1lFRBDppgESHQoXTU9ERUxfQlVTWV9QTEVB",
            "U0VfUkVUUlkQ6qYBEhMKDU1PREVMX0xPQURJTkcQ66YBEiYKIE1PREVMX1JF",
            "RkVSRU5DRV9JTlZBTElEX0FSR1VNRU5UEJinARIqCiRNT0RFTF9FWEFNUExF",
            "X0lOUFVUX0lOVkFMSURfQVJHVU1FTlQQrKcBEhQKDk1PREVMX0VYUE9SVEVE",
            "EPynARIVCg9NT0RFTF9FWFBPUlRJTkcQ/acBEhwKFk1PREVMX0VYUE9SVElO",
            "R19GQUlMRUQQ/qcBEhoKFE1PREVMX0VYUE9SVF9QRU5ESU5HEP+nARIgChpX",
            "T1JLRkxPV19OT19NQVRDSElOR19JTlBVVBDxqwESJAoeV09SS0ZMT1dfUkVR",
            "VUlSRV9UUkFJTkVEX01PREVMEPKrARIYChJXT1JLRkxPV19EVVBMSUNBVEUQ",
            "1KwBEiEKG1dPUktGTE9XX1VOU1VQUE9SVEVEX0ZPUk1BVBDVrAESHQoXV09S",
            "S0ZMT1dfRE9FU19OT1RfRVhJU1QQ1qwBEiAKGldPUktGTE9XX1BFUk1JU1NJ",
            "T05fREVOSUVEENesARIfChlXT1JLRkxPV19JTlZBTElEX0FSR1VNRU5UENis",
            "ARIdChdXT1JLRkxPV19JTlZBTElEX1JFQ0lQRRDZrAESHwoZV09SS0ZMT1df",
            "SU5WQUxJRF9URU1QTEFURRDarAESHAoWV09SS0ZMT1dfSU5WQUxJRF9HUkFQ",
            "SBDbrAESHwoZV09SS0ZMT1dfSU5URVJOQUxfRkFJTFVSRRDcrAESHgoYV09S",
            "S0ZMT1dfSU5WQUxJRF9SRVFVRVNUENezARIdChdXT1JLRkxPV19NT0RJRllf",
            "U1VDQ0VTUxCGrQESHQoXV09SS0ZMT1dfTU9ESUZZX1BFTkRJTkcQh60BEhwK",
            "FldPUktGTE9XX01PRElGWV9GQUlMRUQQiK0BEh0KF1dPUktGTE9XX1JFSU5E",
            "RVhfRkFJTEVEEImtARIcChZDT05DRVBUX01PRElGWV9TVUNDRVNTEO60ARIc",
            "ChZDT05DRVBUX01PRElGWV9QRU5ESU5HEO+0ARIbChVDT05DRVBUX01PRElG",
            "WV9GQUlMRUQQ8LQBEhgKEkFOTk9UQVRJT05fU1VDQ0VTUxDWvAESGAoSQU5O",
            "T1RBVElPTl9QRU5ESU5HENe8ARIXChFBTk5PVEFUSU9OX0ZBSUxFRBDYvAES",
            "HwoZQU5OT1RBVElPTl9VTktOT1dOX1NUQVRVUxDavAESIQobQU5OT1RBVElP",
            "Tl9JTlZBTElEX0FSR1VNRU5UENu8ARIiChxBTk5PVEFUSU9OX1BFUk1JU1NJ",
            "T05fREVOSUVEENy8ARIgChpBTk5PVEFUSU9OX0FXQUlUSU5HX1JFVklFVxDd",
            "vAESKgokQU5OT1RBVElPTl9BV0FJVElOR19DT05TRU5TVVNfUkVWSUVXEN+8",
            "ARIeChhBTk5PVEFUSU9OX1JFVklFV19ERU5JRUQQ3rwBEh8KGUFOTk9UQVRJ",
            "T05fTU9ESUZZX1NVQ0NFU1MQur0BEh8KGUFOTk9UQVRJT05fTU9ESUZZX1BF",
            "TkRJTkcQu70BEh4KGEFOTk9UQVRJT05fTU9ESUZZX0ZBSUxFRBC8vQESGwoV",
            "QU5OT1RBVElPTl9UUkFDS19JRExFEOy9ARIiChxBTk5PVEFUSU9OX1RSQUNL",
            "X0lOX1BST0dSRVNTEO29ARIeChhBTk5PVEFUSU9OX1RSQUNLX1BFTkRJTkcQ",
            "7r0BEh8KGUFOTk9UQVRJT05fVFJBQ0tfQVBQUk9WRUQQ770BEh0KF0FOTk9U",
            "QVRJT05fVFJBQ0tfRkFJTEVEEPC9ARImCiBNRVRBREFUQV9JTlZBTElEX1BB",
            "VENIX0FSR1VNRU5UUxDEwgESHAoWTUVUQURBVEFfUEFSU0lOR19JU1NVRRDF",
            "wgESIQobTUVUQURBVEFfTUFOSVBVTEFUSU9OX0lTU1VFEMbCARIcChZUUkFJ",
            "TkVSX0pPQl9TVEFURV9OT05FEKjDARIeChhUUkFJTkVSX0pPQl9TVEFURV9R",
            "VUVVRUQQqcMBEh8KGVRSQUlORVJfSk9CX1NUQVRFX1JVTk5JTkcQqsMBEiAK",
            "GlRSQUlORVJfSk9CX1NUQVRFX0NPTVBMRVRFEKvDARIdChdUUkFJTkVSX0pP",
            "Ql9TVEFURV9FUlJPUhCswwESFwoRREFUQV9EVU1QX1NVQ0NFU1MQvsQBEhcK",
            "EURBVEFfRFVNUF9QRU5ESU5HEL/EARIWChBEQVRBX0RVTVBfRkFJTEVEEMDE",
            "ARIbChVEQVRBX0RVTVBfSU5fUFJPR1JFU1MQwcQBEhsKEURBVEFfRFVNUF9O",
            "T19EQVRBEMLEARoCCAESIAoaREFUQV9EVU1QX1VORVhQRUNURURfRVJST1IQ",
            "w8QBEh4KGERBVEFfRFVNUF9FWFBPUlRfU1VDQ0VTUxDSxAESHgoYREFUQV9E",
            "VU1QX0VYUE9SVF9QRU5ESU5HENPEARIdChdEQVRBX0RVTVBfRVhQT1JUX0ZB",
            "SUxFRBDUxAESIgocREFUQV9EVU1QX0VYUE9SVF9JTl9QUk9HUkVTUxDVxAES",
            "JwohREFUQV9EVU1QX0VYUE9SVF9VTkVYUEVDVEVEX0VSUk9SENbEARIdChdB",
            "UFBfRFVQTElDQVRJT05fU1VDQ0VTUxDwxAESHAoWQVBQX0RVUExJQ0FUSU9O",
            "X0ZBSUxFRBDxxAESHQoXQVBQX0RVUExJQ0FUSU9OX1BFTkRJTkcQ8sQBEiEK",
            "G0FQUF9EVVBMSUNBVElPTl9JTl9QUk9HUkVTUxDzxAESJQofQVBQX0RVUExJ",
            "Q0FUSU9OX0lOVkFMSURfUkVRVUVTVBD0xAESGwoVTU9EVUxFX0RPRVNfTk9U",
            "X0VYSVNUENTFARIeChhNT0RVTEVfUEVSTUlTU0lPTl9ERU5JRUQQ1cUBEh0K",
            "F01PRFVMRV9JTlZBTElEX0FSR1VNRU5UENbFARIcChZNT0RVTEVfSU5WQUxJ",
            "RF9SRVFVRVNUENfFARIcChZCVUxLX09QRVJBVElPTl9TVUNDRVNTELjGARIb",
            "ChVCVUxLX09QRVJBVElPTl9GQUlMRUQQucYBEhwKFkJVTEtfT1BFUkFUSU9O",
            "X1BFTkRJTkcQusYBEiAKGkJVTEtfT1BFUkFUSU9OX0lOX1BST0dSRVNTELvG",
            "ARIkCh5CVUxLX09QRVJBVElPTl9JTlZBTElEX1JFUVVFU1QQvMYBEh4KGEJV",
            "TEtfT1BFUkFUSU9OX0NBTkNFTExFRBC9xgESJQofQlVMS19PUEVSQVRJT05f",
            "VU5FWFBFQ1RFRF9FUlJPUhC+xgESGwoVUlVOTkVSX0RPRVNfTk9UX0VYSVNU",
            "EIDIARIeChhSVU5ORVJfUEVSTUlTU0lPTl9ERU5JRUQQgcgBEh0KF1JVTk5F",
            "Ul9JTlZBTElEX0FSR1VNRU5UEILIARIcChZSVU5ORVJfSU5WQUxJRF9SRVFV",
            "RVNUEIPIARIYChJSVU5ORVJfTkVFRFNfUkVUUlkQhMgBEhkKE1JVTk5FUl9T",
            "VFJFQU1fU1RBUlQQhcgBEhcKEVJVTk5FUl9TVFJFQU1fRU5EEIbIARIbChVS",
            "VU5ORVJfSVRFTV9DQU5DRUxMRUQQh8gBEh4KGFJVTk5FUl9QUk9DRVNTSU5H",
            "X0ZBSUxFRBCIyAESHQoXTk9ERVBPT0xfRE9FU19OT1RfRVhJU1QQ5MgBEh8K",
            "GU5PREVQT09MX0lOVkFMSURfQVJHVU1FTlQQ5cgBEh4KGE5PREVQT09MX0lO",
            "VkFMSURfUkVRVUVTVBDmyAESJAoeQ09NUFVURV9DTFVTVEVSX0RPRVNfTk9U",
            "X0VYSVNUEMjJARImCiBDT01QVVRFX0NMVVNURVJfSU5WQUxJRF9BUkdVTUVO",
            "VBDJyQESJQofQ09NUFVURV9DTFVTVEVSX0lOVkFMSURfUkVRVUVTVBDKyQES",
            "HwoZREVQTE9ZTUVOVF9ET0VTX05PVF9FWElTVBCsygESIQobREVQTE9ZTUVO",
            "VF9JTlZBTElEX0FSR1VNRU5UEK3KARIgChpERVBMT1lNRU5UX0lOVkFMSURf",
            "UkVRVUVTVBCuygESIgocSU5TVEFOQ0VfVFlQRV9ET0VTX05PVF9FWElTVBCQ",
            "ywESJAoeSU5TVEFOQ0VfVFlQRV9JTlZBTElEX0FSR1VNRU5UEJHLARIjCh1J",
            "TlNUQU5DRV9UWVBFX0lOVkFMSURfUkVRVUVTVBCSywESKwolQ09NUFVURV9Q",
            "TEFORV9NRVRSSUNTX0lOVkFMSURfUkVRVUVTVBD0ywESIgocUElQRUxJTkVf",
            "U1RFUF9ET0VTX05PVF9FWElTVBDYzAESJAoeUElQRUxJTkVfU1RFUF9JTlZB",
            "TElEX0FSR1VNRU5UENnMARIjCh1QSVBFTElORV9TVEVQX0lOVkFMSURfUkVR",
            "VUVTVBDazAESHQoXUElQRUxJTkVfU1RFUF9VUExPQURJTkcQ28wBEiQKHlBJ",
            "UEVMSU5FX1NURVBfVVBMT0FESU5HX0ZBSUxFRBDczAESHAoWUElQRUxJTkVf",
            "U1RFUF9CVUlMRElORxDdzAESIwodUElQRUxJTkVfU1RFUF9CVUlMRElOR19G",
            "QUlMRUQQ3swBEioKJFBJUEVMSU5FX1NURVBfQlVJTERfVU5FWFBFQ1RFRF9F",
            "UlJPUhDfzAESGQoTUElQRUxJTkVfU1RFUF9SRUFEWRDgzAESHQoXUElQRUxJ",
            "TkVfU1RFUF9OT1RfUkVBRFkQ4cwBEh0KF1BJUEVMSU5FX0RPRVNfTk9UX0VY",
            "SVNUELzNARIfChlQSVBFTElORV9JTlZBTElEX0FSR1VNRU5UEL3NARIeChhQ",
            "SVBFTElORV9JTlZBTElEX1JFUVVFU1QQvs0BEhMKDUlOUFVUX1NVQ0NFU1MQ",
            "sOoBEhMKDUlOUFVUX1BFTkRJTkcQseoBEhIKDElOUFVUX0ZBSUxFRBCy6gES",
            "FwoRSU5QVVRfSU5fUFJPR1JFU1MQs+oBEiAKFklOUFVUX0RPV05MT0FEX1NV",
            "Q0NFU1MQsOoBGgIIARIgChZJTlBVVF9ET1dOTE9BRF9QRU5ESU5HELHqARoC",
            "CAESHwoVSU5QVVRfRE9XTkxPQURfRkFJTEVEELLqARoCCAESJAoaSU5QVVRf",
            "RE9XTkxPQURfSU5fUFJPR1JFU1MQs+oBGgIIARIgChpJTlBVVF9TVEFUVVNf",
            "VVBEQVRFX0ZBSUxFRBC06gESGQoTSU5QVVRfREVMRVRFX0ZBSUxFRBC16gES",
            "FQoPSU5QVVRfRFVQTElDQVRFEJTrARIeChhJTlBVVF9VTlNVUFBPUlRFRF9G",
            "T1JNQVQQlesBEhoKFElOUFVUX0RPRVNfTk9UX0VYSVNUEJbrARIdChdJTlBV",
            "VF9QRVJNSVNTSU9OX0RFTklFRBCX6wESHAoWSU5QVVRfSU5WQUxJRF9BUkdV",
            "TUVOVBCY6wESFgoQSU5QVVRfT1ZFUl9MSU1JVBCZ6wESFwoRSU5QVVRfSU5W",
            "QUxJRF9VUkwQmusBEhoKFElOUFVUX01PRElGWV9TVUNDRVNTEPjrARIaChRJ",
            "TlBVVF9NT0RJRllfUEVORElORxD56wESGQoTSU5QVVRfTU9ESUZZX0ZBSUxF",
            "RBD76wESHwoZSU5QVVRfU1RPUkFHRV9IT1NUX0ZBSUxFRBCC7AESHQoXQUxM",
            "X0lOUFVUX0lOVkFMSURfQllURVMQ3OwBEhsKFUlOUFVUX0NMVVNURVJfU1VD",
            "Q0VTUxDA7QESGwoVSU5QVVRfQ0xVU1RFUl9QRU5ESU5HEMHtARIaChRJTlBV",
            "VF9DTFVTVEVSX0ZBSUxFRBDC7QESHwoZSU5QVVRfQ0xVU1RFUl9JTl9QUk9H",
            "UkVTUxDD7QESGwoVSU5QVVRfUkVJTkRFWF9TVUNDRVNTEKTuARIbChVJTlBV",
            "VF9SRUlOREVYX1BFTkRJTkcQpe4BEhoKFElOUFVUX1JFSU5ERVhfRkFJTEVE",
            "EKbuARIfChlJTlBVVF9SRUlOREVYX0lOX1BST0dSRVNTEKfuARIiChxJTlBV",
            "VF9WSURFT19ET1dOTE9BRF9TVUNDRVNTEJjyARIiChxJTlBVVF9WSURFT19E",
            "T1dOTE9BRF9QRU5ESU5HEJnyARIhChtJTlBVVF9WSURFT19ET1dOTE9BRF9G",
            "QUlMRUQQmvIBEhsKFUlOUFVUX1ZJREVPX0RVUExJQ0FURRD88gESJAoeSU5Q",
            "VVRfVklERU9fVU5TVVBQT1JURURfRk9STUFUEP3yARIgChpJTlBVVF9WSURF",
            "T19ET0VTX05PVF9FWElTVBD+8gESIwodSU5QVVRfVklERU9fUEVSTUlTU0lP",
            "Tl9ERU5JRUQQ//IBEiIKHElOUFVUX1ZJREVPX0lOVkFMSURfQVJHVU1FTlQQ",
            "gPMBEhwKFklOUFVUX1ZJREVPX09WRVJfTElNSVQQgfMBEh0KF0lOUFVUX1ZJ",
            "REVPX0lOVkFMSURfVVJMEILzARIgChpJTlBVVF9WSURFT19NT0RJRllfU1VD",
            "Q0VTUxDg8wESIAoaSU5QVVRfVklERU9fTU9ESUZZX1BFTkRJTkcQ4fMBEh8K",
            "GUlOUFVUX1ZJREVPX01PRElGWV9GQUlMRUQQ4/MBEiUKH0lOUFVUX1ZJREVP",
            "X1NUT1JBR0VfSE9TVF9GQUlMRUQQ6vMBEiQKHkFMTF9JTlBVVF9WSURFT1Nf",
            "SU5WQUxJRF9CWVRFUxDE9AESJAoeSU5QVVRfVklERU9fUFJPQ0VTU0lOR19T",
            "VUNDRVNTEKj1ARIkCh5JTlBVVF9WSURFT19QUk9DRVNTSU5HX1BFTkRJTkcQ",
            "svUBEiMKHUlOUFVUX1ZJREVPX1BST0NFU1NJTkdfRkFJTEVEELz1ARInCiFJ",
            "TlBVVF9WSURFT19TVE9SQUdFX0lOQ09OU0lTVEVOQ1kQxvUBEiEKG0lOUFVU",
            "X1ZJREVPX1NUT1JBR0VfRkFJTFVSRRDQ9QESKAoiSU5QVVRfVklERU9fVVJM",
            "X0dFTkVSQVRJT05fRkFJTFVSRRDa9QESHQoXSU5QVVRfQ09OTkVDVElPTl9G",
            "QUlMRUQQvLgCEiYKIFJFUVVFU1RfRElTQUJMRURfRk9SX01BSU5URU5BTkNF",
            "EL24AhIvCiVJTlBVVF9XUklURVNfRElTQUJMRURfRk9SX01BSU5URU5BTkNF",
            "EL64AhoCCAESGwoVSU5QVVRfSU5WQUxJRF9SRVFVRVNUEL+4AhIdChdQUkVE",
            "SUNUX0lOVkFMSURfUkVRVUVTVBDBuAISHAoWU0VBUkNIX0lOVkFMSURfUkVR",
            "VUVTVBDCuAISHgoYQ09OQ0VQVFNfSU5WQUxJRF9SRVFVRVNUEMO4AhIbChVT",
            "VEFUU19JTlZBTElEX1JFUVVFU1QQxLgCEhwKFkRBVEFCQVNFX0RVUExJQ0FU",
            "RV9LRVkQyrgCEiAKGkRBVEFCQVNFX1NUQVRFTUVOVF9USU1FT1VUEMu4AhIk",
            "Ch5EQVRBQkFTRV9JTlZBTElEX1JPV1NfQUZGRUNURUQQzLgCEiAKGkRBVEFC",
            "QVNFX0RFQURMT0NLX0RFVEVDVEVEEM24AhIYChJEQVRBQkFTRV9GQUlMX1RB",
            "U0sQzrgCEiYKIERBVEFCQVNFX0ZBSUxfVE9fR0VUX0NPTk5FQ1RJT05TEM+4",
            "AhIfChlEQVRBQkFTRV9UT09fTUFOWV9DTElFTlRTENC4AhIiChxEQVRBQkFT",
            "RV9DT05TVFJBSU5UX1ZJT0xBVEVEENG4AhIXChFEQVRBQkFTRV9DQU5DRUxF",
            "RBDVuAISHwoZQVNZTkNfV09SS0VSX01VTFRJX0VSUk9SUxDUuAISHAoWUlBD",
            "X1JFUVVFU1RfUVVFVUVfRlVMTBDeuAISHAoWUlBDX1NFUlZFUl9VTkFWQUlM",
            "QUJMRRDfuAISGQoTUlBDX1JFUVVFU1RfVElNRU9VVBDguAISIwodUlBDX01B",
            "WF9NRVNTQUdFX1NJWkVfRVhDRUVERUQQ4bgCEhIKDFJQQ19DQU5DRUxFRBDj",
            "uAISGAoSUlBDX1VOS05PV05fTUVUSE9EEOS4AhIeChhSRVFVRVNUX0NBTkNF",
            "TEVEX0JZX1VTRVIQ5bgCEh4KGENMVVNURVJfSU5URVJOQUxfRkFJTFVSRRCg",
            "0AISHwoZRVhURVJOQUxfQ09OTkVDVElPTl9FUlJPUhDiuAISGgoUUVVFUllf",
            "SU5WQUxJRF9TWU5UQVgQ8rgCEhYKEFFVRVVFX0NPTk5fRVJST1IQqMACEiEK",
            "G1FVRVVFX0NMT1NFX1JFUVVFU1RfVElNRU9VVBCqwAISFwoRUVVFVUVfQ09O",
            "Tl9DTE9TRUQQq8ACEh8KGVFVRVVFX1BVQkxJU0hfQUNLX1RJTUVPVVQQrMAC",
            "EhkKE1FVRVVFX1BVQkxJU0hfRVJST1IQrcACEiAKGlFVRVVFX1NVQlNDUklQ",
            "VElPTl9USU1FT1VUEK7AAhIeChhRVUVVRV9TVUJTQ1JJUFRJT05fRVJST1IQ",
            "r8ACEh4KGFFVRVVFX01BUlNIQUxMSU5HX0ZBSUxFRBCwwAISIAoaUVVFVUVf",
            "VU5NQVJTSEFMTElOR19GQUlMRUQQscACEicKIVFVRVVFX01BWF9NU0dfUkVE",
            "RUxJVkVSWV9FWENFRURFRBCywAISFwoRUVVFVUVfQUNLX0ZBSUxVUkUQs8AC",
            "EhMKDVNRU19PVkVSTElNSVQQjMECEiAKGlNRU19JTlZBTElEX1JFQ0VJUFRf",
            "SEFORExFEI3BAhIRCgtTUVNfVU5LTk9XThCOwQISHQoXU0VBUkNIX0lOVEVS",
            "TkFMX0ZBSUxVUkUQ+c8CEh8KGVNFQVJDSF9QUk9KRUNUSU9OX0ZBSUxVUkUQ",
            "+s8CEh8KGVNFQVJDSF9QUkVESUNUSU9OX0ZBSUxVUkUQ+88CEicKIVNFQVJD",
            "SF9CWV9OT1RfRlVMTFlfSU5ERVhFRF9JTlBVVBD8zwISIAoaU0FWRURfU0VB",
            "UkNIX01PRElGWV9GQUlMRUQQ/c8CEh8KGVNFQVJDSF9DT1VOVFNfVU5BVkFJ",
            "TEFCTEUQ/s8CEhcKEUVWQUxVQVRJT05fUVVFVUVEENzQAhIcChZFVkFMVUFU",
            "SU9OX0lOX1BST0dSRVNTEN3QAhIYChJFVkFMVUFUSU9OX1NVQ0NFU1MQ3tAC",
            "EigKIkVWQUxVQVRJT05fRkFJTEVEX1RPX1JFVFJJRVZFX0RBVEEQ39ACEiEK",
            "G0VWQUxVQVRJT05fSU5WQUxJRF9BUkdVTUVOVBDg0AISFwoRRVZBTFVBVElP",
            "Tl9GQUlMRUQQ4dACEhgKEkVWQUxVQVRJT05fUEVORElORxDi0AISGgoURVZB",
            "TFVBVElPTl9USU1FRF9PVVQQ49ACEiEKG0VWQUxVQVRJT05fVU5FWFBFQ1RF",
            "RF9FUlJPUhDk0AISFgoQRVZBTFVBVElPTl9NSVhFRBDl0AISGAoSU1RSSVBF",
            "X0VWRU5UX0VSUk9SEOHXAhIdChdTVFJJUEVfVU5FWFBFQ1RFRF9FUlJPUhDi",
            "1wISEAoKQ0FDSEVfTUlTUxDJ3wISJgogUkVESVNfU0NSSVBUX0VYSVRFRF9X",
            "SVRIX0ZBSUxVUkUQyt8CEhYKEFJFRElTX1NUUkVBTV9FUlIQy98CEhgKElJF",
            "RElTX05PX0NPTlNVTUVSUxDM3wISGgoUUkVESVNfU1RSRUFNX0JBQ0tPRkYQ",
            "zd8CEhgKElNJR05VUF9FVkVOVF9FUlJPUhCx5wISFAoOU0lHTlVQX0ZMQUdH",
            "RUQQsucCEhoKFEZJTEVUWVBFX1VOU1VQUE9SVEVEELPnAhIXChFMT0dJTl9F",
            "VkVOVF9FUlJPUhC05wISHgoYU0lGVF9VTkNBVEVHT1JJWkVEX0VSUk9SELXn",
            "AhIfChlBUFBfQ09VTlRfSU5WQUxJRF9NRVNTQUdFEJnvAhInCiFBUFBfQ09V",
            "TlRfVVBEQVRFX0lOQ1JFTUVOVF9GQUlMRUQQmu8CEh4KGEFQUF9DT1VOVF9S",
            "RUJVSUxEX0ZBSUxFRBCb7wISIAoaQVBQX0NPVU5UX0lOVEVSTkFMX0ZBSUxV",
            "UkUQnO8CEhcKEU1QX0RPV05MT0FEX0VSUk9SEP3vAhIaChRNUF9SRVNPTFZF",
            "X0ROU19FUlJPUhD+7wISKQojTVBfRE9XTkxPQURfTUFYX1NJWkVfRVhDRUVE",
            "RURfRVJST1IQ/+8CEhsKFU1QX0lNQUdFX0RFQ09ERV9FUlJPUhCA8AISGQoT",
            "TVBfSU5WQUxJRF9BUkdVTUVOVBCB8AISHwoZTVBfSU1BR0VfUFJPQ0VTU0lO",
            "R19FUlJPUhCC8AISGQoTREFUQVRJRVJfQ09OTl9FUlJPUhDh8AISFwoRVVNF",
            "Ul9DT05TRU5UX0ZBQ0UQ0YYDEhQKDldPUktFUl9NSVNTSU5HELiOAxITCg1X",
            "T1JLRVJfQUNUSVZFELmOAxIVCg9XT1JLRVJfSU5BQ1RJVkUQuo4DEhcKEUNP",
            "TExFQ1RPUl9NSVNTSU5HEKCWAxIWChBDT0xMRUNUT1JfQUNUSVZFEKGWAxIY",
            "ChJDT0xMRUNUT1JfSU5BQ1RJVkUQopYDEiEKG0NPTExFQ1RPUl9QT1NUX0lO",
            "UFVUX0ZBSUxFRBCjlgMSKgokU1NPX0lERU5USVRZX1BST1ZJREVSX0RPRVNf",
            "Tk9UX0VYSVNUEImeAxIWChBUQVNLX0lOX1BST0dSRVNTEPGlAxIPCglUQVNL",
            "X0RPTkUQ8qUDEhIKDFRBU0tfV09OVF9ETxDzpQMSEQoLVEFTS19GQUlMRUQQ",
            "9aUDEg8KCVRBU0tfSURMRRD2pQMSEwoNVEFTS19DT05GTElDVBDUpgMSGgoU",
            "VEFTS19OT1RfSU1QTEVNRU5URUQQ1aYDEhIKDFRBU0tfTUlTU0lORxDWpgMS",
            "HAoWVEFTS19QRVJNSVNTSU9OX0RFTklFRBDXpgMSHQoXVEFTS19BU1NJR05N",
            "RU5UX1NVQ0NFU1MQuKcDEh0KF1RBU0tfQVNTSUdOTUVOVF9QRU5ESU5HELmn",
            "AxIlCh9UQVNLX0FTU0lHTk1FTlRfQVdBSVRJTkdfUkVWSUVXELqnAxIvCilU",
            "QVNLX0FTU0lHTk1FTlRfQVdBSVRJTkdfQ09OU0VOU1VTX1JFVklFVxC7pwMS",
            "HgoYVEFTS19BU1NJR05NRU5UX1JFSkVDVEVEELynAxIkCh5UQVNLX0FTU0lH",
            "Tk1FTlRfUkVWSUVXX1NVQ0NFU1MQnKgDEiQKHlRBU0tfQVNTSUdOTUVOVF9S",
            "RVZJRVdfUEVORElORxCdqAMSJgogVEFTS19BU1NJR05NRU5UX1JFVklFV19E",
            "SVNNSVNTRUQQnqgDEhkKE0xBQkVMX09SREVSX1BFTkRJTkcQ2a0DEh0KF0xB",
            "QkVMX09SREVSX0lOX1BST0dSRVNTENqtAxIZChNMQUJFTF9PUkRFUl9TVUND",
            "RVNTENutAxIaChRMQUJFTF9PUkRFUl9DQU5DRUxFRBDcrQMSFAoOTElDRU5T",
            "RV9BQ1RJVkUQ4NQDEhwKFkxJQ0VOU0VfRE9FU19OT1RfRVhJU1QQ4dQDEhkK",
            "E0xJQ0VOU0VfTkVFRF9VUERBVEUQ4tQDEhUKD0xJQ0VOU0VfRVhQSVJFRBDj",
            "1AMSFQoPTElDRU5TRV9SRVZPS0VEEOTUAxIVCg9MSUNFTlNFX0RFTEVURUQQ",
            "5dQDEh0KF0xJQ0VOU0VfVk9MVU1FX0VYQ0VFREVEEObUAxIhChtQQVNTV09S",
            "RF9WQUxJREFUSU9OX1NVQ0NFU1MQyNwDEiAKGlBBU1NXT1JEX1ZBTElEQVRJ",
            "T05fRkFJTEVEEMncAxIlCh9QQVNTV09SRFBPTElDWV9JTlZBTElEX0FSR1VN",
            "RU5UEMrcAxIiChxGRUFUVVJFRkxBR19DT05GSUdfTk9UX0ZPVU5EELDkAxIi",
            "ChxGRUFUVVJFRkxBR19JTlZBTElEX0FSR1VNRU5UELHkAxIZChNGRUFUVVJF",
            "RkxBR19CTE9DS0VEELLkAxIbChVGRUFUVVJFRkxBR19OT1RfRk9VTkQQs+QD",
            "EhkKE01BSU5URU5BTkNFX1NVQ0NFU1MQmOwDEhgKEk1BSU5URU5BTkNFX0ZB",
            "SUxFRBCZ7AMSHQoXREFUQVNFVF9WRVJTSU9OX1BFTkRJTkcQhfQDEiEKG0RB",
            "VEFTRVRfVkVSU0lPTl9JTl9QUk9HUkVTUxCK9AMSGwoVREFUQVNFVF9WRVJT",
            "SU9OX1JFQURZEI/0AxIdChdEQVRBU0VUX1ZFUlNJT05fRkFJTFVSRRCU9AMS",
            "JgogREFUQVNFVF9WRVJTSU9OX1VORVhQRUNURURfRVJST1IQmfQDEh4KGERB",
            "VEFTRVRfVkVSU0lPTl9DT05GTElDVBCe9AMSGwoVREFUQVNFVF9JTlBVVF9T",
            "VUNDRVNTEOT0AxIdChdEQVRBU0VUX0lOUFVUX0RVUExJQ0FURRDl9AMSJAoe",
            "REFUQVNFVF9WRVJTSU9OX0VYUE9SVF9TVUNDRVNTEMj1AxIkCh5EQVRBU0VU",
            "X1ZFUlNJT05fRVhQT1JUX1BFTkRJTkcQyfUDEiMKHURBVEFTRVRfVkVSU0lP",
            "Tl9FWFBPUlRfRkFJTEVEEMr1AxIoCiJEQVRBU0VUX1ZFUlNJT05fRVhQT1JU",
            "X0lOX1BST0dSRVNTEMv1AxItCidEQVRBU0VUX1ZFUlNJT05fRVhQT1JUX1VO",
            "RVhQRUNURURfRVJST1IQzPUDEhAKCkpPQl9RVUVVRUQQgPQDEhEKC0pPQl9S",
            "VU5OSU5HEIH0AxITCg1KT0JfQ09NUExFVEVEEIL0AxIQCgpKT0JfRkFJTEVE",
            "EIP0AxITCg1KT0JfQ0FOQ0VMTEVEEIT0AxIaChRKT0JfVU5FWFBFQ1RFRF9F",
            "UlJPUhCG9AMSEgoMSk9CX0NPTkZMSUNUEIf0AxIcChZBVVRIX01JU1NJTkdf",
            "SURQX0FTU09DEOj7AxIZChNMSVNUX09CSkVDVFNfRkFJTEVEENCDBBIcChZB",
            "UkNISVZFX0VYVFJBQ1RfRkFJTEVEELiLBBIYChJVUExPQURfSU5fUFJPR1JF",
            "U1MQoJMEEhEKC1VQTE9BRF9ET05FEKGTBBITCg1VUExPQURfRkFJTEVEEKKT",
            "BBIdChdVUExPQURfVU5FWFBFQ1RFRF9FUlJPUhCjkwQSFAoOVVBMT0FEX0VY",
            "UElSRUQQpJMEEhUKD1VQTE9BRF9DQU5DRUxFRBClkwQSFQoPVVBMT0FEX0NP",
            "TkZMSUNUEKaTBBIaChRCSUxMSU5HX0lOVkFMSURfSU5GTxCImwQSHAoWQklM",
            "TElOR19NSVNTSU5HX1RPS0VOUxCJmwQSIQobTE9HX0VOVFJJRVNfSU5WQUxJ",
            "RF9SRVFVRVNUEPCiBBIbChVJTlRFUk5BTF9TRVJWRVJfSVNTVUUQ1P0FEh0K",
            "F0lOVEVSTkFMX0ZFVENISU5HX0lTU1VFENX9BRIdChdJTlRFUk5BTF9EQVRB",
            "QkFTRV9JU1NVRRDW/QUSHwoZSU5URVJOQUxfQ09OVEVYVF9DQU5DRUxFRBDY",
            "/QUSIQobSU5URVJOQUxfVU5FWFBFQ1RFRF9USU1FT1VUENn9BRIcChZJTlRF",
            "Uk5BTF9VTkVYUEVDVEVEX1YxENr9BRIfChlJTlRFUk5BTF9VTkVYUEVDVEVE",
            "X1BBTklDENv9BRIfChlJTlRFUk5BTF9VTkVYUEVDVEVEX1NQSVJFENz9BRIg",
            "ChpJTlRFUk5BTF9SRURJU19VTkFWQUlMQUJMRRDd/QUSIQobSU5URVJOQUxf",
            "UkVTT1VSQ0VfRVhIQVVTVEVEEN79BRIiChxJTlRFUk5BTF9SRURJU19VTkNB",
            "VEVHT1JJWkVEEN/9BRIgChpJTlRFUk5BTF9BV1NfVU5DQVRFR09SSVpFRBDg",
            "/QUSIgocSU5URVJOQUxfQVpVUkVfVU5DQVRFR09SSVpFRBDh/QUSJQofSU5U",
            "RVJOQUxfVkVDVE9SREJfVU5DQVRFR09SSVpFRBDi/QUSIwodSU5URVJOQUxf",
            "T1JBQ0xFX1VOQ0FURUdPUklaRUQQ4/0FEiIKHElOVEVSTkFMX1ZVTFRSX1VO",
            "Q0FURUdPUklaRUQQ5P0FEiAKGklOVEVSTkFMX0dDUF9VTkNBVEVHT1JJWkVE",
            "EOX9BRIYChJDT05OX1VOQ0FURUdPUklaRUQQuYUGEhkKE01PREVMX1VOQ0FU",
            "RUdPUklaRUQQuoUGEhkKE0lOUFVUX1VOQ0FURUdPUklaRUQQu4UGEh4KGEFO",
            "Tk9UQVRJT05fVU5DQVRFR09SSVpFRBC8hQYSGwoVQklMTElOR19VTkNBVEVH",
            "T1JJWkVEEL2FBhIcChZJTlRFUk5BTF9VTkNBVEVHT1JJWkVEEMGFBhIRCgtC",
            "QURfUkVRVUVTVBCgwgUSEgoMU0VSVkVSX0VSUk9SEITDBRoCEAEiCAi/xgEQ",
            "v8YBIggI6IECEOiBAiIICOmBAhDpgQIiCAjqgQIQ6oECIggIzIICEMyCAiII",
            "CM2CAhDNggIiCAjOggIQzoICIggIz4ICEM+CAiIICNCCAhDQggIiCAjRggIQ",
            "0YICIggI0oICENKCAiIICLCDAhCwgwIiCAixgwIQsYMCIggIs4MCELODAiII",
            "CLqDAhC6gwIiCAi7uAIQu7gCIggI0rgCENK4AiIICNO4AhDTuAIiCAjwwQIQ",
            "8MECIggI8cECEPHBAiIICPLBAhDywQIiCAjzwQIQ88ECIggI9MECEPTBAiII",
            "CJzHARCcxwEiCAidxwEQnccBIggInscBEJ7HASIICJ/HARCfxwEiCAihxwEQ",
            "occBIggIoscBEKLHAUJnChxjb20uY2xhcmlmYWkuZ3JwYy5hcGkuc3RhdHVz",
            "UAFaPmdpdGh1Yi5jb20vQ2xhcmlmYWkvY2xhcmlmYWktZ28tZ3JwYy9wcm90",
            "by9jbGFyaWZhaS9hcGkvc3RhdHVzogIEQ0FJUGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Clarifai.Api.Status.StatusCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StatusCode {
    /// <summary>
    /// to be revised and greatly expanded
    /// </summary>
    [pbr::OriginalName("ZERO")] Zero = 0,
    /// <summary>
    /// Generic
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 10000,
    [pbr::OriginalName("MIXED_STATUS")] MixedStatus = 10010,
    [pbr::OriginalName("FAILURE")] Failure = 10020,
    [pbr::OriginalName("TRY_AGAIN")] TryAgain = 10030,
    [pbr::OriginalName("NOT_IMPLEMENTED")] NotImplemented = 10040,
    /// <summary>
    /// Resource moved. Respond with Http status 307 and add new Location header to response
    /// </summary>
    [pbr::OriginalName("MOVED")] Moved = 10050,
    [pbr::OriginalName("TEAPOT")] Teapot = 10060,
    /// <summary>
    /// Request has been accepted. Respond with Http status 202.
    /// </summary>
    [pbr::OriginalName("ACCEPTED")] Accepted = 10070,
    /// <summary>
    /// Clarifai Connection Codes: 11xxx
    /// </summary>
    [pbr::OriginalName("CONN_ACCOUNT_ISSUES")] ConnAccountIssues = 11000,
    /// <summary>
    /// invalid auth token used. Deprecated: we should return CONN_KEY_INVALID instead now in all cases.
    /// </summary>
    [pbr::OriginalName("CONN_TOKEN_INVALID")] ConnTokenInvalid = 11001,
    /// <summary>
    /// invalid auth credentials
    /// </summary>
    [pbr::OriginalName("CONN_CREDENTIALS_INVALID")] ConnCredentialsInvalid = 11002,
    /// <summary>
    /// throttle hourly limit exceeded
    /// </summary>
    [pbr::OriginalName("CONN_EXCEED_HOURLY_LIMIT")] ConnExceedHourlyLimit = 11003,
    /// <summary>
    /// throttle monthly limit exceeded
    /// </summary>
    [pbr::OriginalName("CONN_EXCEED_MONTHLY_LIMIT")] ConnExceedMonthlyLimit = 11004,
    /// <summary>
    /// throttler and billing stuff
    /// </summary>
    [pbr::OriginalName("CONN_THROTTLED")] ConnThrottled = 11005,
    /// <summary>
    /// throttler and billing stuff
    /// </summary>
    [pbr::OriginalName("CONN_EXCEEDS_LIMITS")] ConnExceedsLimits = 11006,
    /// <summary>
    /// api key has insufficient permissions
    /// </summary>
    [pbr::OriginalName("CONN_INSUFFICIENT_SCOPES")] ConnInsufficientScopes = 11007,
    /// <summary>
    /// api key is invalid
    /// </summary>
    [pbr::OriginalName("CONN_KEY_INVALID")] ConnKeyInvalid = 11008,
    /// <summary>
    /// api key not found
    /// </summary>
    [pbr::OriginalName("CONN_KEY_NOT_FOUND")] ConnKeyNotFound = 11009,
    /// <summary>
    /// multipart form parsing, broken json, etc
    /// </summary>
    [pbr::OriginalName("CONN_BAD_REQUEST_FORMAT")] ConnBadRequestFormat = 11100,
    /// <summary>
    /// when path is bad
    /// </summary>
    [pbr::OriginalName("CONN_DOES_NOT_EXIST")] ConnDoesNotExist = 11101,
    /// <summary>
    /// something wrong with a header
    /// </summary>
    [pbr::OriginalName("CONN_INVALID_REQUEST")] ConnInvalidRequest = 11102,
    /// <summary>
    /// when a request method is not allowed
    /// </summary>
    [pbr::OriginalName("CONN_METHOD_NOT_ALLOWED")] ConnMethodNotAllowed = 11103,
    /// <summary>
    /// lack GDPR consent
    /// </summary>
    [pbr::OriginalName("CONN_NO_GDPR_CONSENT")] ConnNoGdprConsent = 11104,
    /// <summary>
    /// when invalid range of a resource is requested
    /// </summary>
    [pbr::OriginalName("CONN_INVALID_RANGE")] ConnInvalidRange = 11105,
    /// <summary>
    /// authentication method is disabled
    /// </summary>
    [pbr::OriginalName("CONN_AUTH_METHOD_DISABLED")] ConnAuthMethodDisabled = 11200,
    /// <summary>
    /// Model/Custom Training related 20xxx
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINED")] ModelTrained = 21100,
    /// <summary>
    /// Custom model is currently training.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING")] ModelTraining = 21101,
    /// <summary>
    /// Custom model has not yet been trained.
    /// </summary>
    [pbr::OriginalName("MODEL_UNTRAINED")] ModelUntrained = 21102,
    /// <summary>
    /// Custom model is currently in queue for training, waiting on assets to process first.
    /// </summary>
    [pbr::OriginalName("MODEL_QUEUED_FOR_TRAINING")] ModelQueuedForTraining = 21103,
    [pbr::OriginalName("MODEL_UPLOADING")] ModelUploading = 21104,
    [pbr::OriginalName("MODEL_UPLOADING_FAILED")] ModelUploadingFailed = 21105,
    /// <summary>
    /// generic err msg for any type of model training err.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_FAILED")] ModelTrainingFailed = 21106,
    /// <summary>
    /// For new V3 DockerInternalType models which are built images
    /// </summary>
    [pbr::OriginalName("MODEL_BUILDING")] ModelBuilding = 21107,
    /// <summary>
    /// Failed to build image for model.
    /// </summary>
    [pbr::OriginalName("MODEL_BUILDING_FAILED")] ModelBuildingFailed = 21108,
    /// <summary>
    /// Failed to build image for model.
    /// </summary>
    [pbr::OriginalName("MODEL_BUILD_UNEXPECTED_ERROR")] ModelBuildUnexpectedError = 21109,
    /// <summary>
    /// Custom model training had no data.  FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_NO_DATA")] ModelTrainingNoData = 21110,
    /// <summary>
    /// Custom model training had no positive examples. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_NO_POSITIVES")] ModelTrainingNoPositives = 21111,
    /// <summary>
    /// Custom model training was ONE_VS_N but with a single class. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_ONE_VS_N_SINGLE_CLASS")] ModelTrainingOneVsNSingleClass = 21112,
    /// <summary>
    /// Training took longer than hard coded timeouts. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_TIMED_OUT")] ModelTrainingTimedOut = 21113,
    /// <summary>
    /// Training got error waiting on asset pipeline to finish. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_WAITING_ERROR")] ModelTrainingWaitingError = 21114,
    /// <summary>
    /// Training threw an unknown exception.
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_UNKNOWN_ERROR")] ModelTrainingUnknownError = 21115,
    /// <summary>
    /// Training message was redelivered. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_MSG_REDELIVER")] ModelTrainingMsgRedeliver = 21116,
    /// <summary>
    /// Training got error due to insufficient labelled data. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INSUFFICIENT_DATA")] ModelTrainingInsufficientData = 21117,
    /// <summary>
    /// FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INVALID_PARAMS")] ModelTrainingInvalidParams = 21118,
    /// <summary>
    /// Training is stopped because too much data was dropped. FIXME(yang): deprecate this. Use the 21106 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_TRAINING_INVALID_DATA_TOLERANCE_EXCEEDED")] ModelTrainingInvalidDataToleranceExceeded = 21119,
    [pbr::OriginalName("MODEL_MODIFY_SUCCESS")] ModelModifySuccess = 21150,
    [pbr::OriginalName("MODEL_MODIFY_PENDING")] ModelModifyPending = 21151,
    [pbr::OriginalName("MODEL_MODIFY_FAILED")] ModelModifyFailed = 21152,
    [pbr::OriginalName("MODEL_DOES_NOT_EXIST")] ModelDoesNotExist = 21200,
    [pbr::OriginalName("MODEL_PERMISSION_DENIED")] ModelPermissionDenied = 21201,
    [pbr::OriginalName("MODEL_INVALID_ARGUMENT")] ModelInvalidArgument = 21202,
    [pbr::OriginalName("MODEL_INVALID_REQUEST")] ModelInvalidRequest = 21203,
    [pbr::OriginalName("MODEL_EVALUATED")] ModelEvaluated = 21300,
    [pbr::OriginalName("MODEL_EVALUATING")] ModelEvaluating = 21301,
    [pbr::OriginalName("MODEL_NOT_EVALUATED")] ModelNotEvaluated = 21302,
    [pbr::OriginalName("MODEL_QUEUED_FOR_EVALUATION")] ModelQueuedForEvaluation = 21303,
    /// <summary>
    /// Evaluation took longer than hard coded timeouts. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_TIMED_OUT")] ModelEvaluationTimedOut = 21310,
    /// <summary>
    /// Evaluation got error waiting on asset pipeline to finish.FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_WAITING_ERROR")] ModelEvaluationWaitingError = 21311,
    /// <summary>
    /// EVALUATION THREW AN UNKNOWN EXCEPTION.
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_UNKNOWN_ERROR")] ModelEvaluationUnknownError = 21312,
    [pbr::OriginalName("MODEL_PREDICTION_FAILED")] ModelPredictionFailed = 21313,
    /// <summary>
    /// Eval message was redelivered. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_MSG_REDELIVER")] ModelEvaluationMsgRedeliver = 21314,
    /// <summary>
    /// Don't have enough concepts labelled to perform evaluation. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_NEED_LABELS")] ModelEvaluationNeedLabels = 21315,
    /// <summary>
    /// Don't have enough inputs per concept to perform evaluation. FIXME(yang): deprecate this. Use the 21317 + errStatusMsg
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_NEED_INPUTS")] ModelEvaluationNeedInputs = 21316,
    /// <summary>
    /// Generic err code for eval failure.
    /// </summary>
    [pbr::OriginalName("MODEL_EVALUATION_FAILED")] ModelEvaluationFailed = 21317,
    /// <summary>
    /// Used when inference coordinator failed to deploy spire and throws an error
    /// </summary>
    [pbr::OriginalName("MODEL_DEPLOYMENT_FAILED")] ModelDeploymentFailed = 21350,
    /// <summary>
    /// Used when calling the inference coordinator to deploy a spire
    /// </summary>
    [pbr::OriginalName("MODEL_DEPLOYING")] ModelDeploying = 21351,
    /// <summary>
    /// Used when training is completed
    /// </summary>
    [pbr::OriginalName("MODEL_QUEUED_FOR_DEPLOYMENT")] ModelQueuedForDeployment = 21352,
    /// <summary>
    /// Used when model spire deployment is manually taken down or due to inactivity
    /// </summary>
    [pbr::OriginalName("MODEL_NOT_DEPLOYED")] ModelNotDeployed = 21353,
    [pbr::OriginalName("MODEL_BUSY_PLEASE_RETRY")] ModelBusyPleaseRetry = 21354,
    /// <summary>
    /// Used when the model pod is running, but not yet ready to serve requests.
    /// </summary>
    [pbr::OriginalName("MODEL_LOADING")] ModelLoading = 21355,
    /// <summary>
    /// Used when a model reference field is not set properly
    /// </summary>
    [pbr::OriginalName("MODEL_REFERENCE_INVALID_ARGUMENT")] ModelReferenceInvalidArgument = 21400,
    /// <summary>
    /// Used when a model example input field is not set properly
    /// </summary>
    [pbr::OriginalName("MODEL_EXAMPLE_INPUT_INVALID_ARGUMENT")] ModelExampleInputInvalidArgument = 21420,
    /// <summary>
    /// Model Export status codes
    /// </summary>
    [pbr::OriginalName("MODEL_EXPORTED")] ModelExported = 21500,
    [pbr::OriginalName("MODEL_EXPORTING")] ModelExporting = 21501,
    [pbr::OriginalName("MODEL_EXPORTING_FAILED")] ModelExportingFailed = 21502,
    [pbr::OriginalName("MODEL_EXPORT_PENDING")] ModelExportPending = 21503,
    /// <summary>
    /// specified model input not in workflow
    /// </summary>
    [pbr::OriginalName("WORKFLOW_NO_MATCHING_INPUT")] WorkflowNoMatchingInput = 22001,
    /// <summary>
    /// specified model must be trained
    /// </summary>
    [pbr::OriginalName("WORKFLOW_REQUIRE_TRAINED_MODEL")] WorkflowRequireTrainedModel = 22002,
    [pbr::OriginalName("WORKFLOW_DUPLICATE")] WorkflowDuplicate = 22100,
    [pbr::OriginalName("WORKFLOW_UNSUPPORTED_FORMAT")] WorkflowUnsupportedFormat = 22101,
    [pbr::OriginalName("WORKFLOW_DOES_NOT_EXIST")] WorkflowDoesNotExist = 22102,
    [pbr::OriginalName("WORKFLOW_PERMISSION_DENIED")] WorkflowPermissionDenied = 22103,
    /// <summary>
    /// error in the request somewhere
    /// </summary>
    [pbr::OriginalName("WORKFLOW_INVALID_ARGUMENT")] WorkflowInvalidArgument = 22104,
    [pbr::OriginalName("WORKFLOW_INVALID_RECIPE")] WorkflowInvalidRecipe = 22105,
    [pbr::OriginalName("WORKFLOW_INVALID_TEMPLATE")] WorkflowInvalidTemplate = 22106,
    [pbr::OriginalName("WORKFLOW_INVALID_GRAPH")] WorkflowInvalidGraph = 22107,
    [pbr::OriginalName("WORKFLOW_INTERNAL_FAILURE")] WorkflowInternalFailure = 22108,
    /// <summary>
    /// error in the request somewhere
    /// </summary>
    [pbr::OriginalName("WORKFLOW_INVALID_REQUEST")] WorkflowInvalidRequest = 22999,
    [pbr::OriginalName("WORKFLOW_MODIFY_SUCCESS")] WorkflowModifySuccess = 22150,
    [pbr::OriginalName("WORKFLOW_MODIFY_PENDING")] WorkflowModifyPending = 22151,
    [pbr::OriginalName("WORKFLOW_MODIFY_FAILED")] WorkflowModifyFailed = 22152,
    [pbr::OriginalName("WORKFLOW_REINDEX_FAILED")] WorkflowReindexFailed = 22153,
    /// <summary>
    /// Concept related 23xxx
    /// </summary>
    [pbr::OriginalName("CONCEPT_MODIFY_SUCCESS")] ConceptModifySuccess = 23150,
    [pbr::OriginalName("CONCEPT_MODIFY_PENDING")] ConceptModifyPending = 23151,
    [pbr::OriginalName("CONCEPT_MODIFY_FAILED")] ConceptModifyFailed = 23152,
    /// <summary>
    /// Annotation related 24xxx
    /// </summary>
    [pbr::OriginalName("ANNOTATION_SUCCESS")] AnnotationSuccess = 24150,
    [pbr::OriginalName("ANNOTATION_PENDING")] AnnotationPending = 24151,
    [pbr::OriginalName("ANNOTATION_FAILED")] AnnotationFailed = 24152,
    [pbr::OriginalName("ANNOTATION_UNKNOWN_STATUS")] AnnotationUnknownStatus = 24154,
    [pbr::OriginalName("ANNOTATION_INVALID_ARGUMENT")] AnnotationInvalidArgument = 24155,
    [pbr::OriginalName("ANNOTATION_PERMISSION_DENIED")] AnnotationPermissionDenied = 24156,
    /// <summary>
    /// Annotation is awaiting review from task REVIEWERS.
    /// </summary>
    [pbr::OriginalName("ANNOTATION_AWAITING_REVIEW")] AnnotationAwaitingReview = 24157,
    /// <summary>
    /// Annotation is awaiting consensus review from task LABELERS.
    /// </summary>
    [pbr::OriginalName("ANNOTATION_AWAITING_CONSENSUS_REVIEW")] AnnotationAwaitingConsensusReview = 24159,
    [pbr::OriginalName("ANNOTATION_REVIEW_DENIED")] AnnotationReviewDenied = 24158,
    [pbr::OriginalName("ANNOTATION_MODIFY_SUCCESS")] AnnotationModifySuccess = 24250,
    [pbr::OriginalName("ANNOTATION_MODIFY_PENDING")] AnnotationModifyPending = 24251,
    [pbr::OriginalName("ANNOTATION_MODIFY_FAILED")] AnnotationModifyFailed = 24252,
    /// <summary>
    /// Annotation (video) tracks are groups of annotations per frame
    /// IDLE -> PROCESSING --> PENDING --> APPROVED --> (DELETED)
    /// PROCESSING --> FAILED --> (DELETED)
    /// PROCESSING --> (DELETED)
    /// </summary>
    [pbr::OriginalName("ANNOTATION_TRACK_IDLE")] AnnotationTrackIdle = 24300,
    [pbr::OriginalName("ANNOTATION_TRACK_IN_PROGRESS")] AnnotationTrackInProgress = 24301,
    [pbr::OriginalName("ANNOTATION_TRACK_PENDING")] AnnotationTrackPending = 24302,
    [pbr::OriginalName("ANNOTATION_TRACK_APPROVED")] AnnotationTrackApproved = 24303,
    [pbr::OriginalName("ANNOTATION_TRACK_FAILED")] AnnotationTrackFailed = 24304,
    /// <summary>
    /// Metadata related 249xx
    /// </summary>
    [pbr::OriginalName("METADATA_INVALID_PATCH_ARGUMENTS")] MetadataInvalidPatchArguments = 24900,
    [pbr::OriginalName("METADATA_PARSING_ISSUE")] MetadataParsingIssue = 24901,
    [pbr::OriginalName("METADATA_MANIPULATION_ISSUE")] MetadataManipulationIssue = 24902,
    /// <summary>
    /// Training service related 25xxx
    /// </summary>
    [pbr::OriginalName("TRAINER_JOB_STATE_NONE")] TrainerJobStateNone = 25000,
    [pbr::OriginalName("TRAINER_JOB_STATE_QUEUED")] TrainerJobStateQueued = 25001,
    [pbr::OriginalName("TRAINER_JOB_STATE_RUNNING")] TrainerJobStateRunning = 25002,
    [pbr::OriginalName("TRAINER_JOB_STATE_COMPLETE")] TrainerJobStateComplete = 25003,
    [pbr::OriginalName("TRAINER_JOB_STATE_ERROR")] TrainerJobStateError = 25004,
    /// <summary>
    /// Data Dump related 251xx
    /// </summary>
    [pbr::OriginalName("DATA_DUMP_SUCCESS")] DataDumpSuccess = 25150,
    [pbr::OriginalName("DATA_DUMP_PENDING")] DataDumpPending = 25151,
    [pbr::OriginalName("DATA_DUMP_FAILED")] DataDumpFailed = 25152,
    [pbr::OriginalName("DATA_DUMP_IN_PROGRESS")] DataDumpInProgress = 25153,
    /// <summary>
    /// DEPRECATED: Not used anymore. Now for an empty data dump, DATA_DUMP_SUCCESS is returned. To detect an empty data dump, check if the inptus count is 0.
    /// </summary>
    [pbr::OriginalName("DATA_DUMP_NO_DATA")] DataDumpNoData = 25154,
    [pbr::OriginalName("DATA_DUMP_UNEXPECTED_ERROR")] DataDumpUnexpectedError = 25155,
    [pbr::OriginalName("DATA_DUMP_EXPORT_SUCCESS")] DataDumpExportSuccess = 25170,
    [pbr::OriginalName("DATA_DUMP_EXPORT_PENDING")] DataDumpExportPending = 25171,
    [pbr::OriginalName("DATA_DUMP_EXPORT_FAILED")] DataDumpExportFailed = 25172,
    [pbr::OriginalName("DATA_DUMP_EXPORT_IN_PROGRESS")] DataDumpExportInProgress = 25173,
    [pbr::OriginalName("DATA_DUMP_EXPORT_UNEXPECTED_ERROR")] DataDumpExportUnexpectedError = 25174,
    /// <summary>
    /// Duplicate related 252xx
    /// </summary>
    [pbr::OriginalName("APP_DUPLICATION_SUCCESS")] AppDuplicationSuccess = 25200,
    [pbr::OriginalName("APP_DUPLICATION_FAILED")] AppDuplicationFailed = 25201,
    [pbr::OriginalName("APP_DUPLICATION_PENDING")] AppDuplicationPending = 25202,
    [pbr::OriginalName("APP_DUPLICATION_IN_PROGRESS")] AppDuplicationInProgress = 25203,
    [pbr::OriginalName("APP_DUPLICATION_INVALID_REQUEST")] AppDuplicationInvalidRequest = 25204,
    /// <summary>
    /// Module related codes 253xx
    /// </summary>
    [pbr::OriginalName("MODULE_DOES_NOT_EXIST")] ModuleDoesNotExist = 25300,
    [pbr::OriginalName("MODULE_PERMISSION_DENIED")] ModulePermissionDenied = 25301,
    [pbr::OriginalName("MODULE_INVALID_ARGUMENT")] ModuleInvalidArgument = 25302,
    [pbr::OriginalName("MODULE_INVALID_REQUEST")] ModuleInvalidRequest = 25303,
    /// <summary>
    /// Bulk Operation related codes 254xx
    /// </summary>
    [pbr::OriginalName("BULK_OPERATION_SUCCESS")] BulkOperationSuccess = 25400,
    [pbr::OriginalName("BULK_OPERATION_FAILED")] BulkOperationFailed = 25401,
    [pbr::OriginalName("BULK_OPERATION_PENDING")] BulkOperationPending = 25402,
    [pbr::OriginalName("BULK_OPERATION_IN_PROGRESS")] BulkOperationInProgress = 25403,
    [pbr::OriginalName("BULK_OPERATION_INVALID_REQUEST")] BulkOperationInvalidRequest = 25404,
    [pbr::OriginalName("BULK_OPERATION_CANCELLED")] BulkOperationCancelled = 25405,
    [pbr::OriginalName("BULK_OPERATION_UNEXPECTED_ERROR")] BulkOperationUnexpectedError = 25406,
    /// <summary>
    /// Runner related codes 256xx
    /// </summary>
    [pbr::OriginalName("RUNNER_DOES_NOT_EXIST")] RunnerDoesNotExist = 25600,
    [pbr::OriginalName("RUNNER_PERMISSION_DENIED")] RunnerPermissionDenied = 25601,
    [pbr::OriginalName("RUNNER_INVALID_ARGUMENT")] RunnerInvalidArgument = 25602,
    [pbr::OriginalName("RUNNER_INVALID_REQUEST")] RunnerInvalidRequest = 25603,
    [pbr::OriginalName("RUNNER_NEEDS_RETRY")] RunnerNeedsRetry = 25604,
    [pbr::OriginalName("RUNNER_STREAM_START")] RunnerStreamStart = 25605,
    [pbr::OriginalName("RUNNER_STREAM_END")] RunnerStreamEnd = 25606,
    [pbr::OriginalName("RUNNER_ITEM_CANCELLED")] RunnerItemCancelled = 25607,
    [pbr::OriginalName("RUNNER_PROCESSING_FAILED")] RunnerProcessingFailed = 25608,
    /// <summary>
    /// Nodepool related codes 257xx
    /// </summary>
    [pbr::OriginalName("NODEPOOL_DOES_NOT_EXIST")] NodepoolDoesNotExist = 25700,
    [pbr::OriginalName("NODEPOOL_INVALID_ARGUMENT")] NodepoolInvalidArgument = 25701,
    [pbr::OriginalName("NODEPOOL_INVALID_REQUEST")] NodepoolInvalidRequest = 25702,
    /// <summary>
    /// ComputeCluster related codes 258xx
    /// </summary>
    [pbr::OriginalName("COMPUTE_CLUSTER_DOES_NOT_EXIST")] ComputeClusterDoesNotExist = 25800,
    [pbr::OriginalName("COMPUTE_CLUSTER_INVALID_ARGUMENT")] ComputeClusterInvalidArgument = 25801,
    [pbr::OriginalName("COMPUTE_CLUSTER_INVALID_REQUEST")] ComputeClusterInvalidRequest = 25802,
    /// <summary>
    /// Deployment related codes 259xx
    /// </summary>
    [pbr::OriginalName("DEPLOYMENT_DOES_NOT_EXIST")] DeploymentDoesNotExist = 25900,
    [pbr::OriginalName("DEPLOYMENT_INVALID_ARGUMENT")] DeploymentInvalidArgument = 25901,
    [pbr::OriginalName("DEPLOYMENT_INVALID_REQUEST")] DeploymentInvalidRequest = 25902,
    /// <summary>
    /// InstanceType related codes 260xx
    /// </summary>
    [pbr::OriginalName("INSTANCE_TYPE_DOES_NOT_EXIST")] InstanceTypeDoesNotExist = 26000,
    [pbr::OriginalName("INSTANCE_TYPE_INVALID_ARGUMENT")] InstanceTypeInvalidArgument = 26001,
    [pbr::OriginalName("INSTANCE_TYPE_INVALID_REQUEST")] InstanceTypeInvalidRequest = 26002,
    /// <summary>
    /// Compute plane related codes 261xx
    /// </summary>
    [pbr::OriginalName("COMPUTE_PLANE_METRICS_INVALID_REQUEST")] ComputePlaneMetricsInvalidRequest = 26100,
    /// <summary>
    /// PipelineStep related codes 262xx
    /// </summary>
    [pbr::OriginalName("PIPELINE_STEP_DOES_NOT_EXIST")] PipelineStepDoesNotExist = 26200,
    [pbr::OriginalName("PIPELINE_STEP_INVALID_ARGUMENT")] PipelineStepInvalidArgument = 26201,
    [pbr::OriginalName("PIPELINE_STEP_INVALID_REQUEST")] PipelineStepInvalidRequest = 26202,
    [pbr::OriginalName("PIPELINE_STEP_UPLOADING")] PipelineStepUploading = 26203,
    [pbr::OriginalName("PIPELINE_STEP_UPLOADING_FAILED")] PipelineStepUploadingFailed = 26204,
    [pbr::OriginalName("PIPELINE_STEP_BUILDING")] PipelineStepBuilding = 26205,
    [pbr::OriginalName("PIPELINE_STEP_BUILDING_FAILED")] PipelineStepBuildingFailed = 26206,
    [pbr::OriginalName("PIPELINE_STEP_BUILD_UNEXPECTED_ERROR")] PipelineStepBuildUnexpectedError = 26207,
    [pbr::OriginalName("PIPELINE_STEP_READY")] PipelineStepReady = 26208,
    [pbr::OriginalName("PIPELINE_STEP_NOT_READY")] PipelineStepNotReady = 26209,
    /// <summary>
    /// Pipeline related codes 263xx
    /// </summary>
    [pbr::OriginalName("PIPELINE_DOES_NOT_EXIST")] PipelineDoesNotExist = 26300,
    [pbr::OriginalName("PIPELINE_INVALID_ARGUMENT")] PipelineInvalidArgument = 26301,
    [pbr::OriginalName("PIPELINE_INVALID_REQUEST")] PipelineInvalidRequest = 26302,
    /// <summary>
    /// Input:Image related 30xxx
    /// </summary>
    [pbr::OriginalName("INPUT_SUCCESS")] InputSuccess = 30000,
    /// <summary>
    /// when things are async, this is the default status.
    /// </summary>
    [pbr::OriginalName("INPUT_PENDING")] InputPending = 30001,
    /// <summary>
    /// any type of error downloading and processing
    /// </summary>
    [pbr::OriginalName("INPUT_FAILED")] InputFailed = 30002,
    [pbr::OriginalName("INPUT_IN_PROGRESS")] InputInProgress = 30003,
    /// <summary>
    /// use INPUT_SUCCESS, INPUT_PENDING, INPUT_FAILED, INPUT_IN_PROGRESS instead
    /// DOWNLOAD is no longer correct, but keep old statuses for backward compatibility
    /// </summary>
    [pbr::OriginalName("INPUT_DOWNLOAD_SUCCESS", PreferredAlias = false)] InputDownloadSuccess = 30000,
    [pbr::OriginalName("INPUT_DOWNLOAD_PENDING", PreferredAlias = false)] InputDownloadPending = 30001,
    [pbr::OriginalName("INPUT_DOWNLOAD_FAILED", PreferredAlias = false)] InputDownloadFailed = 30002,
    [pbr::OriginalName("INPUT_DOWNLOAD_IN_PROGRESS", PreferredAlias = false)] InputDownloadInProgress = 30003,
    [pbr::OriginalName("INPUT_STATUS_UPDATE_FAILED")] InputStatusUpdateFailed = 30004,
    [pbr::OriginalName("INPUT_DELETE_FAILED")] InputDeleteFailed = 30005,
    [pbr::OriginalName("INPUT_DUPLICATE")] InputDuplicate = 30100,
    [pbr::OriginalName("INPUT_UNSUPPORTED_FORMAT")] InputUnsupportedFormat = 30101,
    [pbr::OriginalName("INPUT_DOES_NOT_EXIST")] InputDoesNotExist = 30102,
    [pbr::OriginalName("INPUT_PERMISSION_DENIED")] InputPermissionDenied = 30103,
    [pbr::OriginalName("INPUT_INVALID_ARGUMENT")] InputInvalidArgument = 30104,
    [pbr::OriginalName("INPUT_OVER_LIMIT")] InputOverLimit = 30105,
    [pbr::OriginalName("INPUT_INVALID_URL")] InputInvalidUrl = 30106,
    [pbr::OriginalName("INPUT_MODIFY_SUCCESS")] InputModifySuccess = 30200,
    [pbr::OriginalName("INPUT_MODIFY_PENDING")] InputModifyPending = 30201,
    [pbr::OriginalName("INPUT_MODIFY_FAILED")] InputModifyFailed = 30203,
    [pbr::OriginalName("INPUT_STORAGE_HOST_FAILED")] InputStorageHostFailed = 30210,
    [pbr::OriginalName("ALL_INPUT_INVALID_BYTES")] AllInputInvalidBytes = 30300,
    [pbr::OriginalName("INPUT_CLUSTER_SUCCESS")] InputClusterSuccess = 30400,
    [pbr::OriginalName("INPUT_CLUSTER_PENDING")] InputClusterPending = 30401,
    [pbr::OriginalName("INPUT_CLUSTER_FAILED")] InputClusterFailed = 30402,
    [pbr::OriginalName("INPUT_CLUSTER_IN_PROGRESS")] InputClusterInProgress = 30403,
    [pbr::OriginalName("INPUT_REINDEX_SUCCESS")] InputReindexSuccess = 30500,
    [pbr::OriginalName("INPUT_REINDEX_PENDING")] InputReindexPending = 30501,
    [pbr::OriginalName("INPUT_REINDEX_FAILED")] InputReindexFailed = 30502,
    [pbr::OriginalName("INPUT_REINDEX_IN_PROGRESS")] InputReindexInProgress = 30503,
    /// <summary>
    /// Input:Video related 31xxx -- Deprecated
    /// </summary>
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_SUCCESS")] InputVideoDownloadSuccess = 31000,
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_PENDING")] InputVideoDownloadPending = 31001,
    [pbr::OriginalName("INPUT_VIDEO_DOWNLOAD_FAILED")] InputVideoDownloadFailed = 31002,
    [pbr::OriginalName("INPUT_VIDEO_DUPLICATE")] InputVideoDuplicate = 31100,
    [pbr::OriginalName("INPUT_VIDEO_UNSUPPORTED_FORMAT")] InputVideoUnsupportedFormat = 31101,
    [pbr::OriginalName("INPUT_VIDEO_DOES_NOT_EXIST")] InputVideoDoesNotExist = 31102,
    [pbr::OriginalName("INPUT_VIDEO_PERMISSION_DENIED")] InputVideoPermissionDenied = 31103,
    [pbr::OriginalName("INPUT_VIDEO_INVALID_ARGUMENT")] InputVideoInvalidArgument = 31104,
    [pbr::OriginalName("INPUT_VIDEO_OVER_LIMIT")] InputVideoOverLimit = 31105,
    [pbr::OriginalName("INPUT_VIDEO_INVALID_URL")] InputVideoInvalidUrl = 31106,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_SUCCESS")] InputVideoModifySuccess = 31200,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_PENDING")] InputVideoModifyPending = 31201,
    [pbr::OriginalName("INPUT_VIDEO_MODIFY_FAILED")] InputVideoModifyFailed = 31203,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_HOST_FAILED")] InputVideoStorageHostFailed = 31210,
    [pbr::OriginalName("ALL_INPUT_VIDEOS_INVALID_BYTES")] AllInputVideosInvalidBytes = 31300,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_SUCCESS")] InputVideoProcessingSuccess = 31400,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_PENDING")] InputVideoProcessingPending = 31410,
    [pbr::OriginalName("INPUT_VIDEO_PROCESSING_FAILED")] InputVideoProcessingFailed = 31420,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_INCONSISTENCY")] InputVideoStorageInconsistency = 31430,
    [pbr::OriginalName("INPUT_VIDEO_STORAGE_FAILURE")] InputVideoStorageFailure = 31440,
    [pbr::OriginalName("INPUT_VIDEO_URL_GENERATION_FAILURE")] InputVideoUrlGenerationFailure = 31450,
    [pbr::OriginalName("INPUT_CONNECTION_FAILED")] InputConnectionFailed = 39996,
    [pbr::OriginalName("REQUEST_DISABLED_FOR_MAINTENANCE")] RequestDisabledForMaintenance = 39997,
    /// <summary>
    /// deprecate this one. Use REQUEST_DISABLED_FOR_MAINTENANCE
    /// </summary>
    [pbr::OriginalName("INPUT_WRITES_DISABLED_FOR_MAINTENANCE")] InputWritesDisabledForMaintenance = 39998,
    [pbr::OriginalName("INPUT_INVALID_REQUEST")] InputInvalidRequest = 39999,
    /// <summary>
    /// API formatting issues 4000x
    /// </summary>
    [pbr::OriginalName("PREDICT_INVALID_REQUEST")] PredictInvalidRequest = 40001,
    [pbr::OriginalName("SEARCH_INVALID_REQUEST")] SearchInvalidRequest = 40002,
    [pbr::OriginalName("CONCEPTS_INVALID_REQUEST")] ConceptsInvalidRequest = 40003,
    [pbr::OriginalName("STATS_INVALID_REQUEST")] StatsInvalidRequest = 40004,
    /// <summary>
    /// Other related 400xx
    /// </summary>
    [pbr::OriginalName("DATABASE_DUPLICATE_KEY")] DatabaseDuplicateKey = 40010,
    [pbr::OriginalName("DATABASE_STATEMENT_TIMEOUT")] DatabaseStatementTimeout = 40011,
    [pbr::OriginalName("DATABASE_INVALID_ROWS_AFFECTED")] DatabaseInvalidRowsAffected = 40012,
    [pbr::OriginalName("DATABASE_DEADLOCK_DETECTED")] DatabaseDeadlockDetected = 40013,
    [pbr::OriginalName("DATABASE_FAIL_TASK")] DatabaseFailTask = 40014,
    [pbr::OriginalName("DATABASE_FAIL_TO_GET_CONNECTIONS")] DatabaseFailToGetConnections = 40015,
    [pbr::OriginalName("DATABASE_TOO_MANY_CLIENTS")] DatabaseTooManyClients = 40016,
    [pbr::OriginalName("DATABASE_CONSTRAINT_VIOLATED")] DatabaseConstraintViolated = 40017,
    [pbr::OriginalName("DATABASE_CANCELED")] DatabaseCanceled = 40021,
    [pbr::OriginalName("ASYNC_WORKER_MULTI_ERRORS")] AsyncWorkerMultiErrors = 40020,
    [pbr::OriginalName("RPC_REQUEST_QUEUE_FULL")] RpcRequestQueueFull = 40030,
    [pbr::OriginalName("RPC_SERVER_UNAVAILABLE")] RpcServerUnavailable = 40031,
    [pbr::OriginalName("RPC_REQUEST_TIMEOUT")] RpcRequestTimeout = 40032,
    [pbr::OriginalName("RPC_MAX_MESSAGE_SIZE_EXCEEDED")] RpcMaxMessageSizeExceeded = 40033,
    [pbr::OriginalName("RPC_CANCELED")] RpcCanceled = 40035,
    [pbr::OriginalName("RPC_UNKNOWN_METHOD")] RpcUnknownMethod = 40036,
    [pbr::OriginalName("REQUEST_CANCELED_BY_USER")] RequestCanceledByUser = 40037,
    [pbr::OriginalName("CLUSTER_INTERNAL_FAILURE")] ClusterInternalFailure = 43040,
    /// <summary>
    /// could not connect to external services
    /// </summary>
    [pbr::OriginalName("EXTERNAL_CONNECTION_ERROR")] ExternalConnectionError = 40034,
    [pbr::OriginalName("QUERY_INVALID_SYNTAX")] QueryInvalidSyntax = 40050,
    /// <summary>
    /// Queue related errors 41xxx
    /// </summary>
    [pbr::OriginalName("QUEUE_CONN_ERROR")] QueueConnError = 41000,
    [pbr::OriginalName("QUEUE_CLOSE_REQUEST_TIMEOUT")] QueueCloseRequestTimeout = 41002,
    [pbr::OriginalName("QUEUE_CONN_CLOSED")] QueueConnClosed = 41003,
    [pbr::OriginalName("QUEUE_PUBLISH_ACK_TIMEOUT")] QueuePublishAckTimeout = 41004,
    [pbr::OriginalName("QUEUE_PUBLISH_ERROR")] QueuePublishError = 41005,
    [pbr::OriginalName("QUEUE_SUBSCRIPTION_TIMEOUT")] QueueSubscriptionTimeout = 41006,
    [pbr::OriginalName("QUEUE_SUBSCRIPTION_ERROR")] QueueSubscriptionError = 41007,
    [pbr::OriginalName("QUEUE_MARSHALLING_FAILED")] QueueMarshallingFailed = 41008,
    [pbr::OriginalName("QUEUE_UNMARSHALLING_FAILED")] QueueUnmarshallingFailed = 41009,
    [pbr::OriginalName("QUEUE_MAX_MSG_REDELIVERY_EXCEEDED")] QueueMaxMsgRedeliveryExceeded = 41010,
    [pbr::OriginalName("QUEUE_ACK_FAILURE")] QueueAckFailure = 41011,
    /// <summary>
    /// SQS related errors 411xx
    /// </summary>
    [pbr::OriginalName("SQS_OVERLIMIT")] SqsOverlimit = 41100,
    [pbr::OriginalName("SQS_INVALID_RECEIPT_HANDLE")] SqsInvalidReceiptHandle = 41101,
    [pbr::OriginalName("SQS_UNKNOWN")] SqsUnknown = 41102,
    /// <summary>
    ///Search related errors 43xxxx
    /// </summary>
    [pbr::OriginalName("SEARCH_INTERNAL_FAILURE")] SearchInternalFailure = 43001,
    [pbr::OriginalName("SEARCH_PROJECTION_FAILURE")] SearchProjectionFailure = 43002,
    [pbr::OriginalName("SEARCH_PREDICTION_FAILURE")] SearchPredictionFailure = 43003,
    [pbr::OriginalName("SEARCH_BY_NOT_FULLY_INDEXED_INPUT")] SearchByNotFullyIndexedInput = 43004,
    [pbr::OriginalName("SAVED_SEARCH_MODIFY_FAILED")] SavedSearchModifyFailed = 43005,
    [pbr::OriginalName("SEARCH_COUNTS_UNAVAILABLE")] SearchCountsUnavailable = 43006,
    /// <summary>
    /// Workflow evaluation err code
    /// </summary>
    [pbr::OriginalName("EVALUATION_QUEUED")] EvaluationQueued = 43100,
    [pbr::OriginalName("EVALUATION_IN_PROGRESS")] EvaluationInProgress = 43101,
    [pbr::OriginalName("EVALUATION_SUCCESS")] EvaluationSuccess = 43102,
    [pbr::OriginalName("EVALUATION_FAILED_TO_RETRIEVE_DATA")] EvaluationFailedToRetrieveData = 43103,
    [pbr::OriginalName("EVALUATION_INVALID_ARGUMENT")] EvaluationInvalidArgument = 43104,
    [pbr::OriginalName("EVALUATION_FAILED")] EvaluationFailed = 43105,
    [pbr::OriginalName("EVALUATION_PENDING")] EvaluationPending = 43106,
    [pbr::OriginalName("EVALUATION_TIMED_OUT")] EvaluationTimedOut = 43107,
    [pbr::OriginalName("EVALUATION_UNEXPECTED_ERROR")] EvaluationUnexpectedError = 43108,
    [pbr::OriginalName("EVALUATION_MIXED")] EvaluationMixed = 43109,
    /// <summary>
    /// Stripe 44xxx
    /// </summary>
    [pbr::OriginalName("STRIPE_EVENT_ERROR")] StripeEventError = 44001,
    [pbr::OriginalName("STRIPE_UNEXPECTED_ERROR")] StripeUnexpectedError = 44002,
    /// <summary>
    /// Redis/Cache 45xxx
    /// </summary>
    [pbr::OriginalName("CACHE_MISS")] CacheMiss = 45001,
    [pbr::OriginalName("REDIS_SCRIPT_EXITED_WITH_FAILURE")] RedisScriptExitedWithFailure = 45002,
    [pbr::OriginalName("REDIS_STREAM_ERR")] RedisStreamErr = 45003,
    [pbr::OriginalName("REDIS_NO_CONSUMERS")] RedisNoConsumers = 45004,
    [pbr::OriginalName("REDIS_STREAM_BACKOFF")] RedisStreamBackoff = 45005,
    /// <summary>
    /// Sift Science 46xxx
    /// </summary>
    [pbr::OriginalName("SIGNUP_EVENT_ERROR")] SignupEventError = 46001,
    [pbr::OriginalName("SIGNUP_FLAGGED")] SignupFlagged = 46002,
    [pbr::OriginalName("FILETYPE_UNSUPPORTED")] FiletypeUnsupported = 46003,
    [pbr::OriginalName("LOGIN_EVENT_ERROR")] LoginEventError = 46004,
    [pbr::OriginalName("SIFT_UNCATEGORIZED_ERROR")] SiftUncategorizedError = 46005,
    /// <summary>
    /// Application counts related errors 470xx
    /// </summary>
    [pbr::OriginalName("APP_COUNT_INVALID_MESSAGE")] AppCountInvalidMessage = 47001,
    [pbr::OriginalName("APP_COUNT_UPDATE_INCREMENT_FAILED")] AppCountUpdateIncrementFailed = 47002,
    [pbr::OriginalName("APP_COUNT_REBUILD_FAILED")] AppCountRebuildFailed = 47003,
    [pbr::OriginalName("APP_COUNT_INTERNAL_FAILURE")] AppCountInternalFailure = 47004,
    /// <summary>
    /// Media processor related errors 471xx -- DEPRECATED
    /// </summary>
    [pbr::OriginalName("MP_DOWNLOAD_ERROR")] MpDownloadError = 47101,
    [pbr::OriginalName("MP_RESOLVE_DNS_ERROR")] MpResolveDnsError = 47102,
    [pbr::OriginalName("MP_DOWNLOAD_MAX_SIZE_EXCEEDED_ERROR")] MpDownloadMaxSizeExceededError = 47103,
    [pbr::OriginalName("MP_IMAGE_DECODE_ERROR")] MpImageDecodeError = 47104,
    [pbr::OriginalName("MP_INVALID_ARGUMENT")] MpInvalidArgument = 47105,
    [pbr::OriginalName("MP_IMAGE_PROCESSING_ERROR")] MpImageProcessingError = 47106,
    /// <summary>
    /// DataTier related error 472xx
    /// </summary>
    [pbr::OriginalName("DATATIER_CONN_ERROR")] DatatierConnError = 47201,
    /// <summary>
    /// User legal consent stauts related 50xxx
    /// </summary>
    [pbr::OriginalName("USER_CONSENT_FACE")] UserConsentFace = 50001,
    /// <summary>
    /// Workers 51xxx
    /// </summary>
    [pbr::OriginalName("WORKER_MISSING")] WorkerMissing = 51000,
    [pbr::OriginalName("WORKER_ACTIVE")] WorkerActive = 51001,
    [pbr::OriginalName("WORKER_INACTIVE")] WorkerInactive = 51002,
    /// <summary>
    /// Collectors 52xxx
    /// </summary>
    [pbr::OriginalName("COLLECTOR_MISSING")] CollectorMissing = 52000,
    [pbr::OriginalName("COLLECTOR_ACTIVE")] CollectorActive = 52001,
    [pbr::OriginalName("COLLECTOR_INACTIVE")] CollectorInactive = 52002,
    [pbr::OriginalName("COLLECTOR_POST_INPUT_FAILED")] CollectorPostInputFailed = 52003,
    /// <summary>
    /// SSO 53xxx
    /// </summary>
    [pbr::OriginalName("SSO_IDENTITY_PROVIDER_DOES_NOT_EXIST")] SsoIdentityProviderDoesNotExist = 53001,
    /// <summary>
    /// Tasks 54xxx
    /// The task was created.
    /// </summary>
    [pbr::OriginalName("TASK_IN_PROGRESS")] TaskInProgress = 54001,
    /// <summary>
    /// The task is completed.
    /// </summary>
    [pbr::OriginalName("TASK_DONE")] TaskDone = 54002,
    /// <summary>
    /// The task is marked as abandoned.
    /// </summary>
    [pbr::OriginalName("TASK_WONT_DO")] TaskWontDo = 54003,
    /// <summary>
    /// An error occurred during add-task-annotations or add-auto-annotations pipeline.
    /// </summary>
    [pbr::OriginalName("TASK_FAILED")] TaskFailed = 54005,
    /// <summary>
    /// When an Auto Annotation task job has finished processing its last batch and is waiting for more dataset assets.
    /// </summary>
    [pbr::OriginalName("TASK_IDLE")] TaskIdle = 54006,
    /// <summary>
    /// The task operation is in conflict with the current state of the server.
    /// </summary>
    [pbr::OriginalName("TASK_CONFLICT")] TaskConflict = 54100,
    /// <summary>
    /// Certain task-related scenarios are not implemented.
    /// </summary>
    [pbr::OriginalName("TASK_NOT_IMPLEMENTED")] TaskNotImplemented = 54101,
    /// <summary>
    /// Task was not found.
    /// </summary>
    [pbr::OriginalName("TASK_MISSING")] TaskMissing = 54102,
    /// <summary>
    /// Not allowed to perform a task-related action.
    /// </summary>
    [pbr::OriginalName("TASK_PERMISSION_DENIED")] TaskPermissionDenied = 54103,
    /// <summary>
    /// Task Assignments 542xx
    /// </summary>
    [pbr::OriginalName("TASK_ASSIGNMENT_SUCCESS")] TaskAssignmentSuccess = 54200,
    [pbr::OriginalName("TASK_ASSIGNMENT_PENDING")] TaskAssignmentPending = 54201,
    [pbr::OriginalName("TASK_ASSIGNMENT_AWAITING_REVIEW")] TaskAssignmentAwaitingReview = 54202,
    [pbr::OriginalName("TASK_ASSIGNMENT_AWAITING_CONSENSUS_REVIEW")] TaskAssignmentAwaitingConsensusReview = 54203,
    [pbr::OriginalName("TASK_ASSIGNMENT_REJECTED")] TaskAssignmentRejected = 54204,
    /// <summary>
    /// Task Assignment Reviews 543xx
    /// </summary>
    [pbr::OriginalName("TASK_ASSIGNMENT_REVIEW_SUCCESS")] TaskAssignmentReviewSuccess = 54300,
    [pbr::OriginalName("TASK_ASSIGNMENT_REVIEW_PENDING")] TaskAssignmentReviewPending = 54301,
    [pbr::OriginalName("TASK_ASSIGNMENT_REVIEW_DISMISSED")] TaskAssignmentReviewDismissed = 54302,
    /// <summary>
    /// Label Order Related Status Code 55xxx
    /// </summary>
    [pbr::OriginalName("LABEL_ORDER_PENDING")] LabelOrderPending = 55001,
    [pbr::OriginalName("LABEL_ORDER_IN_PROGRESS")] LabelOrderInProgress = 55002,
    [pbr::OriginalName("LABEL_ORDER_SUCCESS")] LabelOrderSuccess = 55003,
    [pbr::OriginalName("LABEL_ORDER_CANCELED")] LabelOrderCanceled = 55004,
    /// <summary>
    /// License Related Status Code 600xx
    /// </summary>
    [pbr::OriginalName("LICENSE_ACTIVE")] LicenseActive = 60000,
    [pbr::OriginalName("LICENSE_DOES_NOT_EXIST")] LicenseDoesNotExist = 60001,
    [pbr::OriginalName("LICENSE_NEED_UPDATE")] LicenseNeedUpdate = 60002,
    [pbr::OriginalName("LICENSE_EXPIRED")] LicenseExpired = 60003,
    [pbr::OriginalName("LICENSE_REVOKED")] LicenseRevoked = 60004,
    /// <summary>
    /// hidden state not reflected to users
    /// </summary>
    [pbr::OriginalName("LICENSE_DELETED")] LicenseDeleted = 60005,
    [pbr::OriginalName("LICENSE_VOLUME_EXCEEDED")] LicenseVolumeExceeded = 60006,
    /// <summary>
    /// Password Related Status Code
    /// </summary>
    [pbr::OriginalName("PASSWORD_VALIDATION_SUCCESS")] PasswordValidationSuccess = 61000,
    [pbr::OriginalName("PASSWORD_VALIDATION_FAILED")] PasswordValidationFailed = 61001,
    [pbr::OriginalName("PASSWORDPOLICY_INVALID_ARGUMENT")] PasswordpolicyInvalidArgument = 61002,
    /// <summary>
    /// Feature flags status code
    /// </summary>
    [pbr::OriginalName("FEATUREFLAG_CONFIG_NOT_FOUND")] FeatureflagConfigNotFound = 62000,
    [pbr::OriginalName("FEATUREFLAG_INVALID_ARGUMENT")] FeatureflagInvalidArgument = 62001,
    [pbr::OriginalName("FEATUREFLAG_BLOCKED")] FeatureflagBlocked = 62002,
    [pbr::OriginalName("FEATUREFLAG_NOT_FOUND")] FeatureflagNotFound = 62003,
    /// <summary>
    /// Maintenance status code
    /// </summary>
    [pbr::OriginalName("MAINTENANCE_SUCCESS")] MaintenanceSuccess = 63000,
    [pbr::OriginalName("MAINTENANCE_FAILED")] MaintenanceFailed = 63001,
    /// <summary>
    /// Datasets 64xxx
    /// The dataset version is pending to be processed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_PENDING")] DatasetVersionPending = 64005,
    /// <summary>
    /// The dataset version is currently being processed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_IN_PROGRESS")] DatasetVersionInProgress = 64010,
    /// <summary>
    /// The dataset version is ready to be used.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_READY")] DatasetVersionReady = 64015,
    /// <summary>
    /// An error occurred during the dataset version processing.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_FAILURE")] DatasetVersionFailure = 64020,
    /// <summary>
    /// An unexpected error occurred during the dataset version processing.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_UNEXPECTED_ERROR")] DatasetVersionUnexpectedError = 64025,
    /// <summary>
    /// An alteration to dataset version would create a conflict
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_CONFLICT")] DatasetVersionConflict = 64030,
    /// <summary>
    /// The dataset input was successfully added.
    /// </summary>
    [pbr::OriginalName("DATASET_INPUT_SUCCESS")] DatasetInputSuccess = 64100,
    /// <summary>
    /// The dataset input is a duplicate.
    /// Deprecated: Unused.
    /// </summary>
    [pbr::OriginalName("DATASET_INPUT_DUPLICATE")] DatasetInputDuplicate = 64101,
    /// <summary>
    /// The dataset version export is completed.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_SUCCESS")] DatasetVersionExportSuccess = 64200,
    /// <summary>
    /// The dataset version is pending to be exported.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_PENDING")] DatasetVersionExportPending = 64201,
    /// <summary>
    /// An error occurred during the dataset version export.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_FAILED")] DatasetVersionExportFailed = 64202,
    /// <summary>
    /// The dataset version is currently being exported.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_IN_PROGRESS")] DatasetVersionExportInProgress = 64203,
    /// <summary>
    /// An unexpected error occurred during the dataset version export.
    /// </summary>
    [pbr::OriginalName("DATASET_VERSION_EXPORT_UNEXPECTED_ERROR")] DatasetVersionExportUnexpectedError = 64204,
    /// <summary>
    /// Generic Job status codes
    /// </summary>
    [pbr::OriginalName("JOB_QUEUED")] JobQueued = 64000,
    [pbr::OriginalName("JOB_RUNNING")] JobRunning = 64001,
    [pbr::OriginalName("JOB_COMPLETED")] JobCompleted = 64002,
    [pbr::OriginalName("JOB_FAILED")] JobFailed = 64003,
    [pbr::OriginalName("JOB_CANCELLED")] JobCancelled = 64004,
    [pbr::OriginalName("JOB_UNEXPECTED_ERROR")] JobUnexpectedError = 64006,
    [pbr::OriginalName("JOB_CONFLICT")] JobConflict = 64007,
    /// <summary>
    ///auth issues
    /// </summary>
    [pbr::OriginalName("AUTH_MISSING_IDP_ASSOC")] AuthMissingIdpAssoc = 65000,
    [pbr::OriginalName("LIST_OBJECTS_FAILED")] ListObjectsFailed = 66000,
    [pbr::OriginalName("ARCHIVE_EXTRACT_FAILED")] ArchiveExtractFailed = 67000,
    /// <summary>
    /// Multipart uploading status codes
    /// </summary>
    [pbr::OriginalName("UPLOAD_IN_PROGRESS")] UploadInProgress = 68000,
    [pbr::OriginalName("UPLOAD_DONE")] UploadDone = 68001,
    [pbr::OriginalName("UPLOAD_FAILED")] UploadFailed = 68002,
    [pbr::OriginalName("UPLOAD_UNEXPECTED_ERROR")] UploadUnexpectedError = 68003,
    [pbr::OriginalName("UPLOAD_EXPIRED")] UploadExpired = 68004,
    [pbr::OriginalName("UPLOAD_CANCELED")] UploadCanceled = 68005,
    [pbr::OriginalName("UPLOAD_CONFLICT")] UploadConflict = 68006,
    /// <summary>
    /// Billing related issues: 69xxx
    /// </summary>
    [pbr::OriginalName("BILLING_INVALID_INFO")] BillingInvalidInfo = 69000,
    [pbr::OriginalName("BILLING_MISSING_TOKENS")] BillingMissingTokens = 69001,
    /// <summary>
    /// Logs related issues: 70000;
    /// </summary>
    [pbr::OriginalName("LOG_ENTRIES_INVALID_REQUEST")] LogEntriesInvalidRequest = 70000,
    /// <summary>
    /// Internal issues: 98xxx
    /// </summary>
    [pbr::OriginalName("INTERNAL_SERVER_ISSUE")] InternalServerIssue = 98004,
    [pbr::OriginalName("INTERNAL_FETCHING_ISSUE")] InternalFetchingIssue = 98005,
    [pbr::OriginalName("INTERNAL_DATABASE_ISSUE")] InternalDatabaseIssue = 98006,
    [pbr::OriginalName("INTERNAL_CONTEXT_CANCELED")] InternalContextCanceled = 98008,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_TIMEOUT")] InternalUnexpectedTimeout = 98009,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_V1")] InternalUnexpectedV1 = 98010,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_PANIC")] InternalUnexpectedPanic = 98011,
    [pbr::OriginalName("INTERNAL_UNEXPECTED_SPIRE")] InternalUnexpectedSpire = 98012,
    [pbr::OriginalName("INTERNAL_REDIS_UNAVAILABLE")] InternalRedisUnavailable = 98013,
    [pbr::OriginalName("INTERNAL_RESOURCE_EXHAUSTED")] InternalResourceExhausted = 98014,
    [pbr::OriginalName("INTERNAL_REDIS_UNCATEGORIZED")] InternalRedisUncategorized = 98015,
    [pbr::OriginalName("INTERNAL_AWS_UNCATEGORIZED")] InternalAwsUncategorized = 98016,
    [pbr::OriginalName("INTERNAL_AZURE_UNCATEGORIZED")] InternalAzureUncategorized = 98017,
    [pbr::OriginalName("INTERNAL_VECTORDB_UNCATEGORIZED")] InternalVectordbUncategorized = 98018,
    [pbr::OriginalName("INTERNAL_ORACLE_UNCATEGORIZED")] InternalOracleUncategorized = 98019,
    [pbr::OriginalName("INTERNAL_VULTR_UNCATEGORIZED")] InternalVultrUncategorized = 98020,
    [pbr::OriginalName("INTERNAL_GCP_UNCATEGORIZED")] InternalGcpUncategorized = 98021,
    /// <summary>
    /// Uncategorized: 99xxx: move off as soon as known
    /// </summary>
    [pbr::OriginalName("CONN_UNCATEGORIZED")] ConnUncategorized = 99001,
    [pbr::OriginalName("MODEL_UNCATEGORIZED")] ModelUncategorized = 99002,
    [pbr::OriginalName("INPUT_UNCATEGORIZED")] InputUncategorized = 99003,
    [pbr::OriginalName("ANNOTATION_UNCATEGORIZED")] AnnotationUncategorized = 99004,
    [pbr::OriginalName("BILLING_UNCATEGORIZED")] BillingUncategorized = 99005,
    [pbr::OriginalName("INTERNAL_UNCATEGORIZED")] InternalUncategorized = 99009,
    /// <summary>
    /// Deprecated: migrate off to one of the internal issues
    /// </summary>
    [pbr::OriginalName("BAD_REQUEST")] BadRequest = 90400,
    /// <summary>
    /// Deprecated: migrate off to one of the internal issues
    /// </summary>
    [pbr::OriginalName("SERVER_ERROR")] ServerError = 90500,
  }

  #endregion

}

#endregion Designer generated code
