// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/utils/test_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Api.Utils {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/utils/test_proto.proto</summary>
  public static partial class TestProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/utils/test_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilwcm90by9jbGFyaWZhaS9hcGkvdXRpbHMvdGVzdF9wcm90by5wcm90bxIS",
            "Y2xhcmlmYWkuYXBpLnV0aWxzGilwcm90by9jbGFyaWZhaS9hcGkvdXRpbHMv",
            "ZXh0ZW5zaW9ucy5wcm90byLlAQoJVGVzdFByb3RvEgoKAmlkGAEgASgJEigK",
            "B21lc3NhZ2UYAiABKAlCF4C1GAGKtRgPcHJvdG9zIGFyZSBjb29sEhYKBXZh",
            "bHVlGAMgASgBQgfVtRgAAIA/EhMKC2ltYWdlX2J5dGVzGAQgASgMEhYKDHN0",
            "cmluZ19vbmVvZhgFIAEoCUgAEhQKCmJvb2xfb25lb2YYBiABKAhIABI3Cg1t",
            "ZXNzYWdlX29uZW9mGAcgASgLMh4uY2xhcmlmYWkuYXBpLnV0aWxzLlRlc3RQ",
            "cm90bzJIAEIOCgxvbmVfb2ZfZmllbGQiJgoKVGVzdFByb3RvMhIKCgJpZBgB",
            "IAEoCRIMCgRmbGlwGAIgASgIQjoKG2NvbS5jbGFyaWZhaS5ncnBjLmFwaS51",
            "dGlsc1ABWhJjbGFyaWZhaS9hcGkvdXRpbHOiAgRDQUlQYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Clarifai.Api.Utils.ExtensionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Clarifai.Api.Utils.TestProto), global::Clarifai.Api.Utils.TestProto.Parser, new[]{ "Id", "Message", "Value", "ImageBytes", "StringOneof", "BoolOneof", "MessageOneof" }, new[]{ "OneOfField" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Clarifai.Api.Utils.TestProto2), global::Clarifai.Api.Utils.TestProto2.Parser, new[]{ "Id", "Flip" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TestProto : pb::IMessage<TestProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestProto> _parser = new pb::MessageParser<TestProto>(() => new TestProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Clarifai.Api.Utils.TestProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestProto(TestProto other) : this() {
      id_ = other.id_;
      message_ = other.message_;
      value_ = other.value_;
      imageBytes_ = other.imageBytes_;
      switch (other.OneOfFieldCase) {
        case OneOfFieldOneofCase.StringOneof:
          StringOneof = other.StringOneof;
          break;
        case OneOfFieldOneofCase.BoolOneof:
          BoolOneof = other.BoolOneof;
          break;
        case OneOfFieldOneofCase.MessageOneof:
          MessageOneof = other.MessageOneof.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestProto Clone() {
      return new TestProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private double value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "image_bytes" field.</summary>
    public const int ImageBytesFieldNumber = 4;
    private pb::ByteString imageBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ImageBytes {
      get { return imageBytes_; }
      set {
        imageBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "string_oneof" field.</summary>
    public const int StringOneofFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringOneof {
      get { return oneOfFieldCase_ == OneOfFieldOneofCase.StringOneof ? (string) oneOfField_ : ""; }
      set {
        oneOfField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        oneOfFieldCase_ = OneOfFieldOneofCase.StringOneof;
      }
    }

    /// <summary>Field number for the "bool_oneof" field.</summary>
    public const int BoolOneofFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BoolOneof {
      get { return oneOfFieldCase_ == OneOfFieldOneofCase.BoolOneof ? (bool) oneOfField_ : false; }
      set {
        oneOfField_ = value;
        oneOfFieldCase_ = OneOfFieldOneofCase.BoolOneof;
      }
    }

    /// <summary>Field number for the "message_oneof" field.</summary>
    public const int MessageOneofFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Clarifai.Api.Utils.TestProto2 MessageOneof {
      get { return oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof ? (global::Clarifai.Api.Utils.TestProto2) oneOfField_ : null; }
      set {
        oneOfField_ = value;
        oneOfFieldCase_ = value == null ? OneOfFieldOneofCase.None : OneOfFieldOneofCase.MessageOneof;
      }
    }

    private object oneOfField_;
    /// <summary>Enum of possible cases for the "one_of_field" oneof.</summary>
    public enum OneOfFieldOneofCase {
      None = 0,
      StringOneof = 5,
      BoolOneof = 6,
      MessageOneof = 7,
    }
    private OneOfFieldOneofCase oneOfFieldCase_ = OneOfFieldOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OneOfFieldOneofCase OneOfFieldCase {
      get { return oneOfFieldCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOneOfField() {
      oneOfFieldCase_ = OneOfFieldOneofCase.None;
      oneOfField_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Message != other.Message) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Value, other.Value)) return false;
      if (ImageBytes != other.ImageBytes) return false;
      if (StringOneof != other.StringOneof) return false;
      if (BoolOneof != other.BoolOneof) return false;
      if (!object.Equals(MessageOneof, other.MessageOneof)) return false;
      if (OneOfFieldCase != other.OneOfFieldCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Value != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Value);
      if (ImageBytes.Length != 0) hash ^= ImageBytes.GetHashCode();
      if (oneOfFieldCase_ == OneOfFieldOneofCase.StringOneof) hash ^= StringOneof.GetHashCode();
      if (oneOfFieldCase_ == OneOfFieldOneofCase.BoolOneof) hash ^= BoolOneof.GetHashCode();
      if (oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof) hash ^= MessageOneof.GetHashCode();
      hash ^= (int) oneOfFieldCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Value != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Value);
      }
      if (ImageBytes.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ImageBytes);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.StringOneof) {
        output.WriteRawTag(42);
        output.WriteString(StringOneof);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.BoolOneof) {
        output.WriteRawTag(48);
        output.WriteBool(BoolOneof);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof) {
        output.WriteRawTag(58);
        output.WriteMessage(MessageOneof);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Value != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Value);
      }
      if (ImageBytes.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ImageBytes);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.StringOneof) {
        output.WriteRawTag(42);
        output.WriteString(StringOneof);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.BoolOneof) {
        output.WriteRawTag(48);
        output.WriteBool(BoolOneof);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof) {
        output.WriteRawTag(58);
        output.WriteMessage(MessageOneof);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Value != 0D) {
        size += 1 + 8;
      }
      if (ImageBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ImageBytes);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.StringOneof) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringOneof);
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.BoolOneof) {
        size += 1 + 1;
      }
      if (oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MessageOneof);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Value != 0D) {
        Value = other.Value;
      }
      if (other.ImageBytes.Length != 0) {
        ImageBytes = other.ImageBytes;
      }
      switch (other.OneOfFieldCase) {
        case OneOfFieldOneofCase.StringOneof:
          StringOneof = other.StringOneof;
          break;
        case OneOfFieldOneofCase.BoolOneof:
          BoolOneof = other.BoolOneof;
          break;
        case OneOfFieldOneofCase.MessageOneof:
          if (MessageOneof == null) {
            MessageOneof = new global::Clarifai.Api.Utils.TestProto2();
          }
          MessageOneof.MergeFrom(other.MessageOneof);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 25: {
            Value = input.ReadDouble();
            break;
          }
          case 34: {
            ImageBytes = input.ReadBytes();
            break;
          }
          case 42: {
            StringOneof = input.ReadString();
            break;
          }
          case 48: {
            BoolOneof = input.ReadBool();
            break;
          }
          case 58: {
            global::Clarifai.Api.Utils.TestProto2 subBuilder = new global::Clarifai.Api.Utils.TestProto2();
            if (oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof) {
              subBuilder.MergeFrom(MessageOneof);
            }
            input.ReadMessage(subBuilder);
            MessageOneof = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 25: {
            Value = input.ReadDouble();
            break;
          }
          case 34: {
            ImageBytes = input.ReadBytes();
            break;
          }
          case 42: {
            StringOneof = input.ReadString();
            break;
          }
          case 48: {
            BoolOneof = input.ReadBool();
            break;
          }
          case 58: {
            global::Clarifai.Api.Utils.TestProto2 subBuilder = new global::Clarifai.Api.Utils.TestProto2();
            if (oneOfFieldCase_ == OneOfFieldOneofCase.MessageOneof) {
              subBuilder.MergeFrom(MessageOneof);
            }
            input.ReadMessage(subBuilder);
            MessageOneof = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TestProto2 : pb::IMessage<TestProto2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestProto2> _parser = new pb::MessageParser<TestProto2>(() => new TestProto2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestProto2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Clarifai.Api.Utils.TestProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestProto2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestProto2(TestProto2 other) : this() {
      id_ = other.id_;
      flip_ = other.flip_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestProto2 Clone() {
      return new TestProto2(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "flip" field.</summary>
    public const int FlipFieldNumber = 2;
    private bool flip_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Flip {
      get { return flip_; }
      set {
        flip_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestProto2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestProto2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Flip != other.Flip) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Flip != false) hash ^= Flip.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Flip != false) {
        output.WriteRawTag(16);
        output.WriteBool(Flip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Flip != false) {
        output.WriteRawTag(16);
        output.WriteBool(Flip);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Flip != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestProto2 other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Flip != false) {
        Flip = other.Flip;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Flip = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Flip = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
