// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/auth/types/types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Auth.Types {

  /// <summary>Holder for reflection information generated from proto/clarifai/auth/types/types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/auth/types/types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVwcm90by9jbGFyaWZhaS9hdXRoL3R5cGVzL3R5cGVzLnByb3RvEhNjbGFy",
            "aWZhaS5hdXRoLnR5cGVzKmAKCEF1dGhUeXBlEgkKBXVuZGVmEAASCgoGTm9B",
            "dXRoEAESCwoHS2V5QXV0aBACEhQKEFNlc3Npb25Ub2tlbkF1dGgQAxINCglB",
            "ZG1pbkF1dGgQBBILCgdQQVRBdXRoEAVCLgocY29tLmNsYXJpZmFpLmdycGMu",
            "YXV0aC50eXBlc1ABWgV0eXBlc6ICBENBSVBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Clarifai.Auth.Types.AuthType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Authorization type for endpoints.
  /// </summary>
  public enum AuthType {
    /// <summary>
    /// introduce undef so that the zero (default/unset) value of the enum is not a real
    /// permission.  undef is only present for this purpose and should not be used
    /// to indicate any "real" value.
    /// </summary>
    [pbr::OriginalName("undef")] Undef = 0,
    /// <summary>
    /// No authorization need for this endpoint.
    /// </summary>
    [pbr::OriginalName("NoAuth")] NoAuth = 1,
    /// <summary>
    /// This authorization requires API keys (both app-spceific keys and personal access tokens).
    /// The endpoints that use this AuthType may also include a list of
    /// clarifai.auth.utils.cl_depending_scopes.
    /// </summary>
    [pbr::OriginalName("KeyAuth")] KeyAuth = 2,
    /// <summary>
    /// This uses a session token from your web browser. This is reserved for users/account level APIs
    /// that are only needed in a browser.
    /// </summary>
    [pbr::OriginalName("SessionTokenAuth")] SessionTokenAuth = 3,
    /// <summary>
    /// This uses a special token for admin access to the APIs.
    /// </summary>
    [pbr::OriginalName("AdminAuth")] AdminAuth = 4,
    /// <summary>
    /// This authorization requires personal access tokens. This is used for endpoints such as
    /// /users/{user_id}/apps which are not specific. An app-specific API key will not work
    /// when PATAuth is used.
    /// </summary>
    [pbr::OriginalName("PATAuth")] Patauth = 5,
  }

  #endregion

}

#endregion Designer generated code
